skip_branch_with_pr: true

image:
  - Visual Studio 2015

build:
  verbosity: detailed

clone_folder: c:\projects\cdt-plusplus

shallow_clone: true

configuration: Release

install:
  - mkdir C:\projects\dev
  - cd C:\projects\dev

  # Install Ninja
  - set NINJA_URL="https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-win.zip"
  - appveyor DownloadFile %NINJA_URL% -FileName ninja.zip
  - 7z x ninja.zip -oC:\projects\dev\ninja > nul
  - set PATH=%PATH%;C:\projects\dev\ninja
  - ninja --version
  # Install CMake
  - set CMAKE_URL="https://cmake.org/files/v3.8/cmake-3.8.2-win64-x64.zip"
  - appveyor DownloadFile %CMAKE_URL% -FileName cmake.zip
  - 7z x cmake.zip -oC:\projects\dev
  - set PATH=%PATH%;C:\projects\dev\cmake\bin
  - cmake --version
  # Setup Clang-cl
  - set PATH=%PATH%;"C:\Program Files\LLVM\bin"
  - clang-cl -v
  - set CC=clang-cl
  - set CXX=clang-cl
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
  # Install Boost
  - nuget install boost
  - cd C:\projects\dev\boost.1.64.0.0
  - set PATH=%PATH%;C:\projects\dev\boost.1.64.0.0\lib
  # Install GMP
  - cd C:\projects\dev
  - nuget install libgmp_vc120
#  - set PATH=%PATH%;C:\projects\dev\libgmp_vc120.5.1.3.2\build\native\include
#  - set PATH=%PATH%;C:\projects\dev\libgmp_vc120.5.1.3.2\build\native\bin
  # Install CGAL
  - set CGAL_URL="https://github.com/CGAL/releases/archive/CGAL-4.9.1.zip"
  - appveyor DownloadFile %CGAL_URL% -FileName cgal.zip
  - 7z x cgal.zip -oC:\projects\dev
  - set PATH=%PATH%;C:\projects\dev\releases-CGAL-4.9.1
  - cd C:\projects\dev\releases-CGAL-4.9.1
  - dir # Debugging
  - cmake -DCMAKE_BUILD_TYPE=Release -DBoost_USE_STATIC_LIBS=ON -DWITH_Eigen3=ON -DBOOST_ROOT=${BOOST_DIR} -DGMP_INCLUDE_DIR:PATH="C:\projects\dev\libgmp_vc120.5.1.3.2\build\native\bin" _DGMP_LIBRARIES_DIR:PATH="C:\projects\dev\libgmp_vc120.5.1.3.2\build\native\include" -DCMAKE_CXX_COMPILER=clang-cl -GNinja .
  - cmake --build .

before_build:
  - cd C:\projects\CDT-plusplus

build_script:
  - mkdir build
  - cd build
  - cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DGMOCK_TESTS:BOOL=OFF ..

on_success:
  - cmake --build . --target test

notifications:

  - provider: Email
    to:
      - acgetchell@ucdavis.edu
    subject: 'Build {{status}}'
    message: "{{message}}, {{commitId}}, ..."
    on_build_status_changed: true

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))