version: 0.1.8.{build}

platform:
  - x64

environment:
  #  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  VCPKG_DEFAULT_TRIPLET: x64-windows

cache:
  - c:\tools\vcpkg\installed\


image:
  - Visual Studio 2017

skip_tags: true

skip_branch_with_pr: true

build:
  verbosity: detailed

clone_folder: c:\projects\cdt-test

shallow_clone: true

configuration: Release

clone_script:
  - cmd: >-
      git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
      && cd %APPVEYOR_BUILD_FOLDER%
      && git checkout -qf %APPVEYOR_REPO_COMMIT%
      && git submodule update --init --recursive

install:
  #  - if not exist "c:\projects\dev" (
  #      mkdir c:\projects\dev
  #      cd c:\projects\dev
  #      set NINJA_URL="https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip"
  #      appveyor DownloadFile %NINJA_URL% -FileName ninja.zip
  #      7z x ninja.zip -oC:\projects\dev\ninja > nul
  #    )
  - mkdir C:\projects\dev
  - cd C:\projects\dev
  # Install Ninja
  - set NINJA_URL="https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-win.zip"
  - appveyor DownloadFile %NINJA_URL% -FileName ninja.zip
  - 7z x ninja.zip -oC:\projects\dev\ninja > nul
  - set PATH=%PATH%;C:\projects\dev\ninja
  - ninja --version
  - set CMAKE_MAKE_PROGRAM=C:\projects\dev\ninja\ninja.exe
  # Verify CMake
  - cmake --version
  - cd c:\tools\vcpkg
  # Update ports
  - git pull
  # Update vcpkg
  - .\bootstrap-vcpkg.bat
  # Enable integration for Visual Studio/MSBuild
  - vcpkg integrate install
  # Install required libraries
  - vcpkg install catch2
  - vcpkg install docopt
  - vcpkg install fmt
  - vcpkg install ms-gsl
  - vcpkg install eigen3
  - vcpkg install tbb
  - vcpkg install cgal
  # Upgrade required libraries
  - vcpkg upgrade --no-dry-run
  - vcpkg list
  # Setup Clang-cl
  - set PATH=%PATH%;"C:\Program Files\LLVM\bin"
  - clang-cl -v
  - set CC=clang-cl -mrtm
  - set CXX=clang-cl -mrtm
  # Visual Studio 2017
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - set CMAKE_CXX_COMPILER="C:\Program Files\LLVM\bin\clang-cl"
  # Remove conflicting OpenSSL directories
#  - rd /s /q c:\OpenSSL-v11-Win32
#  - rd /s /q c:\OpenSSL-v11-Win64



before_build:
  - cd %APPVEYOR_BUILD_FOLDER%

build_script:
  - mkdir build
  - cd build
  #  - cmake -G Ninja -DCMAKE_MAKE_PROGRAM=c:\projects\dev\ninja\ninja.exe -DVCPKG_TARGET_TRIPLET=x86-windows -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake ..
  - cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake ..
  - cmake --build .

on_success:
  - cmake --build . --target test & exit 0

notifications:
  - provider: Email
    to:
      - acgetchell@ucdavis.edu
    on_build_status_changed: true

#on_failure:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
