skip_branch_with_pr: true

image:
  - Visual Studio 2017

build:
  verbosity: detailed

clone_folder: c:\projects\cdt-plusplus

shallow_clone: true

configuration: Release

install:
  - mkdir C:\projects\dev
  - cd C:\projects\dev

  # Install Ninja
  - set NINJA_URL="https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-win.zip"
  - appveyor DownloadFile %NINJA_URL% -FileName ninja.zip
  - 7z x ninja.zip -oC:\projects\dev\ninja > nul
  - set PATH=C:\projects\dev\ninja;%PATH%
  - ninja --version
  # Install CMake
  - set CMAKE_URL="https://cmake.org/files/v3.8/cmake-3.8.1-win64-x64.zip"
  - appveyor DownloadFile %CMAKE_URL% -FileName cmake.zip
  - 7z x cmake.zip -oC:\projects\dev
  - set PATH=C:\projects\dev\cmake\bin;%PATH%
  - cmake --version
  # Setup Clang-cl
  - set PATH="C:\Program Files\LLVM\bin";%PATH%
  - clang-cl -v
  - set CC=clang-cl
  - set CXX=clang-cl
  # Install Boost
  - nuget install boost
  - dir # Debugging
  - cd C:\projects\dev\boost.1.64.0.0
  - dir
  #- set BOOST_LIBRARYDIR="C:\projects\dev\boost.1.64.0.0\lib"
  #- cd lib
  #- dir
  #- cd ..
  #- set BOOST_INCLUDEDIR="C:\projects\dev\build"
  #- cd build
  #- dir
  #- cd ..
  - set PATH=C:\projects\dev\boost.1.64.0.0\lib;%PATH%
  # Install GMP
  - nuget install libgmp_vc120
  - set PATH=C:\projects\dev\libgmp_vc120.5.1.3.2\build\native\include;%PATH%
  - set PATH=C:\projects\dev\libgmp_vc120.5.1.3.2\build\native\bin;%PATH%
  # Install CGAL
  - set CGAL_URL="https://github.com/CGAL/releases/archive/CGAL-4.9.1.zip"
  - appveyor DownloadFile %CGAL_URL% -FileName cgal.zip
  - 7z x cgal.zip -oC:\projects\dev
  - set PATH=C:\projects\dev\releases-CGAL-4.9.1;%PATH%
  - cd C:\projects\dev\releases-CGAL-4.9.1
  - dir # Debugging
  - cmake -DCMAKE_BUILD_TYPE=Release -DBoost_USE_STATIC_LIBS=ON -DWITH_Eigen3=ON -DBOOST_ROOT=${BOOST_DIR} -G "Visual Studio 15 2017 Win64" .
  - cmake --build .

before_build:
  - cd C:\projects\CDT-plusplus
  - dir # Debugging

build_script:
  - mkdir build
  - cd build
  - cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DGMOCK_TESTS:BOOL=OFF ..

on_success:
  - cmake --build . --target test

notifications:

  - provider: Email
    to:
      - acgetchell@ucdavis.edu
    subject: 'Build {{status}}'
    message: "{{message}}, {{commitId}}, ..."
    on_build_status_changed: true

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))