skip_branch_with_pr: true

image:
  - Visual Studio 2015

build:
  verbosity: detailed

clone_folder: c:\projects\cdt-plusplus

shallow_clone: true

configuration: Release

install:
  - mkdir C:\projects\dev
  - cd C:\projects\dev

  # Install Ninja
  - set NINJA_URL="https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-win.zip"
  - appveyor DownloadFile %NINJA_URL% -FileName ninja.zip
  - 7z x ninja.zip -oC:\projects\dev\ninja > nul
  - set PATH=%PATH%;C:\projects\dev\ninja
  - ninja --version
  # Verify CMake
  - cmake --version
  # Setup Clang-cl
  - set PATH=%PATH%;"C:\Program Files\LLVM\bin"
  - clang-cl -v
  - set CC=clang-cl
  - set CXX=clang-cl
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
  # Use installed conda
  - set PATH=%PATH%;C:\Miniconda-x64\Scripts
  - conda update conda -y
  #- conda list
  - conda create --name py36 python=3.6 -y
  - activate py36
  # Install Eigen
  - conda install -c conda-forge eigen -y
  # Install TBB
  - conda install -c conda-forge tbb -y
  # Install Boost
  - conda install -c menpo boost-cpp -y
  # Install MPFR
  - conda install -c conda-forge mpfr -y
  # Install CGAL
  - conda install -c vincentrouvreau cgal_header_only -y
  # Install curl
  - conda install -c conda-forge curl
  # Install gtest
  - conda install -c conda-forge gtest -y

before_build:
  - cd C:\projects\CDT-plusplus

build_script:
  - mkdir build
  - cd build
  - cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DGMOCK_TESTS:BOOL=OFF ..
  - cmake --build .

on_success:
  - cmake --build . --target test

notifications:

  - provider: Email
    to:
      - acgetchell@ucdavis.edu
    subject: 'Build {{status}}'
    message: "{{message}}, {{commitId}}, ..."
    on_build_status_changed: true

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
