version: 0.1.8.{build}

skip_tags: true

skip_branch_with_pr: true

image:
  - Visual Studio 2019

clone_folder: c:\projects\cdt-plusplus

shallow_clone: true

clone_script:
  - cmd: >-
      git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
      && cd %APPVEYOR_BUILD_FOLDER%
      && git checkout -qf %APPVEYOR_REPO_COMMIT%
      && git submodule update --init --recursive

environment:
  #  APPVEYOR_SAVE_CACHE_ON_ERROR : true
  VCPKG_DEFAULT_TRIPLET: x64-windows
  VCPKG_ROOT: c:\tools\vcpkg

cache:
  - c:\Users\appveyor\AppData\Local\vcpkg\archives\
  - c:\tools\vcpkg

install:
  # Setup vcpkg
  - cd c:\tools\vcpkg
  - git pull origin master --no-rebase
  - git reset --hard c6f8dba
  - .\bootstrap-vcpkg.bat
  - set PATH=%PATH%;%VCPKG_ROOT%
  - vcpkg integrate install
  - if exist c:\tools\vcpkg\downloads\ rmdir /q /s c:\tools\vcpkg\downloads
  - if exist c:\tools\vcpkg\buildtrees\ rmdir /q /s c:\tools\vcpkg\buildtrees
  - if exist c:\tools\vcpkg\packages\ rmdir /q /s c:\tools\vcpkg\packages
  - cmake --version
  # Install required libraries in classic mode
  - set VCPKG_INSTALL_ROOT=%APPVEYOR_BUILD_FOLDER%\vcpkg_installed
  - vcpkg install --x-install-root=%VCPKG_INSTALL_ROOT% catch2 docopt date fmt ms-gsl eigen3 pcg tbb tl-expected
  # CGAL requires GMP which requires yasm-tool:x86-windows, even if you are using x64-windows.
  - vcpkg install --x-install-root=%VCPKG_INSTALL_ROOT% --recurse yasm-tool:x86-windows
  - vcpkg install --x-install-root=%VCPKG_INSTALL_ROOT% cgal
  # Upgrade required libraries
  - vcpkg upgrade --no-dry-run --x-install-root=%VCPKG_INSTALL_ROOT%
  - vcpkg list --x-install-root=%VCPKG_INSTALL_ROOT%
  # Setup Clang-cl
  - set PATH=%PATH%;"C:\Program Files\LLVM\bin"
  - clang-cl -v
  - set CC=clang-cl -mrtm
  - set CXX=clang-cl -mrtm
  # Visual Studio 2019
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
  - set CMAKE_CXX_COMPILER="C:\Program Files\LLVM\bin\clang-cl"

platform:
  - x64

configuration: Release

build:
  verbosity: detailed

before_build:
  - cd %APPVEYOR_BUILD_FOLDER%
#  - vcpkg install --feature-flags=manifests

build_script:
  - cmake -G Ninja -D CMAKE_BUILD_TYPE=Release -D ENABLE_CACHE=OFF -D VCPKG_MANIFEST_MODE=OFF -S . -B build
  - cmake --build build

#on_success:
#  - cd build
#  - ctest -VV

notifications:
  - provider: Email
    to:
      - acgetchell@ucdavis.edu
    on_build_status_changed: true

#on_failure:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
