version: 0.1.8.{build}

#branches:
#  only:
#    - master
#    - develop

platform:
    - x64

cache: c:\tools\vcpkg\installed\

image:
  - Visual Studio 2015
  - Visual Studio 2017

skip_branch_with_pr: true

build:
  verbosity: detailed

clone_folder: c:\projects\cdt-plusplus

shallow_clone: true

configuration: Release

install:
  - mkdir C:\projects\dev
  - cd C:\projects\dev

  # Install Ninja
  - set NINJA_URL="https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip"
  - appveyor DownloadFile %NINJA_URL% -FileName ninja.zip
  - 7z x ninja.zip -oC:\projects\dev\ninja > nul
  - set PATH=%PATH%;C:\projects\dev\ninja
  - ninja --version
  - set CMAKE_MAKE_PROGRAM=C:\projects\dev\ninja\ninja.exe
  # Verify CMake
  - cmake --version
  # Install make because TBB uses it and autoconf because libcurl uses it with msys2 64-bit on AppVeyor
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Syu"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S base-devel"
#  - choco install make
  - cd c:\tools\vcpkg
  # Update ports
  - git pull
  - # Update vcpkg
  - .\bootstrap-vcpkg.bat
  # Enable integration for Visual Studio/MSBuild
  - vcpkg integrate install
  # Use vcpkg to install required libraries
  - vcpkg install curl
  - vcpkg install date
  - vcpkg install docopt
  - vcpkg install gsl
  - vcpkg install catch2
  - vcpkg install eigen3
  - vcpkg install tbb
  - vcpkg install cgal
  # Setup Clang-cl
  - set PATH=%PATH%;"C:\Program Files\LLVM\bin"
  - clang-cl -v
  - set CC=clang-cl.exe -mrtm
  - set CXX=clang-cl.exe -mrtm
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
  - set CMAKE_CXX_COMPILER="C:\Program Files\LLVM\bin\clang-cl"
  # Upgrade pip
  - python -m pip install --upgrade pip
  # Install Conan
  - echo "Downloading conan..."
  - set PATH=%PATH%;%PYTHON%\Scripts\
  - pip.exe install conan

before_build:
  - cd C:\projects\CDT-plusplus
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan

build_script:
  - mkdir build
  - cd build
  - conan profile new cdt --detect
  - conan profile update env.CONAN_CMAKE_GENERATOR=Ninja cdt
  # TBB only seems to work on x64, uncommenting the line below causes TBB to fail
#  - conan profile update settings.arch=x86 default
  - conan profile show cdt
  - conan install .. -pr cdt --build=missing
  - cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DTESTS:BOOL=OFF -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake ..
  - cmake --build .
#  - conan build ..

on_success:
  - cmake --build . --target test
#  - conan install .. -pr default --build=missing
#  - conan build ..

#test_script:
#  - ctest -C release

notifications:

  - provider: Email
    to:
      - acgetchell@ucdavis.edu
    on_build_status_changed: true

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
