version: 0.1.8.{build}

skip_tags: true

skip_branch_with_pr: true

image:
  - Visual Studio 2022

clone_folder: c:\projects\cdt-plusplus

shallow_clone: true

clone_script:
  - cmd: >-
      git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
      && cd %APPVEYOR_BUILD_FOLDER%
      && git checkout -qf %APPVEYOR_REPO_COMMIT%
      && git submodule update --init --recursive

environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR : true
  VCPKG_DEFAULT_TRIPLET: x64-windows
  VCPKG_ROOT: c:\tools\vcpkg

#cache:
#  - c:\Users\appveyor\AppData\Local\vcpkg\archives\
#  - c:\tools\vcpkg\packages\

install:
  # Setup vcpkg
  - cd c:\tools\vcpkg
  - git pull
  - .\bootstrap-vcpkg.bat
  - set PATH=%PATH%;%VCPKG_ROOT%
  - vcpkg integrate install
  - cmake --version
  # Setup Clang-cl
  - set PATH=%PATH%;"C:\Program Files\LLVM\bin"
  - clang-cl -v
  - set CC=clang-cl -mrtm
  - set CXX=clang-cl -mrtm
  # Visual Studio 2022
  - call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"
  - set CMAKE_CXX_COMPILER="C:\Program Files\LLVM\bin\clang-cl"

platform:
  - x64

configuration: Release

build:
  verbosity: detailed

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - cmake --preset=appveyor
  - cmake --build build

#on_success:
#  - cd build
#  - ctest --output-on-failure -j2

notifications:
  - provider: Email
    to:
      - acgetchell@ucdavis.edu
    on_build_status_changed: true

#on_failure:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
