---
codecov:
  branch: main
  notify:
    require_ci_to_pass: false

coverage:
  precision: 2
  round: down
  range: "30...100"

  status:
    project:
      default:
        threshold: 3%
    patch: false
    changes: false

comment:
  layout: "reach, diff, flags, files, footer"
  behavior: default
  require_changes: false

ignore:
  - "tests/"
