image: acgetchell/vcpkg-image

tasks:
  - init: >
      mkdir vcpkg_installed
      && eval $(gp env -e _VCPKG_INSTALLED_DIR=/workspace/CDT-plusplus/vcpkg_installed)
      && vcpkg install --feature-flags=manifests
      && cd scripts
      && ./fast-build.sh
