path_classifiers:
  test:
    - tests
  docs:
    - docs
  library:
    - external
extraction:
  cpp:
    prepare:
      packages:
        - ninja-build
        - yasm
    configure:
      command:
        - git clone https://github.com/Microsoft/vcpkg.git
        - cd vcpkg
        - ./bootstrap-vcpkg.sh
        - ./vcpkg integrate install
        - ./vcpkg install catch2
        - ./vcpkg install docopt
        - ./vcpkg install ms-gsl
        - ./vcpkg install eigen3
        - ./vcpkg install boost
        - ./vcpkg install mpir
        - ./vcpkg install mpfr
        - ./vcpkg install tbb
        - ./vcpkg install cgal
    index:
      build_command:
        - cd $LGTM_SRC
        - mkdir build
        - cd build
        - cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=$LGTM_SRC/vcpkg/scripts/buildsystems/vcpkg.cmake ..
        - cmake --build .