path_classifiers:
  test:
    - tests
  docs:
    - docs
  library:
    - external
extraction:
  cpp:
    prepare:
      packages:
        - build-essential
        - automake
        - autoconf
        - autoconf-archive
        - libtool-bin
        - texinfo
        - yasm
        - ninja-build
#        - g++-10
        - ccache
#    after_prepare:
#      - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 --slave /usr/bin/g++ g++ /usr/bin/g++-10
#      - export CXX="g++-10" CC="gcc-10"
    configure:
      command:
        - git clone https://github.com/Microsoft/vcpkg.git
        - cd vcpkg
        - export VCPKG_ROOT="$LGTM_SRC/vcpkg"
        - export PATH="$VCPKG_ROOT:$PATH"
        - git pull origin master --no-rebase
        - ./bootstrap-vcpkg.sh
        - vcpkg integrate install
        - cmake --version
        - cd $LGTM_SRC
        - pwd
        - ps aux | grep vcpkg
        - vcpkg install --feature-flags=manifests
    index:
      build_command:
        - cd $LGTM_SRC
        - mkdir build
        - cd build || exit
        - cmake -G Ninja -D CMAKE_BUILD_TYPE=RelWithDebInfo -D ENABLE_TESTING:BOOL=TRUE ..
        - cmake --build .