path_classifiers:
  test:
    - tests
  docs:
    - docs
  library:
    - external
extraction:
  cpp:
    prepare:
      packages:
        - build-essential
        - automake
        - autoconf
        - autoconf-archive
        - libtool-bin
        - texinfo
        - yasm
        - ninja-build
        - g++-10
        - ccache
    after_prepare:
      - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 --slave /usr/bin/g++ g++ /usr/bin/g++-10
      - export CXX="g++-10" CC="gcc-10"
    configure:
      command:
        - git clone https://github.com/Microsoft/vcpkg.git
        - cd vcpkg
        - git reset --hard
        - git pull --no-rebase
        - git checkout 447b9cb
        - ./bootstrap-vcpkg.sh
        - ./vcpkg integrate install
        - ./vcpkg install catch2
        - ./vcpkg install docopt
        - ./vcpkg install date
        - ./vcpkg install fmt
        - ./vcpkg install ms-gsl
        - ./vcpkg install eigen3
        - ./vcpkg install pcg
        - ./vcpkg install tbb
        - ./vcpkg install cgal
#        - ./vcpkg upgrade --no-dry-run
        - ./vcpkg list
        - export VCPKG_ROOT="$LGTM_SRC/vcpkg"
    index:
      build_command:
        - cd $LGTM_SRC
        - mkdir build
        - cd build
        - cmake -G Ninja -D CMAKE_BUILD_TYPE=Debug -D VCPKG_MANIFEST_MODE=OFF ..
        - cmake --build .