CDT++: include/Ergodic_moves_3.hpp File Reference
Ergodic_moves_3.hpp File Reference
Pachner moves on 2+1 dimensional foliated Delaunay triangulations.
#include <expected>
#include "Formatters.hpp"
#include "Manifold.hpp"
#include "Move_tracker.hpp"
Typedefs
using ergodic_moves::Cell_container = std::vector< Cell_handle >
using ergodic_moves::Cell_handle = Cell_handle_t< 3 >
using ergodic_moves::Delaunay = Delaunay_t< 3 >
using ergodic_moves::Edge_container = std::vector< Edge_handle >
using ergodic_moves::Edge_handle = Edge_handle_t< 3 >
using ergodic_moves::Expected = std::expected< Manifold, std::string >
using ergodic_moves::Manifold = manifolds::Manifold_3
using ergodic_moves::Vertex_container = std::vector< Vertex_handle >
using ergodic_moves::Vertex_handle = Vertex_handle_t< 3 >
Functions
auto ergodic_moves::bistellar_flip (Delaunay const &source_triangulation, Edge_handle const source_edge, Vertex_handle const source_top, Vertex_handle const source_bottom) -> std::optional< Delaunay >
Perform a bistellar flip on triangulation via the given edge.
auto ergodic_moves::check_move (Manifold const &t_before, Manifold const &t_after, move_tracker::move_type const &t_move) -> bool
Check move correctness.
auto ergodic_moves::do_23_move (Manifold const &t_manifold) -> Expected
Perform a (2,3) move.
auto ergodic_moves::do_26_move (Manifold const &t_manifold) -> Expected
Perform a (2,6) move.
auto ergodic_moves::do_32_move (Manifold const &t_manifold) -> Expected
Perform a (3,2) move.
auto ergodic_moves::do_44_move (Manifold const &t_manifold) -> Expected
Perform a (4,4) move.
auto ergodic_moves::do_62_move (Manifold const &t_manifold) -> Expected
Perform a (6,2) move.
auto ergodic_moves::find_adjacent_31_cell (Cell_handle const &t_cell) -> std::optional< int >
Find a (2,6) move location.
auto ergodic_moves::find_bistellar_flip_location (Delaunay const &triangulation, Edge_handle const &t_edge_candidate) -> std::optional< Cell_container >
Find a bistellar flip location.
auto ergodic_moves::find_pivot_edge (Delaunay const &triangulation, Edge_container const &edges) -> std::optional< Edge_handle >
auto ergodic_moves::get_incident_cells (Delaunay const &triangulation, Edge_handle const edge) -> std::optional< Cell_container >
Return a container of cells incident to an edge.
auto ergodic_moves::get_vertices (Cell_container const &cells)
Return a container of all vertices in a container of cells.
auto ergodic_moves::incident_cells_from_edge (Delaunay_t< 3 > const &triangulation, Edge_handle const &edge) -> std::optional< Cell_container >
Find all cells incident to the edge.
auto ergodic_moves::is_62_movable (Delaunay const &triangulation, Vertex_handle const &candidate) -> bool
Find a (6,2) move location.
auto ergodic_moves::detail::is_well_formed_edge (Edge_handle const &edge) noexcept -> bool
Check an edge handle without dereferencing its cell handle.
auto ergodic_moves::detail::make_manifold (Delaunay triangulation, Manifold const &source) -> Manifold
Rebuild all derived topology and geometry state around a value.
auto ergodic_moves::null_move (Manifold const &t_manifold) -> Expected
Perform a null move.
auto ergodic_moves::try_23_move (Delaunay &triangulation, Cell_handle const &to_be_moved) -> bool
Perform a TriangulationDataStructure_3::flip on a facet.
auto ergodic_moves::try_32_move (Delaunay &triangulation, Edge_handle const &to_be_moved) -> bool
Perform a TriangulationDataStructure_3::flip on an edge.
auto ergodic_moves::try_62_move (Delaunay const &source_triangulation, Vertex_handle const source_candidate) -> std::optional< Delaunay >
Apply the combinatorial (6,2) retriangulation on a private copy.
Detailed Description
Pachner moves on 2+1 dimensional foliated Delaunay triangulations.
Author
Adam Getchell
Pachner moves operate on the level of the Manifold_3. The helper functions for the moves operate on the level of the Delaunay_Triangulation_3. C++23 support is required for std::expected.
Definition in file Ergodic_moves_3.hpp.
Typedef Documentation
Cell_container
using ergodic_moves::Cell_container = typedef std::vector<Cell_handle>
Definition at line 29 of file Ergodic_moves_3.hpp.
Cell_handle
using ergodic_moves::Cell_handle = typedef Cell_handle_t<3>
Definition at line 28 of file Ergodic_moves_3.hpp.
Delaunay
using ergodic_moves::Delaunay = typedef Delaunay_t<3>
Definition at line 34 of file Ergodic_moves_3.hpp.
Edge_container
using ergodic_moves::Edge_container = typedef std::vector<Edge_handle>
Definition at line 31 of file Ergodic_moves_3.hpp.
Edge_handle
using ergodic_moves::Edge_handle = typedef Edge_handle_t<3>
Definition at line 30 of file Ergodic_moves_3.hpp.
Expected
using ergodic_moves::Expected = typedef std::expected<Manifold, std::string>
Definition at line 27 of file Ergodic_moves_3.hpp.
Manifold
using ergodic_moves::Manifold = typedef manifolds::Manifold_3
Definition at line 26 of file Ergodic_moves_3.hpp.
Vertex_container
using ergodic_moves::Vertex_container = typedef std::vector<Vertex_handle>
Definition at line 33 of file Ergodic_moves_3.hpp.
Vertex_handle
using ergodic_moves::Vertex_handle = typedef Vertex_handle_t<3>
Definition at line 32 of file Ergodic_moves_3.hpp.
Function Documentation
bistellar_flip()
auto ergodic_moves::bistellar_flip (Delaunay const & source_triangulation, Edge_handle const source_edge, Vertex_handle const source_top, Vertex_handle const source_bottom) -> std::optional<Delaunay> inline
Perform a bistellar flip on triangulation via the given edge.
Pass by value to avoid modifying the original triangulation in the event that the flip is unsuccessful.
Parameters
source_triangulation The triangulation to flip
source_edge The edge to pivot on
source_top Top vertex of the cells being flipped
source_bottom Bottom vertex of the cells being flipped
Returns
A flipped triangulation or nullopt
Definition at line 654 of file Ergodic_moves_3.hpp.
References ergodic_moves::bistellar_flip(), and ergodic_moves::get_incident_cells().
Referenced by ergodic_moves::bistellar_flip(), and ergodic_moves::do_44_move().
check_move()
auto ergodic_moves::check_move (Manifold const & t_before, Manifold const & t_after, move_tracker::move_type const & t_move) -> bool inline
Check move correctness.
Parameters
t_before The manifold before the move
t_after The manifold after the move
t_move The type of move
Returns
True if the move correctly changed the triangulation
Definition at line 918 of file Ergodic_moves_3.hpp.
References ergodic_moves::check_move().
Referenced by ergodic_moves::check_move().
do_23_move()
auto ergodic_moves::do_23_move (Manifold const & t_manifold) -> Expected inline
Perform a (2,3) move.
A (2,3) move "flips" a timelike face into a timelike edge. This adds a (2,2) simplex and a timelike edge.
This function calls try_23_move on (2,2) simplices drawn from a randomly shuffled container until it succeeds or runs out of simplices.
If successful, the triangulation is no longer Delaunay.
Parameters
t_manifold The simplicial manifold
Returns
The Expected (2,3) moved manifold or an Unexpected
Definition at line 127 of file Ergodic_moves_3.hpp.
References ergodic_moves::do_23_move(), and ergodic_moves::try_23_move().
Referenced by ergodic_moves::do_23_move().
do_26_move()
auto ergodic_moves::do_26_move (Manifold const & t_manifold) -> Expected inline
Perform a (2,6) move.
A (2,6) move inserts a vertex into the spacelike face between a (1,3) simplex on the bottom connected to a (3,1) simplex on top. This adds 2 (1,3) simplices and 2 (3,1) simplices. It adds 2 spacelike faces and 6 timelike faces. It also adds 2 timelike edges and 3 spacelike edges, as well as the vertex. This function calls find_adjacent_31_cell on (1,3) simplices drawn from a randomly shuffled container until it succeeds or runs out of simplices. If successful, the triangulation is no longer Delaunay.
Parameters
t_manifold The simplicial manifold
Returns
The Expected (2,6) moved manifold or an Unexpected
Definition at line 234 of file Ergodic_moves_3.hpp.
References ergodic_moves::do_26_move(), and ergodic_moves::find_adjacent_31_cell().
Referenced by ergodic_moves::do_26_move().
do_32_move()
auto ergodic_moves::do_32_move (Manifold const & t_manifold) -> Expected inline
Perform a (3,2) move.
A (3,2) move "flips" a timelike edge into a timelike face. This removes a (2,2) simplex and the timelike edge. This function calls try_32_move on timelike edges drawn from a randomly shuffled container until it succeeds or runs out of edges. If successful, the triangulation is no longer Delaunay.
Parameters
t_manifold The simplicial manifold
Returns
The Expected (3,2) moved manifold or an Unexpected
Definition at line 173 of file Ergodic_moves_3.hpp.
References ergodic_moves::do_32_move(), and ergodic_moves::try_32_move().
Referenced by ergodic_moves::do_32_move().
do_44_move()
auto ergodic_moves::do_44_move (Manifold const & t_manifold) -> Expected inline
Perform a (4,4) move.
This is a bistellar flip pivoting the internal spacelike edge between the two spacelike faces. A (4,4) move flips an edge which has exactly 4 incident cells. In CDT specifically, the edge is spacelike and the 4 incident cells are a pair of (1,3) simplices and a pair of (3,1) simplices. It thus re-labels each of the 4 cells in the complex, but doesn't actually change the number of cells, vertices, or edges. This move has the effect of mixing up the simplices, thus possibly creating different potential moves in different locations.
This function calls is_44_movable() on a randomly shuffled container of edges until it succeeds or runs out of edges.
If successful, the triangulation remains combinatorially valid. A CDT move is not required to preserve the Euclidean Delaunay property of the coordinates used to represent the abstract triangulation.
Parameters
t_manifold The simplicial manifold
Returns
The Expected (4,4) moved manifold or Unexpected
Definition at line 837 of file Ergodic_moves_3.hpp.
References ergodic_moves::bistellar_flip(), ergodic_moves::do_44_move(), and ergodic_moves::find_bistellar_flip_location().
Referenced by ergodic_moves::do_44_move().
do_62_move()
auto ergodic_moves::do_62_move (Manifold const & t_manifold) -> Expected inline
Perform a (6,2) move.
This function performs a (6,2) move on the given manifold. A (6,2) move removes a vertex which has 3 incident (3,1) simplices and 3 (1,3) simplices for a total of 6 incident simplices exactly. This converts the 3 (1,3) simplices into a single (1,3) simplex on the bottom and the 3 (3,1) simplices into a single (3,1) simplex on top. It thus removes 2 (1,3) simplices, 2 (3,1) simplices, 2 spacelike faces, 6 timelike faces, 3 spacelike edges, 2 timelike edges, and a single vertex.
This function calls is_62_movable() on a randomly shuffled container of vertices until it succeeds or runs out of vertices.
If successful, the triangulation remains Delaunay. (Other moves may change this, however.)
Parameters
t_manifold The simplicial manifold
Returns
The Expected (6,2) moved manifold or Unexpected
Definition at line 547 of file Ergodic_moves_3.hpp.
References ergodic_moves::do_62_move(), ergodic_moves::is_62_movable(), and ergodic_moves::try_62_move().
Referenced by ergodic_moves::do_62_move().
find_adjacent_31_cell()
auto ergodic_moves::find_adjacent_31_cell (Cell_handle const & t_cell) -> std::optional<int> inline
Find a (2,6) move location.
This function checks to see if a (2,6) move is possible. Starting with a (1,3) simplex, it checks neighbors for a (3,1) simplex.
Parameters
t_cell The (1,3) simplex that is checked
Returns
The integer of the neighboring (3,1) simplex or nullopt
Definition at line 201 of file Ergodic_moves_3.hpp.
References ergodic_moves::find_adjacent_31_cell().
Referenced by ergodic_moves::do_26_move(), and ergodic_moves::find_adjacent_31_cell().
find_bistellar_flip_location()
auto ergodic_moves::find_bistellar_flip_location (Delaunay const & triangulation, Edge_handle const & t_edge_candidate) -> std::optional<Cell_container> inline
Find a bistellar flip location.
This function checks to see if a bistellar flip is possible. Starting with an edge, it checks all incident cells. There must be 4 incident cells; 2 should be (3,1) simplices, 2 should be (1,3) simplices, and there should be no (2,2) simplices.
Parameters
triangulation The simplicial manifold
t_edge_candidate The edge to check
Returns
A container of incident cells if there are exactly 4 or nullopt
Definition at line 613 of file Ergodic_moves_3.hpp.
References ergodic_moves::find_bistellar_flip_location(), and ergodic_moves::incident_cells_from_edge().
Referenced by ergodic_moves::do_44_move(), and ergodic_moves::find_bistellar_flip_location().
find_pivot_edge()
auto ergodic_moves::find_pivot_edge (Delaunay const & triangulation, Edge_container const & edges) -> std::optional<Edge_handle> inline
Returns
The center edge of a 4-cell complex
Definition at line 785 of file Ergodic_moves_3.hpp.
References ergodic_moves::find_pivot_edge(), and ergodic_moves::incident_cells_from_edge().
Referenced by ergodic_moves::find_pivot_edge().
get_incident_cells()
auto ergodic_moves::get_incident_cells (Delaunay const & triangulation, Edge_handle const edge) -> std::optional<Cell_container> inline
Return a container of cells incident to an edge.
Parameters
triangulation The triangulation with the cells.
edge The edge to find the incident cells of.
Returns
A container of cells incident to the edge or nullopt
Definition at line 639 of file Ergodic_moves_3.hpp.
References ergodic_moves::get_incident_cells(), and ergodic_moves::incident_cells_from_edge().
Referenced by ergodic_moves::bistellar_flip(), and ergodic_moves::get_incident_cells().
get_vertices()
auto ergodic_moves::get_vertices (Cell_container const & cells) inline
Return a container of all vertices in a container of cells.
Parameters
cells The cells to find the vertices of.
Returns
A container of vertices in the cells
Definition at line 806 of file Ergodic_moves_3.hpp.
References ergodic_moves::get_vertices().
Referenced by ergodic_moves::get_vertices().
incident_cells_from_edge()
auto ergodic_moves::incident_cells_from_edge (Delaunay_t< 3 > const & triangulation, Edge_handle const & edge) -> std::optional<Cell_container> inline
Find all cells incident to the edge.
Parameters
triangulation The Delaunay triangulation
edge The edge
Returns
A container of cells incident to the edge or nullopt
See also
https://github.com/CGAL/cgal/blob/8430d04539179f25fb8e716f99e19d28589beeda/TDS_3/include/CGAL/Triangulation_data_structure_3.h#L2094
Definition at line 577 of file Ergodic_moves_3.hpp.
References ergodic_moves::incident_cells_from_edge().
Referenced by ergodic_moves::find_bistellar_flip_location(), ergodic_moves::find_pivot_edge(), ergodic_moves::get_incident_cells(), and ergodic_moves::incident_cells_from_edge().
is_62_movable()
auto ergodic_moves::is_62_movable (Delaunay const & triangulation, Vertex_handle const & candidate) -> bool inline
Find a (6,2) move location.
This function checks to see if a (6,2) move is possible. Starting with a vertex, it checks all incident cells. There must be 6 incident cells; 3 should be (3,1) simplices, 3 should be (1,3) simplices, and there should be no (2,2) simplices.
Parameters
triangulation The triangulation containing the candidate
candidate The vertex to check
Returns
True if (6,2) move is possible
Definition at line 378 of file Ergodic_moves_3.hpp.
References ergodic_moves::is_62_movable().
Referenced by ergodic_moves::do_62_move(), and ergodic_moves::is_62_movable().
is_well_formed_edge()
auto ergodic_moves::detail::is_well_formed_edge (Edge_handle const & edge) -> bool inline noexcept
Check an edge handle without dereferencing its cell handle.
A tetrahedral cell has four local vertex indices in [0, 4).
Definition at line 51 of file Ergodic_moves_3.hpp.
References ergodic_moves::detail::is_well_formed_edge().
Referenced by ergodic_moves::detail::is_well_formed_edge().
make_manifold()
auto ergodic_moves::detail::make_manifold (Delaunay triangulation, Manifold const & source) -> Manifold inline
Rebuild all derived topology and geometry state around a value.
Definition at line 39 of file Ergodic_moves_3.hpp.
References ergodic_moves::detail::make_manifold().
Referenced by ergodic_moves::detail::make_manifold().
null_move()
auto ergodic_moves::null_move (Manifold const & t_manifold) -> Expected inline
Perform a null move.
Parameters
t_manifold The simplicial manifold
Returns
The null-moved manifold
Definition at line 68 of file Ergodic_moves_3.hpp.
References ergodic_moves::null_move().
Referenced by ergodic_moves::null_move().
try_23_move()
auto ergodic_moves::try_23_move (Delaunay & triangulation, Cell_handle const & to_be_moved) -> bool inline
Perform a TriangulationDataStructure_3::flip on a facet.
Parameters
t_manifold The manifold containing the cell to flip
to_be_moved The cell on which to try the move
Returns
True if move succeeded
See also
https://doc.cgal.org/latest/TDS_3/classTriangulationDataStructure__3.html#a2ad2941984c1eac5561665700bfd60b4
Definition at line 77 of file Ergodic_moves_3.hpp.
References ergodic_moves::try_23_move().
Referenced by ergodic_moves::do_23_move(), and ergodic_moves::try_23_move().
try_32_move()
auto ergodic_moves::try_32_move (Delaunay & triangulation, Edge_handle const & to_be_moved) -> bool inline
Perform a TriangulationDataStructure_3::flip on an edge.
Parameters
t_manifold The manifold containing the edge to flip
to_be_moved The edge on which to try the move
Returns
True if move succeeded
See also
https://doc.cgal.org/latest/TDS_3/classTriangulationDataStructure__3.html#a5837d666e4198f707f862003c1ffa033
Definition at line 158 of file Ergodic_moves_3.hpp.
References ergodic_moves::try_32_move().
Referenced by ergodic_moves::do_32_move(), and ergodic_moves::try_32_move().
try_62_move()
auto ergodic_moves::try_62_move (Delaunay const & source_triangulation, Vertex_handle const source_candidate) -> std::optional<Delaunay> inline
Apply the combinatorial (6,2) retriangulation on a private copy.
A (3,2) flip of either timelike edge incident to the removable vertex leaves that vertex with degree four. Removing it from its maximal simplex then replaces the original six cells with the required two cells. Keeping both operations in a private copy makes rejection failure-atomic.
Parameters
source_triangulation The triangulation containing the candidate
source_candidate The degree-five vertex to remove
Returns
The moved triangulation, or nullopt when the topology is not flippable or the result violates a triangulation or causal-cell invariant
Definition at line 469 of file Ergodic_moves_3.hpp.
References ergodic_moves::try_62_move().
Referenced by ergodic_moves::do_62_move(), and ergodic_moves::try_62_move().