CDT++: include/Geometry.hpp File Reference
Geometry.hpp File Reference
Data structures for geometry.
#include "Foliated_triangulation.hpp"
Classes
struct Geometry< dimension >
struct Geometry< 3 >
3D Geometry
Typedefs
using Geometry3 = Geometry< 3 >
Functions
template<>
struct Geometry< 3 > __attribute__ ((aligned(MEMORY_ALIGNMENT)))
Geometry ()=default
Default ctor.
Geometry (FoliatedTriangulations::FoliatedTriangulation3 const &triangulation)
Constructor with triangulation.
void swap (Geometry< 3 > &t_first, Geometry< 3 > &t_second) noexcept
Swap two Geometry3 structs Used for no-except updates of geometry data structures Usually called from a Manifold swap.
Variables
Int_precision N0 {0}
Number of vertices.
Int_precision N1 {0}
Number of 1D edges.
Int_precision N1_SL {0}
Number of spacelike edges.
Int_precision N1_TL {0}
Number of timelike edges.
Int_precision N2 {0}
Number of 2D faces.
Int_precision N3 {0}
Number of 3D simplices.
Int_precision N3_13 {0}
Number of (1,3) simplices.
Int_precision N3_22 {0}
Number of (2,2) simplices.
Int_precision N3_31 {0}
Number of (3,1) simplices.
Int_precision N3_31_13 {0}
Number of (3,1) + (1,3) simplices.
Detailed Description
Data structures for geometry.
Causal Dynamical Triangulations in C++ using CGAL
Copyright © 2018-2021 Adam Getchell
Geometric quantities of Manifold used by MoveAlgorithm.
Author
Adam Getchell
Definition in file Geometry.hpp.
Function Documentation
Geometry()
__attribute__::Geometry (FoliatedTriangulations::FoliatedTriangulation3 const & triangulation) explicit
Constructor with triangulation.
Parameters
triangulation Triangulation for which Geometry is being calculated
Definition at line 383 of file Geometry.hpp.
swap()
friend void __attribute__::swap (Geometry< 3 > & t_first, Geometry< 3 > & t_second) noexcept
Swap two Geometry3 structs Used for no-except updates of geometry data structures Usually called from a Manifold swap.
Parameters
t_first The destination geometry struct to swap out
t_second The source geometry struct to swap in
Definition at line 404 of file Geometry.hpp.
Referenced by MoveCommand< ManifoldType, FunctionType >::execute(), FoliatedTriangulations::FoliatedTriangulation< 3 >::FoliatedTriangulation(), MoveCommand< ManifoldType, FunctionType >::move(), MoveStrategy< MOVE_ALWAYS, dimension >::operator=(), FoliatedTriangulations::FoliatedTriangulation< 3 >::operator=(), SimplicialManifold::operator=(), and Manifolds::Manifold< 3 >::update_geometry().