CDT++: tests/Manifold_test.cpp File Reference
Manifold_test.cpp File Reference
Tests of new manifold data structure.
#include "Manifold.hpp"
#include <doctest/doctest.h>
#include <numbers>
Typedefs
using Point = Point_t< 3 >
Functions
GIVEN ("4 points.")
GIVEN ("A (1,3) and (3,1) stacked on each other.")
GIVEN ("A 3-manifold with four vertices.")
GIVEN ("A 3-manifold")
GIVEN ("A 3-manifold.")
GIVEN ("A default constructed Manifold_3")
GIVEN ("A medium sized manifold.")
GIVEN ("A mismatched set of points and timevalues.")
GIVEN ("A pair of 3-manifolds.")
GIVEN ("A vector of points and timevalues.")
GIVEN ("The default manifold from the default triangulation")
SCENARIO ("Manifold special member and swap properties" *doctest::test_suite("manifold"))
Variables
static auto constexpr RADIUS_2 = 2.0 * std::numbers::inv_sqrt3_v<double>
Detailed Description
Tests of new manifold data structure.
Author
Adam Getchell
Definition in file Manifold_test.cpp.
Typedef Documentation
Point
using Point = Point_t<3>
Initial value:
{
  spdlog::debug("Manifold initialization.\n")
Definition at line 270 of file Manifold_test.cpp.
Function Documentation
GIVEN() [1/11]
GIVEN ("4 points.")
Todo:
Why is this false?
Todo:
Why is this false?
Definition at line 159 of file Manifold_test.cpp.
References manifolds::Manifold< 3 >::get_cell(), manifolds::Manifold< 3 >::get_delaunay(), manifolds::Manifold< 3 >::get_vertex(), manifolds::Manifold< 3 >::is_correct(), manifolds::Manifold< 3 >::print(), manifolds::Manifold< 3 >::print_details(), and manifolds::Manifold< 3 >::print_vertices().
GIVEN() [2/11]
GIVEN ("A (1,3) and (3,1) stacked on each other.")
Definition at line 657 of file Manifold_test.cpp.
GIVEN() [3/11]
GIVEN ("A 3-manifold with four vertices.")
Definition at line 230 of file Manifold_test.cpp.
GIVEN() [4/11]
GIVEN ("A 3-manifold")
Definition at line 481 of file Manifold_test.cpp.
GIVEN() [5/11]
GIVEN ("A 3-manifold.")
Initial value:
{
  spdlog::debug("3-Manifold copying.\n")
Definition at line 271 of file Manifold_test.cpp.
GIVEN() [6/11]
GIVEN ("A default constructed Manifold_3")
Definition at line 214 of file Manifold_test.cpp.
GIVEN() [7/11]
GIVEN ("A medium sized manifold.")
Definition at line 717 of file Manifold_test.cpp.
GIVEN() [8/11]
GIVEN ("A mismatched set of points and timevalues.")
Definition at line 144 of file Manifold_test.cpp.
GIVEN() [9/11]
GIVEN ("A pair of 3-manifolds.")
Definition at line 596 of file Manifold_test.cpp.
GIVEN() [10/11]
GIVEN ("A vector of points and timevalues.")
Definition at line 119 of file Manifold_test.cpp.
GIVEN() [11/11]
GIVEN ("The default manifold from the default triangulation")
Definition at line 466 of file Manifold_test.cpp.
SCENARIO()
SCENARIO ("Manifold special member and swap properties" * doctest::test_suite"manifold")
Definition at line 22 of file Manifold_test.cpp.
Variable Documentation
RADIUS_2
auto constexpr RADIUS_2 = 2.0 * std::numbers::inv_sqrt3_v<double> inline static constexpr
Definition at line 20 of file Manifold_test.cpp.