CDT++: include/S3Triangulation.hpp File Reference
S3Triangulation.hpp File Reference
Functions on 3D Spherical Delaunay Triangulations.
#include <CGAL/Delaunay_triangulation_3.h>
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/Triangulation_cell_base_with_info_3.h>
#include <CGAL/Triangulation_vertex_base_with_info_3.h>
#include <CGAL/point_generators_3.h>
#include <Utilities.hpp>
#include <algorithm>
#include <memory>
#include <set>
#include <stdexcept>
#include <tuple>
#include <utility>
#include <vector>
Macros
#define DETAILED_DEBUGGING
Toggles detailed per-simplex debugging output.
Typedefs
using Causal_vertices = std::vector< std::pair< Point, int > >
using Cb = CGAL::Triangulation_cell_base_with_info_3< int, K >
using Cell_handle = Delaunay3::Cell_handle
using Delaunay3 = CGAL::Delaunay_triangulation_3< K, Tds >
using Edge_handle = std::tuple< Cell_handle, int, int >
using K = CGAL::Exact_predicates_inexact_constructions_kernel
using Locate_type = Delaunay3::Locate_type
using Move_tracker = std::array< int, 5 >
using Point = Delaunay3::Point
using Tds = CGAL::Triangulation_data_structure_3< Vb, Cb >
using Triangulation = CGAL::Triangulation_3< K >
using Vb = CGAL::Triangulation_vertex_base_with_info_3< int, K >
using Vertex_handle = Delaunay3::Vertex_handle
Enumerations
enum move_type {
TWO_THREE = 0, THREE_TWO = 1, TWO_SIX = 2, SIX_TWO = 3,
FOUR_FOUR = 4
}
Functions
template<typename Manifold >
auto fix_timeslices (Manifold &&universe_ptr)
Fix simplices with incorrect foliation.
template<typename Manifold >
void fix_triangulation (Manifold &&universe_ptr)
Fixes the foliation of the triangulation.
template<typename Manifold >
void insert_into_triangulation (Manifold &&universe_ptr, Causal_vertices cv)
Inserts vertices with timeslices into Delaunay triangulation.
auto make_foliated_sphere (const std::int_fast64_t simplices, const std::int_fast64_t timeslices, double initial_radius=INITIAL_RADIUS, double radial_factor=RADIAL_FACTOR)
Make foliated spheres.
auto make_triangulation (const std::int_fast64_t simplices, const std::int_fast64_t timeslices, double initial_radius=INITIAL_RADIUS, double radial_factor=RADIAL_FACTOR)
Make a triangulation from foliated 2-spheres.
Variables
static constexpr std::int_fast64_t DIMENSION = 3
The dimensionality of the Delaunay triangulation.
static constexpr double INITIAL_RADIUS = 1.0
Initial radius and radial factor.
static constexpr std::int_fast64_t MAX_FOLIATION_FIX_PASSES = 500
The maximum number of passes to fix invalidly foliated simplices.
static constexpr double RADIAL_FACTOR = 1.0
Detailed Description
Functions on 3D Spherical Delaunay Triangulations.
Causal Dynamical Triangulations in C++ using CGAL
Copyright © 2015-2018 Adam Getchell
Creates foliated spherical triangulations
The number of desired timeslices is given, and successive spheres are created with increasing radii. Each vertex at a given radius is assigned a timeslice so that the entire triangulation will have a preferred foliation of time.
\done Insert a 3-sphere into the triangulation data structure. \done Assign each 3-sphere a unique timeslice. \done Iterate over the number of desired timeslices. \done Check/fix issues for large values of simplices and timeslices. \done Iterate over cells and check timeslices of vertices don't differ by more than 1. \done Gather ratio of cells with bad/good foliation. Adjust value of radius to minimize. Recheck the whole triangulation when finished. \done When a cell contains a bad foliation, delete it. Recheck. \done Fixup Delaunay triangulation after bad cells have been deleted. \done Re-written with std::unique_ptr<T> and . Efficient Pure Functional Programming in C++ Using Move Semantics \done Const Correctness. \done Function documentation. \done Multi-threaded operations using Intel TBB. \done Debugging output toggled by macros.
Author
Adam Getchell
Todo:
Deprecated in favor of Foliated_triangulation.hpp
Definition in file S3Triangulation.hpp.
Function Documentation
fix_timeslices()
template<typename Manifold > auto fix_timeslices (Manifold && universe_ptr)
Fix simplices with incorrect foliation.
This function iterates over all of the cells in the triangulation. Within each cell, it iterates over all of the vertices and reads timeslices. Validity of the cell is first checked by the is_valid() function. The foliation validity is then checked by finding maximum and minimum timeslices for all the vertices of a cell and ensuring that the difference is exactly 1. If a cell has a bad foliation, the vertex with the highest timeslice is deleted. The Delaunay triangulation is then recomputed on the remaining vertices. This function is repeatedly called by fix_triangulation() up to MAX_FOLIATION_FIX_PASSES times.
Parameters
universe_ptr A std::unique_ptr<Delaunay> to the triangulation
Returns
A boolean value if there are invalid simplices
Definition at line 116 of file S3Triangulation.hpp.
Referenced by fix_triangulation().
fix_triangulation()
template<typename Manifold > void fix_triangulation (Manifold && universe_ptr)
Fixes the foliation of the triangulation.
Runs fix_timeslices() to fix foliation until there are no errors, or MAX_FOLIATION_FIX_PASSES whichever comes first.
Parameters
universe_ptr A std::unique_ptr<Delaunay> to the triangulation
Definition at line 211 of file S3Triangulation.hpp.
References fix_timeslices(), and MAX_FOLIATION_FIX_PASSES.
insert_into_triangulation()
template<typename Manifold > void insert_into_triangulation (Manifold && universe_ptr, Causal_vertices cv)
Inserts vertices with timeslices into Delaunay triangulation.
Template Parameters
Manifold Type of universe_ptr
Parameters
universe_ptr A unique pointer to triangulation
cv A data structure of causal vertices
Definition at line 230 of file S3Triangulation.hpp.
make_foliated_sphere()
auto make_foliated_sphere (const std::int_fast64_t simplices, const std::int_fast64_t timeslices, double initial_radius = INITIAL_RADIUS, double radial_factor = RADIAL_FACTOR) inline
Make foliated spheres.
The radius is used to denote the time value, so we can nest 2-spheres such that our time foliation contains leaves of identical topology.
Parameters
simplices The number of desired simplices in the triangulation
timeslices The number of desired timeslices in the triangulation
Returns
A std::vector<std::pair<Point, int>> containing random vertices and their corresponding timevalues
Definition at line 245 of file S3Triangulation.hpp.
make_triangulation()
auto make_triangulation (const std::int_fast64_t simplices, const std::int_fast64_t timeslices, double initial_radius = INITIAL_RADIUS, double radial_factor = RADIAL_FACTOR) inline
Make a triangulation from foliated 2-spheres.
This function creates a triangulation from successive spheres. First, the number of points per leaf in the foliation is estimated given the desired number of simplices. Next, make_foliated_sphere() is called to generate nested spheres. The radius of the sphere is assigned as the time value for each vertex in that sphere, which comprises a leaf in the foliation. All vertices in all spheres (along with their time values) are then inserted with insert_into_triangulation() into a Delaunay triangulation (see http://en.wikipedia.org/wiki/Delaunay_triangulation for details). Finally, fix_triangulation() removes cells in the Delaunay triangulation with invalid foliations using fix_timeslices(). A last check is performed to ensure a valid Delaunay triangulation.
Parameters
[in] simplices The number of desired simplices in the triangulation
[in] timeslices The number of timeslices in the triangulation
Returns
A std::unique_ptr<Delaunay> to the foliated triangulation
Definition at line 288 of file S3Triangulation.hpp.
Referenced by SimplicialManifold::SimplicialManifold().