CDT++: tests/Utilities_test.cpp File Reference
Utilities_test.cpp File Reference
Tests on utility functions.
#include <Manifold.hpp>
#include <catch2/catch.hpp>
Functions
SCENARIO ("Various string/stream/time utilities", "[utility][!mayfail]")
SCENARIO ("Randomizing functions", "[utility][!mayfail]")
SCENARIO ("Expected points per timeslice", "[utility]")
Detailed Description
Tests on utility functions.
Causal Dynamical Triangulations in C++ using CGAL
Copyright © 2017-2021 Adam Getchell
Tests for random, conversion, and datetime functions.
Author
Adam Getchell
Definition in file Utilities_test.cpp.
Function Documentation
SCENARIO()
SCENARIO ("Randomizing functions" , "" [utility][!mayfail])
Todo:
fmt rdbuf replacement
Definition at line 132 of file Utilities_test.cpp.
References die_roll(), expected_points_per_timeslice(), generate_probability(), generate_random_int(), generate_random_real(), generate_random_timeslice(), Gmpzf_to_double(), and make_random_generator().