CDT++: src/cdt-opt.cpp File Reference
cdt-opt.cpp File Reference
Outputs values to determine optimizations.
#include <Metropolis.hpp>
#include <Simulation.hpp>
Functions
int main ()
Detailed Description
Outputs values to determine optimizations.
Causal Dynamical Triangulations in C++ using CGAL
Copyright © 2016-2021 Adam Getchell
Full run-through with default options used to calculate optimal values for thermalization, etc. A simpler version that encompasses the entire lifecycle. Also suitable for scripting parallel runs, e.g.
./cdt-opt 2>>errors 1>>output &
Invoke Metropolis algorithm
Todo:
Print out graph of time-value vs. volume vs. pass number
Author
Adam Getchell
Definition in file cdt-opt.cpp.
Function Documentation
main()
int main ()
Constants in units of \(c=G=\hbar=1 \alpha\approx 0.0397887\)
\(\Lambda=2.036\times 10^{-35} s^{-2}\approx 0\)
Definition at line 26 of file cdt-opt.cpp.
References currentDateTime(), SimplicialManifold::geometry, Simulation< element >::queue(), and Simulation< element >::start().