CDT++: src/cdt.cpp File Reference
cdt.cpp File Reference
The main executable.
#include <CGAL/Real_timer.h>
#include <boost/program_options.hpp>
#include <cstdint>
#include <Metropolis.hpp>
#include <utility>
#include "Runtime_config.hpp"
#include "Version.hpp"
Typedefs
using Timer = CGAL::Real_timer
Functions
catch (...)
catch (domain_error const &DomainError)
catch (invalid_argument const &InvalidArgument)
catch (logic_error const &LogicError)
catch (runtime_error const &RuntimeError)
auto main (int const argc, char *const argv[]) -> int try
The main path of the CDT++ program.
Variables
static string_view constexpr USAGE
Help text used by Boost.Program_options.
Detailed Description
The main executable.
Author
Adam Getchell
A program that generates spacetime ensembles. Inspired by https://github.com/ucdavis/CDT.
Definition in file cdt.cpp.
Typedef Documentation
Timer
using Timer = CGAL::Real_timer
Definition at line 23 of file cdt.cpp.
Function Documentation
catch() [1/5]
catch (...)
Definition at line 257 of file cdt.cpp.
catch() [2/5]
catch (domain_error const & DomainError)
Definition at line 234 of file cdt.cpp.
catch() [3/5]
catch (invalid_argument const & InvalidArgument)
Definition at line 240 of file cdt.cpp.
catch() [4/5]
catch (logic_error const & LogicError)
Definition at line 246 of file cdt.cpp.
catch() [5/5]
catch (runtime_error const & RuntimeError)
Definition at line 252 of file cdt.cpp.
main()
auto main (int const argc, char *const argv[]) -> int try
The main path of the CDT++ program.
Parameters
argc Argument count = 1 + number of arguments
argv Argument vector passed to Boost.Program_options
Returns
Integer value 0 if successful, 1 on failure
Definition at line 65 of file cdt.cpp.
References cdt::manifolds::Manifold< 3 >::print(), cdt::manifolds::Manifold< 3 >::print_details(), and cdt::manifolds::Manifold< 3 >::print_volume_per_timeslice().
Variable Documentation
USAGE
string_view constexpr USAGE static constexpr
Initial value:
{
    R"(Causal Dynamical Triangulations in C++ using CGAL.
Copyright (c) 2013-2026 Adam Getchell
A program that generates d-dimensional triangulated spacetimes
with a defined causal structure and evolves them according
to the Metropolis algorithm. Specify the number of passes to control
how much evolution is desired. Each pass attempts a number of ergodic
moves equal to the number of simplices in the simulation.
Usage:./cdt (--spherical | --toroidal) -n SIMPLICES -t TIMESLICES
            [-d DIM]
            [--init INITIAL RADIUS]
            [--foliate FOLIATION SPACING]
            [--no-output]
            [--seed SEED]
            -k K
            --alpha ALPHA
            --lambda LAMBDA
            [-p PASSES]
            [-c CHECKPOINT]
Optional arguments are in square brackets.
Examples:
./cdt --spherical -n 32000 -t 11 --alpha 0.6 -k 1.1 --lambda 0.1 --passes 1000
./cdt -s -n32000 -t11 -a.6 -k1.1 -l.1 -p1000 --seed 92
Options)"}
Help text used by Boost.Program_options.
Definition at line 30 of file cdt.cpp.