CDT++: cdt::MoveRunCadence Class Reference
cdt::MoveRunCadence Class Reference
Positive pass count and checkpoint interval for a move run.
#include <Move_run.hpp>
Classes
struct Parsed
Public Member Functions
MoveRunCadence ()=default
Construct the valid single-pass default cadence.
auto constexpr checkpoint () const noexcept
auto constexpr passes () const noexcept
Static Public Member Functions
static auto parse (Int_precision const passes, Int_precision const checkpoint) noexcept -> std::expected< MoveRunCadence, MoveRunCadenceError >
Parse raw counts into a cadence that proves positivity.
Private Member Functions
MoveRunCadence (Int_precision const passes, Int_precision const checkpoint, Parsed) noexcept
Private Attributes
Int_precision m_checkpoint {1}
Int_precision m_passes {1}
Detailed Description
Positive pass count and checkpoint interval for a move run.
Once parsed, the orchestration core can use both values without repeating positivity checks.
Definition at line 36 of file Move_run.hpp.
Constructor & Destructor Documentation
MoveRunCadence()
cdt::MoveRunCadence::MoveRunCadence (Int_precision const passes, Int_precision const checkpoint, Parsed) inline private noexcept
Definition at line 44 of file Move_run.hpp.
Member Function Documentation
checkpoint()
auto constexpr cdt::MoveRunCadence::checkpoint () const inline nodiscard constexpr noexcept
Returns
The positive number of passes between checkpoint events.
Definition at line 80 of file Move_run.hpp.
Referenced by parse().
parse()
auto cdt::MoveRunCadence::parse (Int_precision const passes, Int_precision const checkpoint) -> std::expected< MoveRunCadence, MoveRunCadenceError > inline static nodiscard noexcept
Parse raw counts into a cadence that proves positivity.
Parameters
passes Number of passes; must be greater than zero.
checkpoint Number of passes between checkpoint events; must be greater than zero.
Returns
A cadence on success, or MoveRunCadenceError::NONPOSITIVE_PASSES when passes is nonpositive, otherwise MoveRunCadenceError::NONPOSITIVE_CHECKPOINT when checkpoint is nonpositive. The passes error takes precedence when both are invalid.
Definition at line 61 of file Move_run.hpp.
References checkpoint(), and passes().
Referenced by cdt::detail::parse_move_run_cadence().
passes()
auto constexpr cdt::MoveRunCadence::passes () const inline nodiscard constexpr noexcept
Returns
The positive number of passes in a run.
Definition at line 77 of file Move_run.hpp.
Referenced by parse().
Member Data Documentation
m_checkpoint
Int_precision cdt::MoveRunCadence::m_checkpoint {1} private
Definition at line 42 of file Move_run.hpp.
m_passes
Int_precision cdt::MoveRunCadence::m_passes {1} private
Definition at line 41 of file Move_run.hpp.
The documentation for this class was generated from the following file:
include/Move_run.hpp