CDT++: cdt::manifolds::Manifold< 3 > Class Reference
cdt::manifolds::Manifold< 3 > Class Reference
3D Manifold
#include <Manifold.hpp>
Public Member Functions
Manifold ()=default
Default ctor.
Manifold (Causal_vertices_t< 3 > const &causal_vertices, double const t_initial_radius=INITIAL_RADIUS, double const t_foliation_spacing=FOLIATION_SPACING)
Construct manifold from Causal_vertices Pass-by-value-then-move.
Manifold (Int_precision const t_desired_simplices, Int_precision const t_desired_timeslices, cdt::Random &&generator, double const t_initial_radius=INITIAL_RADIUS, double const t_foliation_spacing=FOLIATION_SPACING)
Construct from an explicit temporary initialization stream.
Manifold (Int_precision const t_desired_simplices, Int_precision const t_desired_timeslices, cdt::Random &generator, double const t_initial_radius=INITIAL_RADIUS, double const t_foliation_spacing=FOLIATION_SPACING)
Construct a manifold with a caller-owned initialization stream.
Manifold (Manifold &&other) noexcept=default
Default move ctor.
Manifold (Manifold const &other)=default
Default copy ctor.
Manifold (Triangulation t_foliated_triangulation)
Construct manifold from a Foliated triangulation.
~Manifold ()=default
Default dtor.
auto check_simplices () const -> bool
auto check_vertices () const -> bool
auto delaunay_snapshot () const -> Delaunay_t< 3 >
auto dimensionality () const
auto edges () const
auto faces () const
auto foliation_spacing () const
Radial separation between timeslices.
auto get_geometry () const -> Geometry const &
auto initial_radius () const
Initial radius of the first timeslice.
auto is_correct () const -> bool
auto is_delaunay () const -> bool
Forwarding to FoliatedTriangulation.is_delaunay().
auto is_foliated () const -> bool
Forwarding to FoliatedTriangulation_3.is_foliated().
auto is_valid () const -> bool
Forwarding to FoliatedTriangulation.is_tds_valid().
auto max_time () const
auto min_time () const
auto N0 () const
auto N1 () const
auto N1_SL () const
auto N1_TL () const
auto N2 () const
auto N3 () const
auto N3_13 () const
auto N3_22 () const
auto N3_31 () const
auto N3_31_13 () const
auto operator= (Manifold &&other) noexcept -> Manifold &
Default move assignment.
auto operator= (Manifold const &other) -> Manifold &=default
Default copy assignment.
void print () const
Print manifold.
void print_cells () const
Print timevalues of each vertex in the cell and the resulting cell->info().
void print_details () const
Print details of the manifold.
void print_vertices () const
Print values of a vertex->info().
void print_volume_per_timeslice () const
Print the codimension 1 volume of simplices (faces) per timeslice.
auto simplices () const
auto spacelike_face_count (Int_precision const timevalue) const noexcept -> std::size_t
auto updated () const -> Manifold
Return a manifold rebuilt from the current canonical topology.
auto vertices () const
Static Public Attributes
static int constexpr dimension = 3
Dimensionality of the manifold.
static topology_type constexpr topology = topology_type::SPHERICAL
Topology of the manifold.
Private Types
using Geometry = Geometry_3
using Triangulation = foliated_triangulations::FoliatedTriangulation_3
Private Attributes
Geometry m_geometry
The data structure of scalar values for computations.
Triangulation m_triangulation
The data structure of geometric and combinatorial relationships.
Friends
void swap (Manifold &swap_from, Manifold &swap_into) noexcept
Non-member swap function for Manifolds.
Detailed Description
3D Manifold
Definition at line 44 of file Manifold.hpp.
Member Typedef Documentation
Geometry
using cdt::manifolds::Manifold< 3 >::Geometry = Geometry_3 private
Definition at line 47 of file Manifold.hpp.
Triangulation
using cdt::manifolds::Manifold< 3 >::Triangulation = foliated_triangulations::FoliatedTriangulation_3 private
Definition at line 46 of file Manifold.hpp.
Constructor & Destructor Documentation
Manifold() [1/4]
cdt::manifolds::Manifold< 3 >::Manifold (Triangulation t_foliated_triangulation) inline explicit
Construct manifold from a Foliated triangulation.
Parameters
t_foliated_triangulation Triangulation used to construct manifold
Definition at line 106 of file Manifold.hpp.
References m_geometry, and m_triangulation.
Manifold() [2/4]
cdt::manifolds::Manifold< 3 >::Manifold (Int_precision const t_desired_simplices, Int_precision const t_desired_timeslices, cdt::Random & generator, double const t_initial_radius = INITIAL_RADIUS, double const t_foliation_spacing = FOLIATION_SPACING) inline
Construct a manifold with a caller-owned initialization stream.
Parameters
t_desired_simplices Desired number of simplices
t_desired_timeslices Desired number of timeslices
generator Caller-owned initialization stream whose state is advanced during construction
t_initial_radius Radius of the first timeslice
t_foliation_spacing Radial separation between timeslices
Definition at line 118 of file Manifold.hpp.
References Manifold(), and cdt::INITIAL_RADIUS.
Manifold() [3/4]
cdt::manifolds::Manifold< 3 >::Manifold (Int_precision const t_desired_simplices, Int_precision const t_desired_timeslices, cdt::Random && generator, double const t_initial_radius = INITIAL_RADIUS, double const t_foliation_spacing = FOLIATION_SPACING) inline
Construct from an explicit temporary initialization stream.
Parameters
t_desired_simplices Desired number of simplices
t_desired_timeslices Desired number of timeslices
generator Temporary initialization stream whose state is consumed during construction
t_initial_radius Radius of the first timeslice
t_foliation_spacing Radial separation between timeslices
Definition at line 135 of file Manifold.hpp.
References Manifold(), and cdt::INITIAL_RADIUS.
Manifold() [4/4]
cdt::manifolds::Manifold< 3 >::Manifold (Causal_vertices_t< 3 > const & causal_vertices, double const t_initial_radius = INITIAL_RADIUS, double const t_foliation_spacing = FOLIATION_SPACING) inline explicit
Construct manifold from Causal_vertices Pass-by-value-then-move.
Parameters
causal_vertices Causal_vertices to place into the Manifold
t_initial_radius Radius of first timeslice
t_foliation_spacing Radial separation between timeslices
Definition at line 148 of file Manifold.hpp.
References Manifold(), and cdt::INITIAL_RADIUS.
Member Function Documentation
check_simplices()
auto cdt::manifolds::Manifold< 3 >::check_simplices () const -> bool inline nodiscard
Returns
True if all cells in triangulation are classified and match number in geometry
Definition at line 287 of file Manifold.hpp.
References m_triangulation, N3(), and simplices().
check_vertices()
auto cdt::manifolds::Manifold< 3 >::check_vertices () const -> bool inline nodiscard
Returns
True if every vertex carries the expected timevalue
Definition at line 294 of file Manifold.hpp.
References m_triangulation.
delaunay_snapshot()
auto cdt::manifolds::Manifold< 3 >::delaunay_snapshot () const -> Delaunay_t< 3 > inline nodiscard
Returns
An owning snapshot of the canonical Delaunay triangulation
Handles obtained from the snapshot cannot mutate this manifold or invalidate its derived geometry and topology caches.
Definition at line 177 of file Manifold.hpp.
References m_triangulation.
dimensionality()
auto cdt::manifolds::Manifold< 3 >::dimensionality () const inline nodiscard
Returns
Run-time dimensionality of the triangulation data structure
Definition at line 204 of file Manifold.hpp.
References m_triangulation.
edges()
auto cdt::manifolds::Manifold< 3 >::edges () const inline nodiscard
Returns
Number of 1D edges in triangulation data structure
Definition at line 262 of file Manifold.hpp.
References m_triangulation.
faces()
auto cdt::manifolds::Manifold< 3 >::faces () const inline nodiscard
Returns
Number of 2D faces in triangulation data structure
Definition at line 246 of file Manifold.hpp.
References m_triangulation.
foliation_spacing()
auto cdt::manifolds::Manifold< 3 >::foliation_spacing () const inline nodiscard
Radial separation between timeslices.
Definition at line 212 of file Manifold.hpp.
References m_triangulation.
get_geometry()
auto cdt::manifolds::Manifold< 3 >::get_geometry () const -> Geometry const & inline nodiscard
Returns
A read-only reference to the Geometry
Definition at line 181 of file Manifold.hpp.
References m_geometry.
initial_radius()
auto cdt::manifolds::Manifold< 3 >::initial_radius () const inline nodiscard
Initial radius of the first timeslice.
Definition at line 208 of file Manifold.hpp.
References m_triangulation.
is_correct()
auto cdt::manifolds::Manifold< 3 >::is_correct () const -> bool inline nodiscard
Returns
If base data structures are correct
Definition at line 200 of file Manifold.hpp.
References m_triangulation.
is_delaunay()
auto cdt::manifolds::Manifold< 3 >::is_delaunay () const -> bool inline nodiscard
Forwarding to FoliatedTriangulation.is_delaunay().
Returns
True if the Manifold triangulation is Delaunay
Definition at line 191 of file Manifold.hpp.
References m_triangulation.
is_foliated()
auto cdt::manifolds::Manifold< 3 >::is_foliated () const -> bool inline nodiscard
Forwarding to FoliatedTriangulation_3.is_foliated().
Returns
True if the Manifold triangulation is foliated
Definition at line 186 of file Manifold.hpp.
References m_triangulation.
is_valid()
auto cdt::manifolds::Manifold< 3 >::is_valid () const -> bool inline nodiscard
Forwarding to FoliatedTriangulation.is_tds_valid().
Returns
True if the TriangulationDataStructure is valid
Definition at line 196 of file Manifold.hpp.
References m_triangulation.
max_time()
auto cdt::manifolds::Manifold< 3 >::max_time () const inline nodiscard
Returns
Maximum timeslice value in triangulation data structure
Definition at line 282 of file Manifold.hpp.
References m_triangulation.
min_time()
auto cdt::manifolds::Manifold< 3 >::min_time () const inline nodiscard
Returns
Minimum timeslice value in triangulation data structure
Definition at line 278 of file Manifold.hpp.
References m_triangulation.
N0()
auto cdt::manifolds::Manifold< 3 >::N0 () const inline nodiscard
Returns
Number of vertices in geometry data structure
Definition at line 269 of file Manifold.hpp.
References m_geometry.
Referenced by print().
N1()
auto cdt::manifolds::Manifold< 3 >::N1 () const inline nodiscard
Returns
Number of 1D edges in geometry data structure
Definition at line 253 of file Manifold.hpp.
References m_geometry.
Referenced by print().
N1_SL()
auto cdt::manifolds::Manifold< 3 >::N1_SL () const inline nodiscard
Returns
Number of spacelike edges in triangulation data structure
Definition at line 256 of file Manifold.hpp.
References m_triangulation.
Referenced by print_details().
N1_TL()
auto cdt::manifolds::Manifold< 3 >::N1_TL () const inline nodiscard
Returns
Number of timelike edges in triangulation data structure
Definition at line 259 of file Manifold.hpp.
References m_triangulation.
Referenced by print_details().
N2()
auto cdt::manifolds::Manifold< 3 >::N2 () const inline nodiscard
Returns
Number of 2D faces in geometry data structure
Definition at line 238 of file Manifold.hpp.
References m_geometry.
Referenced by print().
N3()
auto cdt::manifolds::Manifold< 3 >::N3 () const inline nodiscard
Returns
Number of 3D simplices in geometry data structure
Definition at line 216 of file Manifold.hpp.
References m_geometry.
Referenced by check_simplices(), and print().
N3_13()
auto cdt::manifolds::Manifold< 3 >::N3_13 () const inline nodiscard
Returns
Number of (1,3) simplices in geometry data structure
Definition at line 225 of file Manifold.hpp.
References m_geometry.
Referenced by print_details().
N3_22()
auto cdt::manifolds::Manifold< 3 >::N3_22 () const inline nodiscard
Returns
Number of (2,2) simplices in geometry data structure
Definition at line 222 of file Manifold.hpp.
References m_geometry.
Referenced by print_details().
N3_31()
auto cdt::manifolds::Manifold< 3 >::N3_31 () const inline nodiscard
Returns
Number of (3,1) simplices in geometry data structure
Definition at line 219 of file Manifold.hpp.
References m_geometry.
Referenced by print_details().
N3_31_13()
auto cdt::manifolds::Manifold< 3 >::N3_31_13 () const inline nodiscard
Returns
Number of (3,1) and (1,3) simplices in geometry data structure
Definition at line 228 of file Manifold.hpp.
References m_geometry.
operator=()
auto cdt::manifolds::Manifold< 3 >::operator= (Manifold< 3 > && other) -> Manifold & inline noexcept
Default move assignment.
Definition at line 87 of file Manifold.hpp.
References Manifold(), and swap.
print()
void cdt::manifolds::Manifold< 3 >::print () const inline
Print manifold.
Definition at line 311 of file Manifold.hpp.
References N0(), N1(), N2(), and N3().
Referenced by main().
print_cells()
void cdt::manifolds::Manifold< 3 >::print_cells () const inline
Print timevalues of each vertex in the cell and the resulting cell->info().
Definition at line 308 of file Manifold.hpp.
References m_triangulation.
print_details()
void cdt::manifolds::Manifold< 3 >::print_details () const inline
Print details of the manifold.
Definition at line 326 of file Manifold.hpp.
References N1_SL(), N1_TL(), N3_13(), N3_22(), and N3_31().
Referenced by main().
print_vertices()
void cdt::manifolds::Manifold< 3 >::print_vertices () const inline
Print values of a vertex->info().
Definition at line 304 of file Manifold.hpp.
References m_triangulation.
print_volume_per_timeslice()
void cdt::manifolds::Manifold< 3 >::print_volume_per_timeslice () const inline
Print the codimension 1 volume of simplices (faces) per timeslice.
Definition at line 298 of file Manifold.hpp.
References m_triangulation.
Referenced by main().
simplices()
auto cdt::manifolds::Manifold< 3 >::simplices () const inline nodiscard
Returns
Number of 3D simplices in triangulation data structure
Definition at line 231 of file Manifold.hpp.
References m_triangulation.
Referenced by check_simplices().
spacelike_face_count()
auto cdt::manifolds::Manifold< 3 >::spacelike_face_count (Int_precision const timevalue) const -> std::size_t inline nodiscard noexcept
Returns
Number of spacelike faces on a timeslice
Definition at line 241 of file Manifold.hpp.
References m_triangulation.
updated()
auto cdt::manifolds::Manifold< 3 >::updated () const -> Manifold inline nodiscard
Return a manifold rebuilt from the current canonical topology.
The source remains unchanged. The returned triangulation caches and geometry are constructed together, so failure cannot publish a partially updated state.
Definition at line 161 of file Manifold.hpp.
References Manifold(), and m_triangulation.
vertices()
auto cdt::manifolds::Manifold< 3 >::vertices () const inline nodiscard
Returns
Number of vertices in triangulation data structure
Definition at line 272 of file Manifold.hpp.
References m_triangulation.
Friends And Related Symbol Documentation
swap
void swap (Manifold< 3 > & swap_from, Manifold< 3 > & swap_into) friend
Non-member swap function for Manifolds.
Used for noexcept updates of manifolds after moves.
Parameters
swap_from The value to be swapped from. Assumed to be discarded.
swap_into The value to be swapped into.
Definition at line 97 of file Manifold.hpp.
References Manifold(), and swap.
Referenced by operator=(), and swap.
Member Data Documentation
dimension
int constexpr cdt::manifolds::Manifold< 3 >::dimension = 3 static constexpr
Dimensionality of the manifold.
Used to determine the manifold dimension at compile-time
Definition at line 66 of file Manifold.hpp.
m_geometry
Geometry cdt::manifolds::Manifold< 3 >::m_geometry private
The data structure of scalar values for computations.
Definition at line 61 of file Manifold.hpp.
Referenced by Manifold(), get_geometry(), N0(), N1(), N2(), N3(), N3_13(), N3_22(), N3_31(), and N3_31_13().
m_triangulation
Triangulation cdt::manifolds::Manifold< 3 >::m_triangulation private
The data structure of geometric and combinatorial relationships.
Definition at line 58 of file Manifold.hpp.
Referenced by Manifold(), check_simplices(), check_vertices(), delaunay_snapshot(), dimensionality(), edges(), faces(), foliation_spacing(), initial_radius(), is_correct(), is_delaunay(), is_foliated(), is_valid(), max_time(), min_time(), N1_SL(), N1_TL(), print_cells(), print_vertices(), print_volume_per_timeslice(), simplices(), spacelike_face_count(), updated(), and vertices().
topology
topology_type constexpr cdt::manifolds::Manifold< 3 >::topology = topology_type::SPHERICAL static constexpr
Topology of the manifold.
Definition at line 69 of file Manifold.hpp.
The documentation for this class was generated from the following file:
include/Manifold.hpp