CDT++: cdt::foliated_triangulations::FoliatedTriangulation< 3 > Class Reference
cdt::foliated_triangulations::FoliatedTriangulation< 3 > Class Reference
3D Foliated triangulation
#include <Foliated_triangulation.hpp>
Public Member Functions
FoliatedTriangulation ()=default
Default ctor.
FoliatedTriangulation (Causal_vertices_t< 3 > const &causal_vertices, double const t_initial_radius=INITIAL_RADIUS, double const t_foliation_spacing=FOLIATION_SPACING)
Constructor from Causal_vertices.
FoliatedTriangulation (Delaunay triangulation, double const initial_radius=INITIAL_RADIUS, double const foliation_spacing=FOLIATION_SPACING)
Constructor using delaunay triangulation Pass-by-value-then-move. Delaunay is the ctor for the Delaunay triangulation.
FoliatedTriangulation (FoliatedTriangulation &&other) noexcept=default
Move constructor.
FoliatedTriangulation (FoliatedTriangulation const &other)
Copy Constructor.
FoliatedTriangulation (Int_precision const t_simplices, Int_precision const t_timeslices, cdt::Random &&generator, double const t_initial_radius=INITIAL_RADIUS, double const t_foliation_spacing=FOLIATION_SPACING)
Construct from an explicit temporary initialization stream.
FoliatedTriangulation (Int_precision const t_simplices, Int_precision const t_timeslices, cdt::Random &generator, double const t_initial_radius=INITIAL_RADIUS, double const t_foliation_spacing=FOLIATION_SPACING)
Constructor with a caller-owned initialization stream.
~FoliatedTriangulation ()=default
Default dtor.
auto check_all_cells () const -> bool
Check that all cells are correctly classified.
auto check_all_vertices () const -> bool
auto delaunay_snapshot () const -> Delaunay
auto dimension () const
auto does_vertex_radius_match_timevalue (Vertex_handle_t< 3 > const t_vertex) const -> bool
Check the radius of a vertex from the origin with its timevalue.
auto expected_radius (Vertex_handle_t< 3 > const &t_vertex) const -> double
Calculates the expected radial distance of a vertex.
auto expected_timevalue (Vertex_handle_t< 3 > const &t_vertex) const -> int
Calculate the expected timevalue for a vertex.
auto fix_cells () -> bool
Fix all cells in the triangulation.
auto fix_vertices () -> bool
Fix vertices with wrong timevalues after foliation.
auto foliation_spacing () const
auto initial_radius () const
auto is_correct () const -> bool
auto is_delaunay () const -> bool
auto is_fixed () -> bool
auto is_foliated () const -> bool
Verifies the triangulation is properly foliated.
auto is_initialized () const -> bool
auto is_tds_valid () const -> bool
auto max_time () const
auto min_time () const
auto N1_SL () const
auto N1_TL () const
auto number_of_finite_cells () const
auto number_of_finite_edges () const
auto number_of_finite_facets () const
auto number_of_one_three_cells () const noexcept -> std::size_t
auto number_of_spacelike_faces () const noexcept -> std::size_t
auto number_of_three_one_cells () const noexcept -> std::size_t
auto number_of_two_two_cells () const noexcept -> std::size_t
auto number_of_vertices () const
auto operator= (FoliatedTriangulation &&other) noexcept -> FoliatedTriangulation &
Move assignment operator.
auto operator= (FoliatedTriangulation const &other) -> FoliatedTriangulation &
Copy assignment operator.
void print () const
Print triangulation statistics.
void print_cells () const
Print timevalues of each vertex in the cell and the resulting cell->info().
void print_edges () const
Print timevalues of each vertex in the edge and classify as timelike or spacelike.
void print_vertices () const
Print values of a vertex.
void print_volume_per_timeslice () const
Print the number of spacelike faces per timeslice.
auto spacelike_face_count (Int_precision const timevalue) const noexcept -> std::size_t
Private Types
using Cell_container = std::vector<Cell_handle>
using Cell_handle = Cell_handle_t<3>
using Delaunay = Delaunay_t<3>
using Edge_container = std::vector<Edge_handle_t<3>>
using Face_container = std::vector<Face_handle_t<3>>
using Vertex_container = std::vector<Vertex_handle>
using Vertex_handle = Vertex_handle_t<3>
using Volume_by_timeslice = std::vector<Volume_entry>
using Volume_entry = std::pair<Int_precision, Facet_t<3>>
Private Member Functions
auto classify_cells (Cell_container const &cells) const -> Cell_container
Classify cells.
auto classify_vertices (Vertex_container const &vertices) const -> Vertex_container
auto collect_edges () const -> Edge_container
auto collect_faces () const -> Face_container
Static Private Member Functions
static auto cache_spacelike_facets (Face_container const &faces) -> Volume_by_timeslice
static auto require_nonempty (Delaunay triangulation) -> Delaunay
Private Attributes
Cell_container m_cells
Edge_container m_edges
Face_container m_faces
double m_foliation_spacing {FOLIATION_SPACING}
double m_initial_radius {INITIAL_RADIUS}
Int_precision m_max_timevalue {0}
Int_precision m_min_timevalue {0}
Cell_container m_one_three
Edge_container m_spacelike_edges
Volume_by_timeslice m_spacelike_facets
Cell_container m_three_one
Edge_container m_timelike_edges
Delaunay m_triangulation {Delaunay{}}
Cell_container m_two_two
Vertex_container m_vertices
Friends
void swap (FoliatedTriangulation &swap_from, FoliatedTriangulation &swap_into) noexcept
Non-member swap function for Foliated Triangulations.
Detailed Description
3D Foliated triangulation
This class is a wrapper around a Delaunay triangulation. The Delaunay triangulation is augmented with a timevalue for each vertex and a simplex type for each cell. The FoliatedTriangulation class invariant is that the Delaunay triangulation has validly foliated vertices and cells, and has further containers for the various sub-simplicial complexes of the triangulation.
Definition at line 1095 of file Foliated_triangulation.hpp.
Member Typedef Documentation
Cell_container
using cdt::foliated_triangulations::FoliatedTriangulation< 3 >::Cell_container = std::vector<Cell_handle> private
Definition at line 1099 of file Foliated_triangulation.hpp.
Cell_handle
using cdt::foliated_triangulations::FoliatedTriangulation< 3 >::Cell_handle = Cell_handle_t<3> private
Definition at line 1098 of file Foliated_triangulation.hpp.
Delaunay
using cdt::foliated_triangulations::FoliatedTriangulation< 3 >::Delaunay = Delaunay_t<3> private
Definition at line 1097 of file Foliated_triangulation.hpp.
Edge_container
using cdt::foliated_triangulations::FoliatedTriangulation< 3 >::Edge_container = std::vector<Edge_handle_t<3>> private
Definition at line 1101 of file Foliated_triangulation.hpp.
Face_container
using cdt::foliated_triangulations::FoliatedTriangulation< 3 >::Face_container = std::vector<Face_handle_t<3>> private
Definition at line 1100 of file Foliated_triangulation.hpp.
Vertex_container
using cdt::foliated_triangulations::FoliatedTriangulation< 3 >::Vertex_container = std::vector<Vertex_handle> private
Definition at line 1103 of file Foliated_triangulation.hpp.
Vertex_handle
using cdt::foliated_triangulations::FoliatedTriangulation< 3 >::Vertex_handle = Vertex_handle_t<3> private
Definition at line 1102 of file Foliated_triangulation.hpp.
Volume_by_timeslice
using cdt::foliated_triangulations::FoliatedTriangulation< 3 >::Volume_by_timeslice = std::vector<Volume_entry> private
Definition at line 1105 of file Foliated_triangulation.hpp.
Volume_entry
using cdt::foliated_triangulations::FoliatedTriangulation< 3 >::Volume_entry = std::pair<Int_precision, Facet_t<3>> private
Definition at line 1104 of file Foliated_triangulation.hpp.
Constructor & Destructor Documentation
FoliatedTriangulation() [1/6]
cdt::foliated_triangulations::FoliatedTriangulation< 3 >::FoliatedTriangulation (FoliatedTriangulation< 3 > const & other) inline
Copy Constructor.
Definition at line 1172 of file Foliated_triangulation.hpp.
References FoliatedTriangulation(), and swap.
FoliatedTriangulation() [2/6]
cdt::foliated_triangulations::FoliatedTriangulation< 3 >::FoliatedTriangulation (FoliatedTriangulation< 3 > && other) default noexcept
Move constructor.
Moves the triangulation and all handle caches directly, without first performing the potentially throwing default construction.
References FoliatedTriangulation().
FoliatedTriangulation() [3/6]
cdt::foliated_triangulations::FoliatedTriangulation< 3 >::FoliatedTriangulation (Delaunay triangulation, double const initial_radius = INITIAL_RADIUS, double const foliation_spacing = FOLIATION_SPACING) inline explicit
Constructor using delaunay triangulation Pass-by-value-then-move. Delaunay is the ctor for the Delaunay triangulation.
Parameters
triangulation Delaunay triangulation
initial_radius Radius of first timeslice
foliation_spacing Radial separation between timeslices
Definition at line 1250 of file Foliated_triangulation.hpp.
References classify_cells(), collect_edges(), collect_faces(), foliation_spacing(), cdt::INITIAL_RADIUS, initial_radius(), and m_triangulation.
FoliatedTriangulation() [4/6]
cdt::foliated_triangulations::FoliatedTriangulation< 3 >::FoliatedTriangulation (Int_precision const t_simplices, Int_precision const t_timeslices, cdt::Random & generator, double const t_initial_radius = INITIAL_RADIUS, double const t_foliation_spacing = FOLIATION_SPACING) inline
Constructor with a caller-owned initialization stream.
Parameters
t_simplices Desired number of simplices
t_timeslices Desired number of timeslices
generator Caller-owned initialization stream whose state is advanced during construction
t_initial_radius Radius of the first timeslice
t_foliation_spacing Radial separation between timeslices
Definition at line 1277 of file Foliated_triangulation.hpp.
References FoliatedTriangulation(), and cdt::INITIAL_RADIUS.
FoliatedTriangulation() [5/6]
cdt::foliated_triangulations::FoliatedTriangulation< 3 >::FoliatedTriangulation (Int_precision const t_simplices, Int_precision const t_timeslices, cdt::Random && generator, double const t_initial_radius = INITIAL_RADIUS, double const t_foliation_spacing = FOLIATION_SPACING) inline
Construct from an explicit temporary initialization stream.
Parameters
t_simplices Desired number of simplices
t_timeslices Desired number of timeslices
generator Temporary initialization stream whose state is consumed during construction
t_initial_radius Radius of the first timeslice
t_foliation_spacing Radial separation between timeslices
Definition at line 1295 of file Foliated_triangulation.hpp.
References FoliatedTriangulation(), and cdt::INITIAL_RADIUS.
FoliatedTriangulation() [6/6]
cdt::foliated_triangulations::FoliatedTriangulation< 3 >::FoliatedTriangulation (Causal_vertices_t< 3 > const & causal_vertices, double const t_initial_radius = INITIAL_RADIUS, double const t_foliation_spacing = FOLIATION_SPACING) inline explicit
Constructor from Causal_vertices.
Parameters
causal_vertices Causal_vertices to place into the FoliatedTriangulation
t_initial_radius Radius of first timeslice
t_foliation_spacing Radial separation between timeslices
Definition at line 1309 of file Foliated_triangulation.hpp.
References FoliatedTriangulation(), and cdt::INITIAL_RADIUS.
Member Function Documentation
cache_spacelike_facets()
auto cdt::foliated_triangulations::FoliatedTriangulation< 3 >::cache_spacelike_facets (Face_container const & faces) -> Volume_by_timeslice inline static nodiscard private
Definition at line 1131 of file Foliated_triangulation.hpp.
check_all_cells()
auto cdt::foliated_triangulations::FoliatedTriangulation< 3 >::check_all_cells () const -> bool inline nodiscard
Check that all cells are correctly classified.
A default triangulation will have no cells, and for this case the triangulation is correctly classified. A triangulation with cells will have them checked via check_cells.
Returns
True if there are no cells or all cells are validly classified
Definition at line 1548 of file Foliated_triangulation.hpp.
References m_triangulation.
Referenced by is_correct().
check_all_vertices()
auto cdt::foliated_triangulations::FoliatedTriangulation< 3 >::check_all_vertices () const -> bool inline nodiscard
Returns
True if all vertices have correct timevalues
Definition at line 1475 of file Foliated_triangulation.hpp.
References m_triangulation.
classify_cells()
auto cdt::foliated_triangulations::FoliatedTriangulation< 3 >::classify_cells (Cell_container const & cells) const -> Cell_container inline nodiscard private
Classify cells.
Parameters
cells The container of simplices to classify
Returns
A container of simplices with Cell_type written to cell->info()
Definition at line 1598 of file Foliated_triangulation.hpp.
References number_of_finite_cells().
Referenced by FoliatedTriangulation().
classify_vertices()
auto cdt::foliated_triangulations::FoliatedTriangulation< 3 >::classify_vertices (Vertex_container const & vertices) const -> Vertex_container inline nodiscard private
Definition at line 1583 of file Foliated_triangulation.hpp.
collect_edges()
auto cdt::foliated_triangulations::FoliatedTriangulation< 3 >::collect_edges () const -> Edge_container inline nodiscard private
Returns
Container of all the finite edges in the triangulation
Definition at line 1630 of file Foliated_triangulation.hpp.
References is_tds_valid(), m_triangulation, and number_of_finite_edges().
Referenced by FoliatedTriangulation().
collect_faces()
auto cdt::foliated_triangulations::FoliatedTriangulation< 3 >::collect_faces () const -> Face_container inline nodiscard private
Returns
Container of all the finite facets in the triangulation
Definition at line 1610 of file Foliated_triangulation.hpp.
References is_tds_valid(), and m_triangulation.
Referenced by FoliatedTriangulation().
delaunay_snapshot()
auto cdt::foliated_triangulations::FoliatedTriangulation< 3 >::delaunay_snapshot () const -> Delaunay inline nodiscard
Returns
An owning snapshot of the Delaunay triangulation
Mutating the returned value cannot invalidate this object's cached topology classifications.
Definition at line 1371 of file Foliated_triangulation.hpp.
References m_triangulation.
dimension()
auto cdt::foliated_triangulations::FoliatedTriangulation< 3 >::dimension () const inline nodiscard
Returns
Dimensionality of triangulation data structure (int)
Definition at line 1397 of file Foliated_triangulation.hpp.
References m_triangulation.
does_vertex_radius_match_timevalue()
auto cdt::foliated_triangulations::FoliatedTriangulation< 3 >::does_vertex_radius_match_timevalue (Vertex_handle_t< 3 > const t_vertex) const -> bool inline nodiscard
Check the radius of a vertex from the origin with its timevalue.
Parameters
t_vertex The vertex to check
Returns
True if the effective radial distance squared matches timevalue squared
Definition at line 1437 of file Foliated_triangulation.hpp.
References expected_radius(), and cdt::TOLERANCE.
expected_radius()
auto cdt::foliated_triangulations::FoliatedTriangulation< 3 >::expected_radius (Vertex_handle_t< 3 > const & t_vertex) const -> double inline nodiscard
Calculates the expected radial distance of a vertex.
The formula for the radius is:
\[R=I+S(t-1)\]
Where I is INITIAL_RADIUS, S is RADIAL_SEPARATION, and t is timevalue
Parameters
t_vertex The vertex to check
Returns
The expected radial distance of the vertex with that timevalue
Definition at line 1457 of file Foliated_triangulation.hpp.
Referenced by does_vertex_radius_match_timevalue().
expected_timevalue()
auto cdt::foliated_triangulations::FoliatedTriangulation< 3 >::expected_timevalue (Vertex_handle_t< 3 > const & t_vertex) const -> int inline nodiscard
Calculate the expected timevalue for a vertex.
Parameters
t_vertex The vertex to check
Returns
The expected timevalue of the vertex
Definition at line 1467 of file Foliated_triangulation.hpp.
Referenced by print_vertices().
fix_cells()
auto cdt::foliated_triangulations::FoliatedTriangulation< 3 >::fix_cells () -> bool inline
Fix all cells in the triangulation.
Definition at line 1554 of file Foliated_triangulation.hpp.
References FoliatedTriangulation(), m_triangulation, and swap.
fix_vertices()
auto cdt::foliated_triangulations::FoliatedTriangulation< 3 >::fix_vertices () -> bool inline nodiscard
Fix vertices with wrong timevalues after foliation.
Definition at line 1482 of file Foliated_triangulation.hpp.
References FoliatedTriangulation(), m_triangulation, and swap.
foliation_spacing()
auto cdt::foliated_triangulations::FoliatedTriangulation< 3 >::foliation_spacing () const inline nodiscard
Returns
The spacing between timeslices
Definition at line 1431 of file Foliated_triangulation.hpp.
Referenced by FoliatedTriangulation().
initial_radius()
auto cdt::foliated_triangulations::FoliatedTriangulation< 3 >::initial_radius () const inline nodiscard
Returns
The initial radius for timeslice = 1
Definition at line 1428 of file Foliated_triangulation.hpp.
Referenced by FoliatedTriangulation().
is_correct()
auto cdt::foliated_triangulations::FoliatedTriangulation< 3 >::is_correct () const -> bool inline nodiscard
Returns
True if the Foliated Triangulation class invariants hold
Definition at line 1339 of file Foliated_triangulation.hpp.
References check_all_cells(), is_foliated(), and is_tds_valid().
Referenced by is_initialized().
is_delaunay()
auto cdt::foliated_triangulations::FoliatedTriangulation< 3 >::is_delaunay () const -> bool inline nodiscard
Returns
True if the triangulation is Delaunay
Definition at line 1331 of file Foliated_triangulation.hpp.
References m_triangulation.
Referenced by is_initialized().
is_fixed()
auto cdt::foliated_triangulations::FoliatedTriangulation< 3 >::is_fixed () -> bool inline nodiscard
Returns
True if fixes were done on the Delaunay triangulation
Definition at line 1350 of file Foliated_triangulation.hpp.
References FoliatedTriangulation(), m_triangulation, and swap.
is_foliated()
auto cdt::foliated_triangulations::FoliatedTriangulation< 3 >::is_foliated () const -> bool inline nodiscard
Verifies the triangulation is properly foliated.
Can not be called until after Foliated_triangulation has been constructed (i.e. not in make_triangulation)
Returns
True if foliated correctly
Definition at line 1325 of file Foliated_triangulation.hpp.
References m_triangulation.
Referenced by is_correct().
is_initialized()
auto cdt::foliated_triangulations::FoliatedTriangulation< 3 >::is_initialized () const -> bool inline nodiscard
Returns
True if the Foliated Triangulation has been initialized correctly
Definition at line 1346 of file Foliated_triangulation.hpp.
References is_correct(), and is_delaunay().
is_tds_valid()
auto cdt::foliated_triangulations::FoliatedTriangulation< 3 >::is_tds_valid () const -> bool inline nodiscard
Returns
True if the triangulation data structure is valid
Definition at line 1335 of file Foliated_triangulation.hpp.
References m_triangulation.
Referenced by collect_edges(), collect_faces(), and is_correct().
max_time()
auto cdt::foliated_triangulations::FoliatedTriangulation< 3 >::max_time () const inline nodiscard
Returns
Maximum time value in triangulation
Definition at line 1422 of file Foliated_triangulation.hpp.
Referenced by print_volume_per_timeslice().
min_time()
auto cdt::foliated_triangulations::FoliatedTriangulation< 3 >::min_time () const inline nodiscard
Returns
Minimum time value in triangulation
Definition at line 1425 of file Foliated_triangulation.hpp.
Referenced by print_volume_per_timeslice().
N1_SL()
auto cdt::foliated_triangulations::FoliatedTriangulation< 3 >::N1_SL () const inline nodiscard
Returns
Number of spacelike edges
Definition at line 1418 of file Foliated_triangulation.hpp.
N1_TL()
auto cdt::foliated_triangulations::FoliatedTriangulation< 3 >::N1_TL () const inline nodiscard
Returns
Number of timelike edges
Definition at line 1414 of file Foliated_triangulation.hpp.
number_of_finite_cells()
auto cdt::foliated_triangulations::FoliatedTriangulation< 3 >::number_of_finite_cells () const inline nodiscard
Returns
Number of 3D simplices in triangulation data structure
Definition at line 1375 of file Foliated_triangulation.hpp.
References m_triangulation.
Referenced by classify_cells(), and print().
number_of_finite_edges()
auto cdt::foliated_triangulations::FoliatedTriangulation< 3 >::number_of_finite_edges () const inline nodiscard
Returns
Number of 1D edges in triangulation data structure
Definition at line 1387 of file Foliated_triangulation.hpp.
References m_triangulation.
Referenced by collect_edges(), and print().
number_of_finite_facets()
auto cdt::foliated_triangulations::FoliatedTriangulation< 3 >::number_of_finite_facets () const inline nodiscard
Returns
Number of 2D faces in triangulation data structure
Definition at line 1381 of file Foliated_triangulation.hpp.
References m_triangulation.
Referenced by print().
number_of_one_three_cells()
auto cdt::foliated_triangulations::FoliatedTriangulation< 3 >::number_of_one_three_cells () const -> std::size_t inline nodiscard noexcept
Returns
Number of classified (1,3) cells
Definition at line 1540 of file Foliated_triangulation.hpp.
number_of_spacelike_faces()
auto cdt::foliated_triangulations::FoliatedTriangulation< 3 >::number_of_spacelike_faces () const -> std::size_t inline nodiscard noexcept
Returns
Total number of spacelike facets
Definition at line 1410 of file Foliated_triangulation.hpp.
number_of_three_one_cells()
auto cdt::foliated_triangulations::FoliatedTriangulation< 3 >::number_of_three_one_cells () const -> std::size_t inline nodiscard noexcept
Returns
Number of classified (3,1) cells
Definition at line 1532 of file Foliated_triangulation.hpp.
number_of_two_two_cells()
auto cdt::foliated_triangulations::FoliatedTriangulation< 3 >::number_of_two_two_cells () const -> std::size_t inline nodiscard noexcept
Returns
Number of classified (2,2) cells
Definition at line 1536 of file Foliated_triangulation.hpp.
number_of_vertices()
auto cdt::foliated_triangulations::FoliatedTriangulation< 3 >::number_of_vertices () const inline nodiscard
Returns
Number of vertices in triangulation data structure
Definition at line 1393 of file Foliated_triangulation.hpp.
References m_triangulation.
Referenced by print().
operator=() [1/2]
auto cdt::foliated_triangulations::FoliatedTriangulation< 3 >::operator= (FoliatedTriangulation< 3 > && other) -> FoliatedTriangulation & inline noexcept
Move assignment operator.
Definition at line 1204 of file Foliated_triangulation.hpp.
References FoliatedTriangulation(), and swap.
operator=() [2/2]
auto cdt::foliated_triangulations::FoliatedTriangulation< 3 >::operator= (FoliatedTriangulation< 3 > const & other) -> FoliatedTriangulation & inline
Copy assignment operator.
Builds a complete copy before replacing the current value.
Definition at line 1189 of file Foliated_triangulation.hpp.
References FoliatedTriangulation(), and swap.
print()
void cdt::foliated_triangulations::FoliatedTriangulation< 3 >::print () const inline
Print triangulation statistics.
Definition at line 1573 of file Foliated_triangulation.hpp.
References number_of_finite_cells(), number_of_finite_edges(), number_of_finite_facets(), and number_of_vertices().
print_cells()
void cdt::foliated_triangulations::FoliatedTriangulation< 3 >::print_cells () const inline
Print timevalues of each vertex in the cell and the resulting cell->info().
Definition at line 1569 of file Foliated_triangulation.hpp.
print_edges()
void cdt::foliated_triangulations::FoliatedTriangulation< 3 >::print_edges () const inline
Print timevalues of each vertex in the edge and classify as timelike or spacelike.
Definition at line 1509 of file Foliated_triangulation.hpp.
print_vertices()
void cdt::foliated_triangulations::FoliatedTriangulation< 3 >::print_vertices () const inline
Print values of a vertex.
Definition at line 1497 of file Foliated_triangulation.hpp.
References expected_timevalue().
print_volume_per_timeslice()
void cdt::foliated_triangulations::FoliatedTriangulation< 3 >::print_volume_per_timeslice () const inline
Print the number of spacelike faces per timeslice.
Definition at line 1522 of file Foliated_triangulation.hpp.
References max_time(), min_time(), and spacelike_face_count().
require_nonempty()
auto cdt::foliated_triangulations::FoliatedTriangulation< 3 >::require_nonempty (Delaunay triangulation) -> Delaunay inline static nodiscard private
Definition at line 1135 of file Foliated_triangulation.hpp.
spacelike_face_count()
auto cdt::foliated_triangulations::FoliatedTriangulation< 3 >::spacelike_face_count (Int_precision const timevalue) const -> std::size_t inline nodiscard noexcept
Returns
Number of spacelike facets on a timeslice
Definition at line 1400 of file Foliated_triangulation.hpp.
Referenced by print_volume_per_timeslice().
Friends And Related Symbol Documentation
swap
void swap (FoliatedTriangulation< 3 > & swap_from, FoliatedTriangulation< 3 > & swap_into) friend
Non-member swap function for Foliated Triangulations.
Note that this function calls swap() from CGAL's Triangulation_3 base class, which assumes that the first triangulation is discarded after it is swapped into the second one.
Parameters
swap_from The value to be swapped from. Assumed to be discarded.
swap_into The value to be swapped into.
Definition at line 1218 of file Foliated_triangulation.hpp.
References FoliatedTriangulation(), and swap.
Referenced by FoliatedTriangulation(), fix_cells(), fix_vertices(), is_fixed(), operator=(), operator=(), and swap.
Member Data Documentation
m_cells
Cell_container cdt::foliated_triangulations::FoliatedTriangulation< 3 >::m_cells private
Definition at line 1152 of file Foliated_triangulation.hpp.
m_edges
Edge_container cdt::foliated_triangulations::FoliatedTriangulation< 3 >::m_edges private
Definition at line 1158 of file Foliated_triangulation.hpp.
m_faces
Face_container cdt::foliated_triangulations::FoliatedTriangulation< 3 >::m_faces private
Definition at line 1156 of file Foliated_triangulation.hpp.
m_foliation_spacing
double cdt::foliated_triangulations::FoliatedTriangulation< 3 >::m_foliation_spacing {FOLIATION_SPACING} private
Definition at line 1150 of file Foliated_triangulation.hpp.
m_initial_radius
double cdt::foliated_triangulations::FoliatedTriangulation< 3 >::m_initial_radius {INITIAL_RADIUS} private
Definition at line 1149 of file Foliated_triangulation.hpp.
m_max_timevalue
Int_precision cdt::foliated_triangulations::FoliatedTriangulation< 3 >::m_max_timevalue {0} private
Definition at line 1161 of file Foliated_triangulation.hpp.
m_min_timevalue
Int_precision cdt::foliated_triangulations::FoliatedTriangulation< 3 >::m_min_timevalue {0} private
Definition at line 1162 of file Foliated_triangulation.hpp.
m_one_three
Cell_container cdt::foliated_triangulations::FoliatedTriangulation< 3 >::m_one_three private
Definition at line 1155 of file Foliated_triangulation.hpp.
m_spacelike_edges
Edge_container cdt::foliated_triangulations::FoliatedTriangulation< 3 >::m_spacelike_edges private
Definition at line 1160 of file Foliated_triangulation.hpp.
m_spacelike_facets
Volume_by_timeslice cdt::foliated_triangulations::FoliatedTriangulation< 3 >::m_spacelike_facets private
Definition at line 1157 of file Foliated_triangulation.hpp.
m_three_one
Cell_container cdt::foliated_triangulations::FoliatedTriangulation< 3 >::m_three_one private
Definition at line 1153 of file Foliated_triangulation.hpp.
m_timelike_edges
Edge_container cdt::foliated_triangulations::FoliatedTriangulation< 3 >::m_timelike_edges private
Definition at line 1159 of file Foliated_triangulation.hpp.
m_triangulation
Delaunay cdt::foliated_triangulations::FoliatedTriangulation< 3 >::m_triangulation {Delaunay{}} private
Data members initialized in order of declaration (Working Draft, Standard for C++ Programming Language, 11.9.3 section 13.3)
Definition at line 1148 of file Foliated_triangulation.hpp.
Referenced by FoliatedTriangulation(), check_all_cells(), check_all_vertices(), collect_edges(), collect_faces(), delaunay_snapshot(), dimension(), fix_cells(), fix_vertices(), is_delaunay(), is_fixed(), is_foliated(), is_tds_valid(), number_of_finite_cells(), number_of_finite_edges(), number_of_finite_facets(), and number_of_vertices().
m_two_two
Cell_container cdt::foliated_triangulations::FoliatedTriangulation< 3 >::m_two_two private
Definition at line 1154 of file Foliated_triangulation.hpp.
m_vertices
Vertex_container cdt::foliated_triangulations::FoliatedTriangulation< 3 >::m_vertices private
Definition at line 1151 of file Foliated_triangulation.hpp.
The documentation for this class was generated from the following file:
include/Foliated_triangulation.hpp