CDT++: cdt::MoveStrategy< Strategies::MOVE_ALWAYS, ManifoldType > Class Template Reference
cdt::MoveStrategy< Strategies::MOVE_ALWAYS, ManifoldType > Class Template Reference
The Move Always algorithm.
#include <Move_always.hpp>
Public Member Functions
MoveStrategy ()=default
Default ctor.
MoveStrategy (Int_precision const t_number_of_passes, Int_precision const t_checkpoint)
Construct a MoveAlways run using a fresh entropy-backed stream.
MoveStrategy (Int_precision const t_number_of_passes, Int_precision const t_checkpoint, cdt::Random random, bool const write_files=true)
Construct a MoveAlways run from an owned PCG stream.
MoveStrategy (Int_precision const t_number_of_passes, Int_precision const t_checkpoint, cdt::Random_seed const seed, bool const write_files=true)
Construct a replayable MoveAlways run from an explicit seed.
auto checkpoint () const noexcept
auto checkpoint_events () const noexcept
auto get_attempted () const
auto get_failed () const
auto get_succeeded () const
auto operator() (ManifoldType const &t_manifold) -> ManifoldType
Execute a fresh run while continuing the owned random stream.
auto passes () const noexcept
void print_results () const
Display results of the latest completed invocation.
auto seed () const noexcept
auto stream () const noexcept
auto writes_files () const noexcept
Private Types
using CommandResults = detail::MoveCommandResults<ManifoldType>
using PassResult = detail::MovePassResult<ManifoldType, std::monostate>
Private Member Functions
auto execute_pass (ManifoldType current, std::monostate strategy_state, Int_precision const attempts) -> PassResult
Static Private Member Functions
static void print_results (CommandResults const &results)
Private Attributes
MoveRunCadence m_cadence
Positive pass and checkpoint cadence.
Int_precision m_checkpoint_events {}
Checkpoint events from the latest completed invocation.
CommandResults m_command_results
Command counters from the latest completed invocation.
cdt::Random m_random
Run-owned random stream used for move selection and site ordering.
bool m_write_files {true}
Whether checkpoint triangulation files may be written.
Detailed Description
template<typename ManifoldType>
requires (ManifoldType::dimension == 3)
class cdt::MoveStrategy< Strategies::MOVE_ALWAYS, ManifoldType >
The Move Always algorithm.
Definition at line 29 of file Move_always.hpp.
Member Typedef Documentation
CommandResults
template<typename ManifoldType> using cdt::MoveStrategy< Strategies::MOVE_ALWAYS, ManifoldType >::CommandResults = detail::MoveCommandResults<ManifoldType> private
Definition at line 31 of file Move_always.hpp.
PassResult
template<typename ManifoldType> using cdt::MoveStrategy< Strategies::MOVE_ALWAYS, ManifoldType >::PassResult = detail::MovePassResult<ManifoldType, std::monostate> private
Definition at line 32 of file Move_always.hpp.
Constructor & Destructor Documentation
MoveStrategy() [1/3]
template<typename ManifoldType> cdt::MoveStrategy< Strategies::MOVE_ALWAYS, ManifoldType >::MoveStrategy (Int_precision const t_number_of_passes, Int_precision const t_checkpoint) inline
Construct a MoveAlways run using a fresh entropy-backed stream.
Parameters
t_number_of_passes Positive number of passes to run.
t_checkpoint Positive number of passes per checkpoint.
Exceptions
std::invalid_argument When either cadence value is nonpositive.
Definition at line 100 of file Move_always.hpp.
References MoveStrategy().
MoveStrategy() [2/3]
template<typename ManifoldType> cdt::MoveStrategy< Strategies::MOVE_ALWAYS, ManifoldType >::MoveStrategy (Int_precision const t_number_of_passes, Int_precision const t_checkpoint, cdt::Random_seed const seed, bool const write_files = true) inline
Construct a replayable MoveAlways run from an explicit seed.
Parameters
t_number_of_passes Positive number of passes to run.
t_checkpoint Positive number of passes per checkpoint.
seed Root seed for the owned random stream.
write_files Whether checkpoints may write triangulation files.
Exceptions
std::invalid_argument When either cadence value is nonpositive.
Definition at line 111 of file Move_always.hpp.
References MoveStrategy(), and seed().
MoveStrategy() [3/3]
template<typename ManifoldType> cdt::MoveStrategy< Strategies::MOVE_ALWAYS, ManifoldType >::MoveStrategy (Int_precision const t_number_of_passes, Int_precision const t_checkpoint, cdt::Random random, bool const write_files = true) inline
Construct a MoveAlways run from an owned PCG stream.
Parameters
t_number_of_passes Positive number of passes to run.
t_checkpoint Positive number of passes per checkpoint.
random Stream whose current state becomes owned by this strategy.
write_files Whether checkpoints may write triangulation files.
Exceptions
std::invalid_argument When either cadence value is nonpositive.
Definition at line 125 of file Move_always.hpp.
References m_cadence, m_random, and m_write_files.
Member Function Documentation
checkpoint()
template<typename ManifoldType> auto cdt::MoveStrategy< Strategies::MOVE_ALWAYS, ManifoldType >::checkpoint () const inline nodiscard noexcept
Returns
The number of passes per checkpoint
Definition at line 139 of file Move_always.hpp.
References m_cadence.
checkpoint_events()
template<typename ManifoldType> auto cdt::MoveStrategy< Strategies::MOVE_ALWAYS, ManifoldType >::checkpoint_events () const inline nodiscard noexcept
Returns
Checkpoint events completed by the latest invocation.
Definition at line 143 of file Move_always.hpp.
References m_checkpoint_events.
execute_pass()
template<typename ManifoldType> auto cdt::MoveStrategy< Strategies::MOVE_ALWAYS, ManifoldType >::execute_pass (ManifoldType current, std::monostate strategy_state, Int_precision const attempts) -> PassResult inline nodiscard private
Definition at line 49 of file Move_always.hpp.
get_attempted()
template<typename ManifoldType> auto cdt::MoveStrategy< Strategies::MOVE_ALWAYS, ManifoldType >::get_attempted () const inline nodiscard
Returns
The MoveTracker of attempted moves
Definition at line 156 of file Move_always.hpp.
References m_command_results.
get_failed()
template<typename ManifoldType> auto cdt::MoveStrategy< Strategies::MOVE_ALWAYS, ManifoldType >::get_failed () const inline nodiscard
Returns
The array of failed moves
Definition at line 164 of file Move_always.hpp.
References m_command_results.
get_succeeded()
template<typename ManifoldType> auto cdt::MoveStrategy< Strategies::MOVE_ALWAYS, ManifoldType >::get_succeeded () const inline nodiscard
Returns
The MoveTracker of successful moves
Definition at line 160 of file Move_always.hpp.
References m_command_results.
operator()()
template<typename ManifoldType> auto cdt::MoveStrategy< Strategies::MOVE_ALWAYS, ManifoldType >::operator() (ManifoldType const & t_manifold) -> ManifoldType inline
Execute a fresh run while continuing the owned random stream.
Counters and checkpoint events are replaced only after the invocation completes.
Definition at line 169 of file Move_always.hpp.
References m_cadence, m_checkpoint_events, m_command_results, m_write_files, seed(), and stream().
passes()
template<typename ManifoldType> auto cdt::MoveStrategy< Strategies::MOVE_ALWAYS, ManifoldType >::passes () const inline nodiscard noexcept
Returns
The number of passes made on a triangulation
Definition at line 136 of file Move_always.hpp.
References m_cadence.
print_results() [1/2]
template<typename ManifoldType> void cdt::MoveStrategy< Strategies::MOVE_ALWAYS, ManifoldType >::print_results () const inline
Display results of the latest completed invocation.
Definition at line 196 of file Move_always.hpp.
References m_command_results, and print_results().
Referenced by print_results().
print_results() [2/2]
template<typename ManifoldType> void cdt::MoveStrategy< Strategies::MOVE_ALWAYS, ManifoldType >::print_results (CommandResults const & results) inline static private
Definition at line 67 of file Move_always.hpp.
seed()
template<typename ManifoldType> auto cdt::MoveStrategy< Strategies::MOVE_ALWAYS, ManifoldType >::seed () const inline nodiscard noexcept
Returns
The effective root seed used for this run.
Definition at line 147 of file Move_always.hpp.
References m_random.
Referenced by MoveStrategy(), and operator()().
stream()
template<typename ManifoldType> auto cdt::MoveStrategy< Strategies::MOVE_ALWAYS, ManifoldType >::stream () const inline nodiscard noexcept
Returns
The PCG stream selector used for this run.
Definition at line 150 of file Move_always.hpp.
References m_random.
Referenced by operator()().
writes_files()
template<typename ManifoldType> auto cdt::MoveStrategy< Strategies::MOVE_ALWAYS, ManifoldType >::writes_files () const inline nodiscard noexcept
Returns
Whether the strategy writes checkpoint triangulation files.
Definition at line 153 of file Move_always.hpp.
References m_write_files.
Member Data Documentation
m_cadence
template<typename ManifoldType> MoveRunCadence cdt::MoveStrategy< Strategies::MOVE_ALWAYS, ManifoldType >::m_cadence private
Positive pass and checkpoint cadence.
Definition at line 35 of file Move_always.hpp.
Referenced by MoveStrategy(), checkpoint(), operator()(), and passes().
m_checkpoint_events
template<typename ManifoldType> Int_precision cdt::MoveStrategy< Strategies::MOVE_ALWAYS, ManifoldType >::m_checkpoint_events {} private
Checkpoint events from the latest completed invocation.
Definition at line 47 of file Move_always.hpp.
Referenced by checkpoint_events(), and operator()().
m_command_results
template<typename ManifoldType> CommandResults cdt::MoveStrategy< Strategies::MOVE_ALWAYS, ManifoldType >::m_command_results private
Command counters from the latest completed invocation.
Definition at line 44 of file Move_always.hpp.
Referenced by get_attempted(), get_failed(), get_succeeded(), operator()(), and print_results().
m_random
template<typename ManifoldType> cdt::Random cdt::MoveStrategy< Strategies::MOVE_ALWAYS, ManifoldType >::m_random private
Run-owned random stream used for move selection and site ordering.
Definition at line 38 of file Move_always.hpp.
Referenced by MoveStrategy(), seed(), and stream().
m_write_files
template<typename ManifoldType> bool cdt::MoveStrategy< Strategies::MOVE_ALWAYS, ManifoldType >::m_write_files {true} private
Whether checkpoint triangulation files may be written.
Definition at line 41 of file Move_always.hpp.
Referenced by MoveStrategy(), operator()(), and writes_files().
The documentation for this class was generated from the following file:
include/Move_always.hpp