CDT++: MoveStrategy< Strategies::MOVE_ALWAYS, ManifoldType > Class Template Reference
MoveStrategy< Strategies::MOVE_ALWAYS, ManifoldType > Class Template Reference
The Move Always algorithm.
#include <Move_always.hpp>
Public Member Functions
MoveStrategy ()=default
Default ctor.
MoveStrategy (Int_precision const t_number_of_passes, Int_precision const t_checkpoint)
Constructor for MoveAlways.
MoveStrategy (Int_precision const t_number_of_passes, Int_precision const t_checkpoint, cdt::Random random)
Construct a MoveAlways run from an owned PCG stream.
MoveStrategy (Int_precision const t_number_of_passes, Int_precision const t_checkpoint, cdt::Random_seed const seed)
Construct a replayable MoveAlways run from an explicit seed.
auto checkpoint () const
auto get_attempted () const
auto get_failed () const
auto get_succeeded () const
auto operator() (ManifoldType const &t_manifold) -> ManifoldType
Call operator.
auto passes () const
void print_results ()
Display results of run.
auto seed () const noexcept
Private Types
using Counter = move_tracker::MoveTracker<ManifoldType>
Private Attributes
Counter m_attempted_moves
The number of moves that were attempted by a MoveCommand.
Int_precision m_checkpoint {1}
The number of passes before a checkpoint.
Counter m_failed_moves
The number of moves that a MoveCommand failed to make due to an error.
Int_precision m_passes {1}
The number of move passes executed by the algorithm.
cdt::Random m_random
Run-owned random stream used for move selection and site ordering.
Counter m_successful_moves
The number of moves that succeeded in the MoveCommand.
Detailed Description
template<typename ManifoldType>
requires (ManifoldType::dimension == 3)
class MoveStrategy< Strategies::MOVE_ALWAYS, ManifoldType >
The Move Always algorithm.
Definition at line 25 of file Move_always.hpp.
Member Typedef Documentation
Counter
template<typename ManifoldType> using MoveStrategy< Strategies::MOVE_ALWAYS, ManifoldType >::Counter = move_tracker::MoveTracker<ManifoldType> private
Definition at line 27 of file Move_always.hpp.
Constructor & Destructor Documentation
MoveStrategy() [1/3]
template<typename ManifoldType> MoveStrategy< Strategies::MOVE_ALWAYS, ManifoldType >::MoveStrategy (Int_precision const t_number_of_passes, Int_precision const t_checkpoint) inline
Constructor for MoveAlways.
Parameters
t_number_of_passes Number of passes to run
t_checkpoint Number of passes per checkpoint
Definition at line 59 of file Move_always.hpp.
References MoveStrategy().
MoveStrategy() [2/3]
template<typename ManifoldType> MoveStrategy< Strategies::MOVE_ALWAYS, ManifoldType >::MoveStrategy (Int_precision const t_number_of_passes, Int_precision const t_checkpoint, cdt::Random_seed const seed) inline
Construct a replayable MoveAlways run from an explicit seed.
Definition at line 65 of file Move_always.hpp.
References MoveStrategy(), and seed().
MoveStrategy() [3/3]
template<typename ManifoldType> MoveStrategy< Strategies::MOVE_ALWAYS, ManifoldType >::MoveStrategy (Int_precision const t_number_of_passes, Int_precision const t_checkpoint, cdt::Random random) inline
Construct a MoveAlways run from an owned PCG stream.
Definition at line 72 of file Move_always.hpp.
References m_checkpoint, m_passes, and m_random.
Member Function Documentation
checkpoint()
template<typename ManifoldType> auto MoveStrategy< Strategies::MOVE_ALWAYS, ManifoldType >::checkpoint () const inline nodiscard
Returns
The number of passes per checkpoint
Definition at line 94 of file Move_always.hpp.
References m_checkpoint.
get_attempted()
template<typename ManifoldType> auto MoveStrategy< Strategies::MOVE_ALWAYS, ManifoldType >::get_attempted () const inline
Returns
The MoveTracker of attempted moves
Definition at line 100 of file Move_always.hpp.
References m_attempted_moves.
get_failed()
template<typename ManifoldType> auto MoveStrategy< Strategies::MOVE_ALWAYS, ManifoldType >::get_failed () const inline
Returns
The array of failed moves
Definition at line 106 of file Move_always.hpp.
References m_failed_moves.
get_succeeded()
template<typename ManifoldType> auto MoveStrategy< Strategies::MOVE_ALWAYS, ManifoldType >::get_succeeded () const inline
Returns
The MoveTracker of successful moves
Definition at line 103 of file Move_always.hpp.
References m_successful_moves.
operator()()
template<typename ManifoldType> auto MoveStrategy< Strategies::MOVE_ALWAYS, ManifoldType >::operator() (ManifoldType const & t_manifold) -> ManifoldType inline
Call operator.
Definition at line 109 of file Move_always.hpp.
References MoveCommand< ManifoldType, ExpectedType >::enqueue(), MoveCommand< ManifoldType, ExpectedType >::execute(), MoveCommand< ManifoldType, ExpectedType >::get_attempted(), MoveCommand< ManifoldType, ExpectedType >::get_const_results(), MoveCommand< ManifoldType, ExpectedType >::get_failed(), MoveCommand< ManifoldType, ExpectedType >::get_results(), MoveCommand< ManifoldType, ExpectedType >::get_succeeded(), m_attempted_moves, m_checkpoint, m_failed_moves, m_passes, m_random, m_successful_moves, print_results(), and MoveCommand< ManifoldType, ExpectedType >::reset_counters().
passes()
template<typename ManifoldType> auto MoveStrategy< Strategies::MOVE_ALWAYS, ManifoldType >::passes () const inline nodiscard
Returns
The number of passes made on a triangulation
Definition at line 91 of file Move_always.hpp.
References m_passes.
print_results()
template<typename ManifoldType> void MoveStrategy< Strategies::MOVE_ALWAYS, ManifoldType >::print_results () inline
Display results of run.
Definition at line 160 of file Move_always.hpp.
References m_attempted_moves, m_failed_moves, and m_successful_moves.
Referenced by operator()().
seed()
template<typename ManifoldType> auto MoveStrategy< Strategies::MOVE_ALWAYS, ManifoldType >::seed () const inline nodiscard noexcept
Returns
The effective root seed used for this run.
Definition at line 97 of file Move_always.hpp.
References m_random.
Referenced by MoveStrategy().
Member Data Documentation
m_attempted_moves
template<typename ManifoldType> Counter MoveStrategy< Strategies::MOVE_ALWAYS, ManifoldType >::m_attempted_moves private
The number of moves that were attempted by a MoveCommand.
Definition at line 43 of file Move_always.hpp.
Referenced by get_attempted(), operator()(), and print_results().
m_checkpoint
template<typename ManifoldType> Int_precision MoveStrategy< Strategies::MOVE_ALWAYS, ManifoldType >::m_checkpoint {1} private
The number of passes before a checkpoint.
Each checkpoint writes a file containing the current triangulation.
Definition at line 37 of file Move_always.hpp.
Referenced by MoveStrategy(), checkpoint(), and operator()().
m_failed_moves
template<typename ManifoldType> Counter MoveStrategy< Strategies::MOVE_ALWAYS, ManifoldType >::m_failed_moves private
The number of moves that a MoveCommand failed to make due to an error.
Definition at line 50 of file Move_always.hpp.
Referenced by get_failed(), operator()(), and print_results().
m_passes
template<typename ManifoldType> Int_precision MoveStrategy< Strategies::MOVE_ALWAYS, ManifoldType >::m_passes {1} private
The number of move passes executed by the algorithm.
Each move pass makes a number of attempts equal to the number of simplices in the triangulation.
Definition at line 32 of file Move_always.hpp.
Referenced by MoveStrategy(), operator()(), and passes().
m_random
template<typename ManifoldType> cdt::Random MoveStrategy< Strategies::MOVE_ALWAYS, ManifoldType >::m_random private
Run-owned random stream used for move selection and site ordering.
Definition at line 40 of file Move_always.hpp.
Referenced by MoveStrategy(), operator()(), and seed().
m_successful_moves
template<typename ManifoldType> Counter MoveStrategy< Strategies::MOVE_ALWAYS, ManifoldType >::m_successful_moves private
The number of moves that succeeded in the MoveCommand.
Definition at line 46 of file Move_always.hpp.
Referenced by get_succeeded(), operator()(), and print_results().
The documentation for this class was generated from the following file:
include/Move_always.hpp