CDT++: move_tracker::MoveTracker< ManifoldType > Class Template Reference
move_tracker::MoveTracker< ManifoldType > Class Template Reference
The data and methods to track ergodic moves.
#include <Move_tracker.hpp>
Public Member Functions
auto four_four_moves () -> auto &
Write access to (4,4) moves.
auto four_four_moves () const
Read access to (4,4) moves.
auto moves_view () const
Get a view of the moves.
auto operator+= (MoveTracker const &rhs) -> MoveTracker &
The += operator for MoveTracker.
auto operator[] (gsl::index index) -> auto &
The [] operator for MoveTracker.
auto operator[] (move_type const move) -> auto &
The [] operator for MoveTracker.
auto operator[] (move_type const move) const -> auto &
The [] operator for a read-only MoveTracker.
void reset ()
Reset all moves counts to zero.
auto six_two_moves () -> auto &
Write access to (6,2) moves.
auto six_two_moves () const
Read access to (6,2) moves.
auto size () const noexcept
Container size.
auto three_two_moves () -> auto &
Write access to (3,2) moves.
auto three_two_moves () const
Read access to (3,2) moves.
auto total () const noexcept
Total moves.
auto two_six_moves () -> auto &
Write access to (2,6) moves.
auto two_six_moves () const
Read access to (2,6) moves.
auto two_three_moves () -> auto &
Write access to (2,3) moves.
auto two_three_moves () const
Read access to (2,3) moves.
Private Types
using Container = std::array< Int_precision, NUMBER_OF_3D_MOVES >
Private Attributes
Container moves = {0}
Detailed Description
template<typename ManifoldType>
requires (ManifoldType::dimension == 3)
class move_tracker::MoveTracker< ManifoldType >
The data and methods to track ergodic moves.
Template Parameters
ManifoldType The type of manifold on which moves are made
Definition at line 84 of file Move_tracker.hpp.
Member Typedef Documentation
Container
template<typename ManifoldType > using move_tracker::MoveTracker< ManifoldType >::Container = std::array<Int_precision, NUMBER_OF_3D_MOVES> private
Definition at line 86 of file Move_tracker.hpp.
Member Function Documentation
four_four_moves() [1/2]
template<typename ManifoldType > auto move_tracker::MoveTracker< ManifoldType >::four_four_moves () -> auto& inline
Write access to (4,4) moves.
Returns
Reference to number of (4,4) moves
Definition at line 204 of file Move_tracker.hpp.
Referenced by MoveCommand< ManifoldType, ExpectedType, FunctionType >::print_attempts(), MoveCommand< ManifoldType, ExpectedType, FunctionType >::print_errors(), MoveStrategy< Strategies::METROPOLIS, ManifoldType >::print_results(), MoveStrategy< Strategies::MOVE_ALWAYS, ManifoldType >::print_results(), and MoveCommand< ManifoldType, ExpectedType, FunctionType >::print_successful().
four_four_moves() [2/2]
template<typename ManifoldType > auto move_tracker::MoveTracker< ManifoldType >::four_four_moves () const inline
Read access to (4,4) moves.
Returns
Value of number of (4,4) moves
Definition at line 210 of file Move_tracker.hpp.
moves_view()
template<typename ManifoldType > auto move_tracker::MoveTracker< ManifoldType >::moves_view () const inline
Get a view of the moves.
Returns
Read-only container of moves
Definition at line 95 of file Move_tracker.hpp.
Referenced by MoveCommand< ManifoldType, ExpectedType, FunctionType >::print_errors().
operator+=()
template<typename ManifoldType > auto move_tracker::MoveTracker< ManifoldType >::operator+= (MoveTracker< ManifoldType > const & rhs) -> MoveTracker& inline
The += operator for MoveTracker.
Parameters
rhs The MoveTracker to be added
Returns
The sum of the individual elements of the MoveTrackers
Definition at line 126 of file Move_tracker.hpp.
operator[]() [1/3]
template<typename ManifoldType > auto move_tracker::MoveTracker< ManifoldType >::operator[] (gsl::index index) -> auto& inline
The [] operator for MoveTracker.
Parameters
index The index of the element to be accessed
Returns
The number of moves at the index
Definition at line 102 of file Move_tracker.hpp.
operator[]() [2/3]
template<typename ManifoldType > auto move_tracker::MoveTracker< ManifoldType >::operator[] (move_type const move) -> auto& inline
The [] operator for MoveTracker.
Parameters
move The move type to be accessed
Returns
The number of moves of that type
Definition at line 110 of file Move_tracker.hpp.
References move_tracker::as_integer().
operator[]() [3/3]
template<typename ManifoldType > auto move_tracker::MoveTracker< ManifoldType >::operator[] (move_type const move) const -> auto& inline
The [] operator for a read-only MoveTracker.
Parameters
move The move type to be accessed
Returns
The number of moves of that type
Definition at line 118 of file Move_tracker.hpp.
References move_tracker::as_integer().
reset()
template<typename ManifoldType > void move_tracker::MoveTracker< ManifoldType >::reset () inline
Reset all moves counts to zero.
Definition at line 213 of file Move_tracker.hpp.
Referenced by MoveStrategy< Strategies::METROPOLIS, ManifoldType >::operator()(), MoveStrategy< Strategies::MOVE_ALWAYS, ManifoldType >::operator()(), and MoveCommand< ManifoldType, ExpectedType, FunctionType >::reset_counters().
six_two_moves() [1/2]
template<typename ManifoldType > auto move_tracker::MoveTracker< ManifoldType >::six_two_moves () -> auto& inline
Write access to (6,2) moves.
Returns
Reference to number of (6,2) moves
Definition at line 192 of file Move_tracker.hpp.
Referenced by MoveCommand< ManifoldType, ExpectedType, FunctionType >::print_attempts(), MoveCommand< ManifoldType, ExpectedType, FunctionType >::print_errors(), MoveStrategy< Strategies::METROPOLIS, ManifoldType >::print_results(), MoveStrategy< Strategies::MOVE_ALWAYS, ManifoldType >::print_results(), and MoveCommand< ManifoldType, ExpectedType, FunctionType >::print_successful().
six_two_moves() [2/2]
template<typename ManifoldType > auto move_tracker::MoveTracker< ManifoldType >::six_two_moves () const inline
Read access to (6,2) moves.
Returns
Value of number of (6,2) moves
Definition at line 198 of file Move_tracker.hpp.
size()
template<typename ManifoldType > auto move_tracker::MoveTracker< ManifoldType >::size () const inline noexcept
Container size.
Returns
The size of the container of moves
Definition at line 148 of file Move_tracker.hpp.
three_two_moves() [1/2]
template<typename ManifoldType > auto move_tracker::MoveTracker< ManifoldType >::three_two_moves () -> auto& inline
Write access to (3,2) moves.
Returns
Reference to number of (3,2) moves
Definition at line 168 of file Move_tracker.hpp.
Referenced by MoveCommand< ManifoldType, ExpectedType, FunctionType >::print_attempts(), MoveCommand< ManifoldType, ExpectedType, FunctionType >::print_errors(), MoveStrategy< Strategies::METROPOLIS, ManifoldType >::print_results(), MoveStrategy< Strategies::MOVE_ALWAYS, ManifoldType >::print_results(), and MoveCommand< ManifoldType, ExpectedType, FunctionType >::print_successful().
three_two_moves() [2/2]
template<typename ManifoldType > auto move_tracker::MoveTracker< ManifoldType >::three_two_moves () const inline
Read access to (3,2) moves.
Returns
Value of number of (3,2) moves
Definition at line 174 of file Move_tracker.hpp.
total()
template<typename ManifoldType > auto move_tracker::MoveTracker< ManifoldType >::total () const inline noexcept
Total moves.
Returns
The total number of moves in the MoveTracker
Definition at line 139 of file Move_tracker.hpp.
Referenced by MoveStrategy< Strategies::METROPOLIS, ManifoldType >::CalculateA1(), and MoveStrategy< Strategies::METROPOLIS, ManifoldType >::print_results().
two_six_moves() [1/2]
template<typename ManifoldType > auto move_tracker::MoveTracker< ManifoldType >::two_six_moves () -> auto& inline
Write access to (2,6) moves.
Returns
Reference to number of (2,6) moves
Definition at line 180 of file Move_tracker.hpp.
Referenced by MoveCommand< ManifoldType, ExpectedType, FunctionType >::print_attempts(), MoveCommand< ManifoldType, ExpectedType, FunctionType >::print_errors(), MoveStrategy< Strategies::METROPOLIS, ManifoldType >::print_results(), MoveStrategy< Strategies::MOVE_ALWAYS, ManifoldType >::print_results(), and MoveCommand< ManifoldType, ExpectedType, FunctionType >::print_successful().
two_six_moves() [2/2]
template<typename ManifoldType > auto move_tracker::MoveTracker< ManifoldType >::two_six_moves () const inline
Read access to (2,6) moves.
Returns
Value of number of (2,6) moves
Definition at line 186 of file Move_tracker.hpp.
two_three_moves() [1/2]
template<typename ManifoldType > auto move_tracker::MoveTracker< ManifoldType >::two_three_moves () -> auto& inline
Write access to (2,3) moves.
Returns
Reference to number of (2,3) moves
Definition at line 156 of file Move_tracker.hpp.
Referenced by MoveCommand< ManifoldType, ExpectedType, FunctionType >::print_attempts(), MoveCommand< ManifoldType, ExpectedType, FunctionType >::print_errors(), MoveStrategy< Strategies::METROPOLIS, ManifoldType >::print_results(), MoveStrategy< Strategies::MOVE_ALWAYS, ManifoldType >::print_results(), and MoveCommand< ManifoldType, ExpectedType, FunctionType >::print_successful().
two_three_moves() [2/2]
template<typename ManifoldType > auto move_tracker::MoveTracker< ManifoldType >::two_three_moves () const inline
Read access to (2,3) moves.
Returns
Value of number of (2,3) moves
Definition at line 162 of file Move_tracker.hpp.
Member Data Documentation
moves
template<typename ManifoldType > Container move_tracker::MoveTracker< ManifoldType >::moves = {0} private
Definition at line 88 of file Move_tracker.hpp.
The documentation for this class was generated from the following file:
include/Move_tracker.hpp