CDT++: cdt::MoveStrategy< Strategies::METROPOLIS, ManifoldType > Class Template Reference
cdt::MoveStrategy< Strategies::METROPOLIS, ManifoldType > Class Template Reference
Metropolis-Hastings algorithm strategy.
#include <Metropolis.hpp>
Public Member Functions
MoveStrategy ()
Construct a default strategy on the named transition stream.
MoveStrategy (long double const Alpha, long double const K, long double const Lambda, Int_precision const passes, Int_precision const checkpoint, bool const write_files, cdt::Random random, std::optional< utilities::Reproducibility_metadata > reproducibility=std::nullopt)
Construct a run from an already selected PCG stream.
MoveStrategy (long double const Alpha, long double const K, long double const Lambda, Int_precision const passes, Int_precision const checkpoint, bool const write_files, std::uint64_t const seed)
Construct a replayable run with an explicit RNG seed.
MoveStrategy (long double const Alpha, long double const K, long double const Lambda, Int_precision const passes, Int_precision const checkpoint, bool const write_files=true)
Metropolis function object constructor.
auto acceptance_probability (Geometry< ManifoldType::dimension > const &current, Geometry< ManifoldType::dimension > const &proposed, move_tracker::move_type const move) const -> mpfr_values::Value
auto Alpha () const noexcept
auto attempt_transition (ManifoldType &current, move_tracker::move_type const move, long double const trial_value) -> bool
Attempt and immediately resolve one Markov transition.
auto CalculateA2 (Geometry< ManifoldType::dimension > const &current, Geometry< ManifoldType::dimension > const &proposed) const -> mpfr_values::Value
Calculate the action factor \(e^{S(T)-S(T')}\).
auto checkpoint () const noexcept
auto get_accepted () const
auto get_attempted () const
auto get_failed () const
auto get_geometry () const noexcept -> Geometry< ManifoldType::dimension > const &
auto get_proposed () const
auto get_rejected () const
auto get_succeeded () const
void initialize (ManifoldType const &manifold)
Initialize the cached action geometry from the canonical manifold.
auto K () const noexcept
auto Lambda () const noexcept
auto operator() (ManifoldType const &t_manifold) -> ManifoldType
Run sequential Metropolis-Hastings passes on a manifold.
auto passes () const noexcept
void print_results ()
Display results of run.
auto reproducibility_metadata (ManifoldType const &manifold, utilities::Artifact_kind const artifact, Int_precision const completed_passes) const -> utilities::Reproducibility_metadata
Materialize output provenance for the supplied canonical state.
auto seed () const noexcept
auto stream () const noexcept
auto transition_count () const noexcept
auto transition_trace () const noexcept
auto writes_files () const noexcept
Static Public Member Functions
static auto CalculateA1 (Geometry< ManifoldType::dimension > const &current, Geometry< ManifoldType::dimension > const &proposed, move_tracker::move_type const move) -> mpfr_values::Value
Calculate the Hastings reverse-to-forward proposal ratio.
static auto proposal_probability (Geometry< ManifoldType::dimension > const &geometry, move_tracker::move_type const move) -> mpfr_values::Value
static auto constexpr proposal_site_count (Geometry< ManifoldType::dimension > const &geometry, move_tracker::move_type const move) noexcept -> Int_precision
static auto constexpr reverse_move (move_tracker::move_type const move) noexcept -> move_tracker::move_type
Private Types
using Counter = move_tracker::MoveTracker<ManifoldType>
enum class Transition_outcome : std::uint8_t { CANDIDATE_FAILED , ACCEPTED , REJECTED }
Private Member Functions
auto propose_candidate (ManifoldType const &current, move_tracker::move_type const move) -> std::expected< ManifoldType, std::string >
void record_transition (move_tracker::move_type const move, Transition_outcome const outcome) noexcept
Private Attributes
Counter m_accepted_moves
The number of proposals committed as state transitions.
long double m_Alpha {}
The length of the timelike edges.
Counter m_attempted_moves
The number of proposal sites whose construction was attempted.
Int_precision m_checkpoint {1}
The number of passes before a checkpoint.
Counter m_failed_moves
The number of inapplicable or invalid candidate constructions.
cdt::Random m_generator
Run-owned random engine used for move, site, and acceptance draws.
Geometry< ManifoldType::dimension > m_geometry
The current geometry of the manifold.
long double m_K {}
\(K=\frac{1}{8\pi G_{N}}\).
long double m_Lambda {}
\(\lambda=\frac{\Lambda}{8\pi G_{N}}\) where \(\Lambda\) is the cosmological constant
Int_precision m_passes {1}
The number of move passes executed by the algorithm.
Counter m_proposed_moves
The number of move types and raw sites proposed.
Counter m_rejected_moves
The number of explicit self-transitions.
utilities::Reproducibility_metadata m_reproducibility
Immutable run provenance, refreshed with state at each output.
Counter m_succeeded_moves
The number of attempts that produced a valid candidate manifold.
std::uint64_t m_transition_count {}
Number of transition records incorporated into the fingerprint.
std::uint64_t m_transition_trace {14695981039346656037ULL}
Compact deterministic fingerprint of ordered transition outcomes.
bool m_write_files {true}
Whether checkpoint and final triangulation files may be written.
Detailed Description
template<typename ManifoldType>
requires (ManifoldType::dimension == 3)
class cdt::MoveStrategy< Strategies::METROPOLIS, ManifoldType >
Metropolis-Hastings algorithm strategy.
The Metropolis-Hastings algorithm is a Markov Chain Monte Carlo method. For target weight \(\pi(T)\propto e^{-S(T)}\), a proposal from triangulation \(T\) to \(T'\) is accepted with probability:
\[\min\left(1, e^{S(T)-S(T')} \frac{q(T\mid T')}{q(T'\mid T)}\right).\]
The proposal-ratio construction follows the Hastings transition rule; see Metropolis-Hastings algorithmMetropolis-Hastings algorithm.
Template Parameters
ManifoldType The type of Manifold on which to apply the algorithm
Definition at line 51 of file Metropolis.hpp.
Member Typedef Documentation
Counter
template<typename ManifoldType> using cdt::MoveStrategy< Strategies::METROPOLIS, ManifoldType >::Counter = move_tracker::MoveTracker<ManifoldType> private
Definition at line 53 of file Metropolis.hpp.
Member Enumeration Documentation
Transition_outcome
template<typename ManifoldType> enum class cdt::MoveStrategy< Strategies::METROPOLIS, ManifoldType >::Transition_outcome : std::uint8_t strong private
Definition at line 117 of file Metropolis.hpp.
Constructor & Destructor Documentation
MoveStrategy() [1/4]
template<typename ManifoldType> cdt::MoveStrategy< Strategies::METROPOLIS, ManifoldType >::MoveStrategy () inline
Construct a default strategy on the named transition stream.
Definition at line 138 of file Metropolis.hpp.
References m_generator, and m_reproducibility.
Referenced by MoveStrategy(), and MoveStrategy().
MoveStrategy() [2/4]
template<typename ManifoldType> cdt::MoveStrategy< Strategies::METROPOLIS, ManifoldType >::MoveStrategy (long double const Alpha, long double const K, long double const Lambda, Int_precision const passes, Int_precision const checkpoint, bool const write_files = true) inline
Metropolis function object constructor.
Setup of runtime job parameters.
Parameters
Alpha \(\alpha\) is the timelike edge length.
K \(k=\frac{1}{8\pi G_{Newton}}\)
Lambda \(\lambda=k*\Lambda\) where \(\Lambda\) is the Cosmological constant.
passes Number of passes of ergodic moves on triangulation.
checkpoint Print/write output for every n=checkpoint passes.
write_files Whether checkpoints may write triangulation files.
Definition at line 153 of file Metropolis.hpp.
References MoveStrategy(), Alpha(), checkpoint(), K(), Lambda(), and passes().
MoveStrategy() [3/4]
template<typename ManifoldType> cdt::MoveStrategy< Strategies::METROPOLIS, ManifoldType >::MoveStrategy (long double const Alpha, long double const K, long double const Lambda, Int_precision const passes, Int_precision const checkpoint, bool const write_files, cdt::Random random, std::optional< utilities::Reproducibility_metadata > reproducibility = std::nullopt) inline
Construct a run from an already selected PCG stream.
Seed, transition-stream, action, and cadence provenance are derived from the actual constructor arguments. Caller metadata supplies initialization and requested-state context only.
Definition at line 171 of file Metropolis.hpp.
References Alpha(), checkpoint(), K(), Lambda(), m_Alpha, m_checkpoint, m_generator, m_K, m_Lambda, m_passes, m_reproducibility, m_write_files, passes(), and seed().
MoveStrategy() [4/4]
template<typename ManifoldType> cdt::MoveStrategy< Strategies::METROPOLIS, ManifoldType >::MoveStrategy (long double const Alpha, long double const K, long double const Lambda, Int_precision const passes, Int_precision const checkpoint, bool const write_files, std::uint64_t const seed) inline
Construct a replayable run with an explicit RNG seed.
Definition at line 217 of file Metropolis.hpp.
References MoveStrategy(), Alpha(), checkpoint(), K(), Lambda(), passes(), and seed().
Member Function Documentation
acceptance_probability()
template<typename ManifoldType> auto cdt::MoveStrategy< Strategies::METROPOLIS, ManifoldType >::acceptance_probability (Geometry< ManifoldType::dimension > const & current, Geometry< ManifoldType::dimension > const & proposed, move_tracker::move_type const move) const -> mpfr_values::Value inline nodiscard
Returns
\(\min(1, q(T|T')/q(T'|T)e^{S(T)-S(T')})\)
Definition at line 398 of file Metropolis.hpp.
References CalculateA1(), and CalculateA2().
Referenced by attempt_transition().
Alpha()
template<typename ManifoldType> auto cdt::MoveStrategy< Strategies::METROPOLIS, ManifoldType >::Alpha () const inline nodiscard noexcept
Returns
The length of the timelike edge
Definition at line 233 of file Metropolis.hpp.
References m_Alpha.
Referenced by MoveStrategy(), MoveStrategy(), and MoveStrategy().
attempt_transition()
template<typename ManifoldType> auto cdt::MoveStrategy< Strategies::METROPOLIS, ManifoldType >::attempt_transition (ManifoldType & current, move_tracker::move_type const move, long double const trial_value) -> bool inline
Attempt and immediately resolve one Markov transition.
Parameters
current Canonical state, updated only after a successful MH accept
move Uniformly selected move type
trial_value Uniform draw in [0,1], injectable for focused tests
Returns
True only when a valid candidate is accepted and committed
Definition at line 438 of file Metropolis.hpp.
References acceptance_probability(), m_accepted_moves, m_attempted_moves, m_failed_moves, m_geometry, m_proposed_moves, m_rejected_moves, and m_succeeded_moves.
Referenced by operator()().
CalculateA1()
template<typename ManifoldType> auto cdt::MoveStrategy< Strategies::METROPOLIS, ManifoldType >::CalculateA1 (Geometry< ManifoldType::dimension > const & current, Geometry< ManifoldType::dimension > const & proposed, move_tracker::move_type const move) -> mpfr_values::Value inline static nodiscard
Calculate the Hastings reverse-to-forward proposal ratio.
See also
Metropolis-Hastings algorithmMetropolis-Hastings algorithm
Definition at line 364 of file Metropolis.hpp.
References proposal_probability(), and reverse_move().
Referenced by acceptance_probability().
CalculateA2()
template<typename ManifoldType> auto cdt::MoveStrategy< Strategies::METROPOLIS, ManifoldType >::CalculateA2 (Geometry< ManifoldType::dimension > const & current, Geometry< ManifoldType::dimension > const & proposed) const -> mpfr_values::Value inline nodiscard
Calculate the action factor \(e^{S(T)-S(T')}\).
See also
Three-dimensional CDT actionThree-dimensional CDT action
Definition at line 382 of file Metropolis.hpp.
References m_Alpha, m_K, and m_Lambda.
Referenced by acceptance_probability().
checkpoint()
template<typename ManifoldType> auto cdt::MoveStrategy< Strategies::METROPOLIS, ManifoldType >::checkpoint () const inline nodiscard noexcept
Returns
The number of passes before writing a checkpoint file
Definition at line 245 of file Metropolis.hpp.
References m_checkpoint.
Referenced by MoveStrategy(), MoveStrategy(), and MoveStrategy().
get_accepted()
template<typename ManifoldType> auto cdt::MoveStrategy< Strategies::METROPOLIS, ManifoldType >::get_accepted () const inline
Returns
The container of accepted moves
Definition at line 292 of file Metropolis.hpp.
References m_accepted_moves.
get_attempted()
template<typename ManifoldType> auto cdt::MoveStrategy< Strategies::METROPOLIS, ManifoldType >::get_attempted () const inline
Returns
The container of attempted moves
Definition at line 298 of file Metropolis.hpp.
References m_attempted_moves.
get_failed()
template<typename ManifoldType> auto cdt::MoveStrategy< Strategies::METROPOLIS, ManifoldType >::get_failed () const inline
Returns
The container of failed moves
Definition at line 304 of file Metropolis.hpp.
References m_failed_moves.
get_geometry()
template<typename ManifoldType> auto cdt::MoveStrategy< Strategies::METROPOLIS, ManifoldType >::get_geometry () const -> Geometry< ManifoldType::dimension > const & inline nodiscard noexcept
Returns
The geometry used by the most recent acceptance decision
Definition at line 307 of file Metropolis.hpp.
References m_geometry.
get_proposed()
template<typename ManifoldType> auto cdt::MoveStrategy< Strategies::METROPOLIS, ManifoldType >::get_proposed () const inline
Returns
The container of trial moves
Definition at line 289 of file Metropolis.hpp.
References m_proposed_moves.
get_rejected()
template<typename ManifoldType> auto cdt::MoveStrategy< Strategies::METROPOLIS, ManifoldType >::get_rejected () const inline
Returns
The container of rejected moves
Definition at line 295 of file Metropolis.hpp.
References m_rejected_moves.
get_succeeded()
template<typename ManifoldType> auto cdt::MoveStrategy< Strategies::METROPOLIS, ManifoldType >::get_succeeded () const inline
Returns
The container of successful moves
Definition at line 301 of file Metropolis.hpp.
References m_succeeded_moves.
initialize()
template<typename ManifoldType> void cdt::MoveStrategy< Strategies::METROPOLIS, ManifoldType >::initialize (ManifoldType const & manifold) inline
Initialize the cached action geometry from the canonical manifold.
Definition at line 480 of file Metropolis.hpp.
References m_geometry.
Referenced by operator()().
K()
template<typename ManifoldType> auto cdt::MoveStrategy< Strategies::METROPOLIS, ManifoldType >::K () const inline nodiscard noexcept
Returns
The normalized Newton's constant
Definition at line 236 of file Metropolis.hpp.
References m_K.
Referenced by MoveStrategy(), MoveStrategy(), and MoveStrategy().
Lambda()
template<typename ManifoldType> auto cdt::MoveStrategy< Strategies::METROPOLIS, ManifoldType >::Lambda () const inline nodiscard noexcept
Returns
The normalized Cosmological constant
Definition at line 239 of file Metropolis.hpp.
References m_Lambda.
Referenced by MoveStrategy(), MoveStrategy(), and MoveStrategy().
operator()()
template<typename ManifoldType> auto cdt::MoveStrategy< Strategies::METROPOLIS, ManifoldType >::operator() (ManifoldType const & t_manifold) -> ManifoldType inline
Run sequential Metropolis-Hastings passes on a manifold.
Definition at line 484 of file Metropolis.hpp.
References attempt_transition(), initialize(), m_accepted_moves, m_attempted_moves, m_checkpoint, m_failed_moves, m_generator, m_passes, m_proposed_moves, m_rejected_moves, m_succeeded_moves, m_transition_count, m_transition_trace, m_write_files, print_results(), and reproducibility_metadata().
passes()
template<typename ManifoldType> auto cdt::MoveStrategy< Strategies::METROPOLIS, ManifoldType >::passes () const inline nodiscard noexcept
Returns
The number of passes to make
Definition at line 242 of file Metropolis.hpp.
References m_passes.
Referenced by MoveStrategy(), MoveStrategy(), and MoveStrategy().
print_results()
template<typename ManifoldType> void cdt::MoveStrategy< Strategies::METROPOLIS, ManifoldType >::print_results () inline
Display results of run.
Definition at line 542 of file Metropolis.hpp.
References m_accepted_moves, m_attempted_moves, m_failed_moves, m_proposed_moves, m_rejected_moves, and m_succeeded_moves.
Referenced by operator()().
proposal_probability()
template<typename ManifoldType> auto cdt::MoveStrategy< Strategies::METROPOLIS, ManifoldType >::proposal_probability (Geometry< ManifoldType::dimension > const & geometry, move_tracker::move_type const move) -> mpfr_values::Value inline static nodiscard
Returns
The probability of selecting a particular raw proposal site
Move types are uniform. A raw site is then uniform within its type-specific domain. Inapplicable sites remain explicit self-transitions.
Definition at line 348 of file Metropolis.hpp.
References proposal_site_count().
Referenced by CalculateA1().
proposal_site_count()
template<typename ManifoldType> auto constexpr cdt::MoveStrategy< Strategies::METROPOLIS, ManifoldType >::proposal_site_count (Geometry< ManifoldType::dimension > const & geometry, move_tracker::move_type const move) -> Int_precision inline static nodiscard constexpr noexcept
Returns
The number of raw sites from which a move type is proposed
Definition at line 328 of file Metropolis.hpp.
Referenced by proposal_probability().
propose_candidate()
template<typename ManifoldType> auto cdt::MoveStrategy< Strategies::METROPOLIS, ManifoldType >::propose_candidate (ManifoldType const & current, move_tracker::move_type const move) -> std::expected< ManifoldType, std::string > inline nodiscard private
Definition at line 410 of file Metropolis.hpp.
record_transition()
template<typename ManifoldType> void cdt::MoveStrategy< Strategies::METROPOLIS, ManifoldType >::record_transition (move_tracker::move_type const move, Transition_outcome const outcome) inline private noexcept
Definition at line 124 of file Metropolis.hpp.
reproducibility_metadata()
template<typename ManifoldType> auto cdt::MoveStrategy< Strategies::METROPOLIS, ManifoldType >::reproducibility_metadata (ManifoldType const & manifold, utilities::Artifact_kind const artifact, Int_precision const completed_passes) const -> utilities::Reproducibility_metadata inline nodiscard
Materialize output provenance for the supplied canonical state.
Definition at line 266 of file Metropolis.hpp.
References m_reproducibility, m_transition_count, and m_transition_trace.
Referenced by operator()().
reverse_move()
template<typename ManifoldType> auto constexpr cdt::MoveStrategy< Strategies::METROPOLIS, ManifoldType >::reverse_move (move_tracker::move_type const move) -> move_tracker::move_type inline static nodiscard constexpr noexcept
Returns
The inverse Pachner move
Definition at line 312 of file Metropolis.hpp.
Referenced by CalculateA1().
seed()
template<typename ManifoldType> auto cdt::MoveStrategy< Strategies::METROPOLIS, ManifoldType >::seed () const inline nodiscard noexcept
Returns
The effective root seed used for this run.
Definition at line 251 of file Metropolis.hpp.
References m_generator.
Referenced by MoveStrategy(), and MoveStrategy().
stream()
template<typename ManifoldType> auto cdt::MoveStrategy< Strategies::METROPOLIS, ManifoldType >::stream () const inline nodiscard noexcept
Returns
The PCG stream selector used for transitions.
Definition at line 254 of file Metropolis.hpp.
References m_generator.
transition_count()
template<typename ManifoldType> auto cdt::MoveStrategy< Strategies::METROPOLIS, ManifoldType >::transition_count () const inline nodiscard noexcept
Returns
Number of transitions represented by transition_trace().
Definition at line 262 of file Metropolis.hpp.
References m_transition_count.
transition_trace()
template<typename ManifoldType> auto cdt::MoveStrategy< Strategies::METROPOLIS, ManifoldType >::transition_trace () const inline nodiscard noexcept
Returns
FNV-1a fingerprint of the ordered move/outcome transition trace.
Definition at line 258 of file Metropolis.hpp.
References m_transition_trace.
writes_files()
template<typename ManifoldType> auto cdt::MoveStrategy< Strategies::METROPOLIS, ManifoldType >::writes_files () const inline nodiscard noexcept
Returns
Whether the strategy writes checkpoint triangulation files
Definition at line 248 of file Metropolis.hpp.
References m_write_files.
Member Data Documentation
m_accepted_moves
template<typename ManifoldType> Counter cdt::MoveStrategy< Strategies::METROPOLIS, ManifoldType >::m_accepted_moves private
The number of proposals committed as state transitions.
Definition at line 99 of file Metropolis.hpp.
Referenced by attempt_transition(), get_accepted(), operator()(), and print_results().
m_Alpha
template<typename ManifoldType> long double cdt::MoveStrategy< Strategies::METROPOLIS, ManifoldType >::m_Alpha {} private
The length of the timelike edges.
Definition at line 56 of file Metropolis.hpp.
Referenced by MoveStrategy(), Alpha(), and CalculateA2().
m_attempted_moves
template<typename ManifoldType> Counter cdt::MoveStrategy< Strategies::METROPOLIS, ManifoldType >::m_attempted_moves private
The number of proposal sites whose construction was attempted.
This equals proposed moves.
Definition at line 108 of file Metropolis.hpp.
Referenced by attempt_transition(), get_attempted(), operator()(), and print_results().
m_checkpoint
template<typename ManifoldType> Int_precision cdt::MoveStrategy< Strategies::METROPOLIS, ManifoldType >::m_checkpoint {1} private
The number of passes before a checkpoint.
Each checkpoint writes a file containing the current triangulation.
Definition at line 73 of file Metropolis.hpp.
Referenced by MoveStrategy(), checkpoint(), and operator()().
m_failed_moves
template<typename ManifoldType> Counter cdt::MoveStrategy< Strategies::METROPOLIS, ManifoldType >::m_failed_moves private
The number of inapplicable or invalid candidate constructions.
Definition at line 115 of file Metropolis.hpp.
Referenced by attempt_transition(), get_failed(), operator()(), and print_results().
m_generator
template<typename ManifoldType> cdt::Random cdt::MoveStrategy< Strategies::METROPOLIS, ManifoldType >::m_generator private
Initial value:
{
        cdt::Random{}.split(cdt::random_streams::transitions)}
Run-owned random engine used for move, site, and acceptance draws.
Definition at line 82 of file Metropolis.hpp.
Referenced by MoveStrategy(), MoveStrategy(), operator()(), seed(), and stream().
m_geometry
template<typename ManifoldType> Geometry<ManifoldType::dimension> cdt::MoveStrategy< Strategies::METROPOLIS, ManifoldType >::m_geometry private
The current geometry of the manifold.
Definition at line 79 of file Metropolis.hpp.
Referenced by attempt_transition(), get_geometry(), and initialize().
m_K
template<typename ManifoldType> long double cdt::MoveStrategy< Strategies::METROPOLIS, ManifoldType >::m_K {} private
\(K=\frac{1}{8\pi G_{N}}\).
Definition at line 59 of file Metropolis.hpp.
Referenced by MoveStrategy(), CalculateA2(), and K().
m_Lambda
template<typename ManifoldType> long double cdt::MoveStrategy< Strategies::METROPOLIS, ManifoldType >::m_Lambda {} private
\(\lambda=\frac{\Lambda}{8\pi G_{N}}\) where \(\Lambda\) is the cosmological constant
Definition at line 63 of file Metropolis.hpp.
Referenced by MoveStrategy(), CalculateA2(), and Lambda().
m_passes
template<typename ManifoldType> Int_precision cdt::MoveStrategy< Strategies::METROPOLIS, ManifoldType >::m_passes {1} private
The number of move passes executed by the algorithm.
Each move pass makes a number of attempts equal to the number of simplices in the triangulation.
Definition at line 68 of file Metropolis.hpp.
Referenced by MoveStrategy(), operator()(), and passes().
m_proposed_moves
template<typename ManifoldType> Counter cdt::MoveStrategy< Strategies::METROPOLIS, ManifoldType >::m_proposed_moves private
The number of move types and raw sites proposed.
This equals accepted moves + rejected moves.
Definition at line 96 of file Metropolis.hpp.
Referenced by attempt_transition(), get_proposed(), operator()(), and print_results().
m_rejected_moves
template<typename ManifoldType> Counter cdt::MoveStrategy< Strategies::METROPOLIS, ManifoldType >::m_rejected_moves private
The number of explicit self-transitions.
Includes inapplicable sites, failed candidate construction, and candidates rejected by the Metropolis-Hastings draw.
Definition at line 104 of file Metropolis.hpp.
Referenced by attempt_transition(), get_rejected(), operator()(), and print_results().
m_reproducibility
template<typename ManifoldType> utilities::Reproducibility_metadata cdt::MoveStrategy< Strategies::METROPOLIS, ManifoldType >::m_reproducibility private
Immutable run provenance, refreshed with state at each output.
Definition at line 86 of file Metropolis.hpp.
Referenced by MoveStrategy(), MoveStrategy(), and reproducibility_metadata().
m_succeeded_moves
template<typename ManifoldType> Counter cdt::MoveStrategy< Strategies::METROPOLIS, ManifoldType >::m_succeeded_moves private
The number of attempts that produced a valid candidate manifold.
A successful candidate may still be rejected by MH.
Definition at line 112 of file Metropolis.hpp.
Referenced by attempt_transition(), get_succeeded(), operator()(), and print_results().
m_transition_count
template<typename ManifoldType> std::uint64_t cdt::MoveStrategy< Strategies::METROPOLIS, ManifoldType >::m_transition_count {} private
Number of transition records incorporated into the fingerprint.
Definition at line 92 of file Metropolis.hpp.
Referenced by operator()(), reproducibility_metadata(), and transition_count().
m_transition_trace
template<typename ManifoldType> std::uint64_t cdt::MoveStrategy< Strategies::METROPOLIS, ManifoldType >::m_transition_trace {14695981039346656037ULL} private
Compact deterministic fingerprint of ordered transition outcomes.
Definition at line 89 of file Metropolis.hpp.
Referenced by operator()(), reproducibility_metadata(), and transition_trace().
m_write_files
template<typename ManifoldType> bool cdt::MoveStrategy< Strategies::METROPOLIS, ManifoldType >::m_write_files {true} private
Whether checkpoint and final triangulation files may be written.
Definition at line 76 of file Metropolis.hpp.
Referenced by MoveStrategy(), operator()(), and writes_files().
The documentation for this class was generated from the following file:
include/Metropolis.hpp