CDT++: FoliatedTriangulation< 3 > Class Template Reference
FoliatedTriangulation< 3 > Class Template Reference
3D Triangulation
#include <Foliated_triangulation.hpp>
Public Types
using squared_distance = Kernel::Compute_squared_distance_3
CGAL::squared_distance See https://doc.cgal.org/latest/Kernel_23/group__squared__distance__grp.html#ga1ff73525660a052564d33fbdd61a4f71.
Public Member Functions
FoliatedTriangulation ()=default
Default ctor.
FoliatedTriangulation (FoliatedTriangulation const &other)
Copy Constructor.
FoliatedTriangulation (FoliatedTriangulation &&other) noexcept
Move ctor.
FoliatedTriangulation (Delaunay3 triangulation)
Constructor using delaunay triangulation Pass-by-value-then-move. Delaunay3 is the ctor for the Delaunay triangulation.
FoliatedTriangulation (Int_precision const t_simplices, Int_precision const t_timeslices, double const t_initial_radius=INITIAL_RADIUS, double const t_foliation_spacing=FOLIATION_SPACING)
Constructor with parameters.
FoliatedTriangulation (Causal_vertices cv, double const t_initial_radius=INITIAL_RADIUS, double const t_foliation_spacing=FOLIATION_SPACING)
Constructor from Causal_vertices.
~FoliatedTriangulation ()=default
Default dtor.
auto check_all_cells () const -> bool
Check that all cells are correctly classified.
auto check_all_vertices () const -> bool
template<typename Triangulation >
auto check_timeslices (Triangulation &&t_triangulation) const -> std::optional< std::vector< Vertex_handle_3 >>
Check simplices for correct foliation.
auto check_vertices (std::vector< Vertex_handle_3 > const &vertices) const -> bool
Check if vertices have the correct timevalues.
template<typename VertexHandle >
auto degree (VertexHandle &&t_vertex) const
See https://doc.cgal.org/latest/TDS_3/classTriangulationDataStructure__3.html#a51fce32aa7abf3d757bcabcebd22f2fe If we have n incident edges we should have 2(n-2) incident cells Forward parameters (see F.19 of C++ Core Guidelines)
auto delaunay () -> Delaunay3 &
auto dimension () const
auto does_vertex_radius_match_timevalue (Vertex_handle_3 t_vertex) const -> bool
Check the radius of a vertex from the origin with its timevalue.
auto expected_radius (Vertex_handle_3 const &t_vertex) const -> double
Calculates the expected radial distance of a vertex given its timevalue.
auto expected_timevalue (Vertex_handle_3 const &t_vertex) const -> int
Calculate the expected timevalue for a vertex.
auto find_incorrect_cells () const -> std::vector< Cell_handle_3 >
auto find_incorrect_vertices () const -> std::vector< Vertex_handle_3 >
auto finite_cells_begin ()
auto finite_cells_end ()
void fix_vertices (std::vector< Vertex_handle_3 > const &incorrect_vertices) const
Fix vertices with wrong timevalues after foliation.
template<typename... Ts>
auto flip (Ts &&... args)
Call one of the TSD3.flip functions.
auto foliation_spacing () const
auto get_cells () const -> std::vector< Cell_handle_3 > const &
auto get_delaunay () const -> Delaunay3 const &
auto get_one_three () const -> std::vector< Cell_handle_3 > const &
auto get_spacelike_edges () const -> std::vector< Edge_handle_3 > const &
auto get_three_one () const -> std::vector< Cell_handle_3 > const &
auto get_timelike_edges () const -> std::vector< Edge_handle_3 > const &
auto get_two_two () const -> std::vector< Cell_handle_3 > const &
auto get_vertices () const -> std::vector< Vertex_handle_3 > const &
template<typename VertexHandle >
auto incident_cells (VertexHandle &&t_vh) const -> decltype(auto)
Call one of the TDS3.incident_cells functions.
template<typename... Ts>
auto incident_cells (Ts &&... args) const -> decltype(auto)
Perfect forwarding to Delaunay3.tds().incident_cells()
auto infinite_vertex () const
auto initial_radius () const
template<typename... Ts>
auto insert (Ts &&... args) -> decltype(auto)
Perfect forwarding to Delaunay3.insert() See https://doc.cgal.org/latest/Triangulation_3/group__PkgDrawTriangulation3.html#ga6a09318e75a0fb017c3ee02521f62742.
auto is_correct () const -> bool
auto is_delaunay () const -> bool
auto is_foliated () const -> bool
Verifies the triangulation is properly foliated.
template<typename VertexHandle >
auto is_infinite (VertexHandle &&t_vertex) const
auto is_initialized () const -> bool
auto is_tds_valid () const -> bool
auto is_vertex_timevalue_correct (Vertex_handle_3 const &t_vertex) const -> bool
Checks if vertex timevalue is correct.
auto max_time () const
auto min_time () const
auto N1_SL () const
auto N1_TL () const
auto N2_SL () const -> std::multimap< Int_precision, Facet_3 > const &
auto number_of_finite_cells () const
auto number_of_finite_edges () const
auto number_of_finite_facets () const
auto number_of_vertices () const
auto operator= (FoliatedTriangulation other) noexcept -> FoliatedTriangulation &
Copy/Move Assignment operator.
void print_cells () const
Print timevalues of each vertex in the cell and the resulting cell->info()
void print_edges () const
Print timevalues of each vertex in the edge and classify as timelike or spacelike.
void print_vertices () const
Print values of a vertex.
void print_volume_per_timeslice () const
Print the number of spacelike faces per timeslice.
Static Public Member Functions
static auto check_cells (std::vector< Cell_handle_3 > const &t_cells) -> bool
Check that all cells in a container are correctly classified.
static auto classify_edge (Edge_handle_3 const &t_edge, bool t_debug_flag=false) -> bool
Predicate to classify edge as timelike or spacelike.
static auto expected_cell_type (Cell_handle_3 const &t_cell, bool t_debug_flag=false)
static auto filter_cells (std::vector< Cell_handle_3 > const &t_cells, Cell_type const &t_cell_type) -> std::vector< Cell_handle_3 >
Filter simplices by Cell_type.
static void fix_cells (std::vector< Cell_handle_3 > const &t_cells)
Fix simplices with the wrong type.
static auto is_cell_type_correct (Cell_handle_3 const &t_cell) -> bool
static void print_cells (std::vector< Cell_handle_3 > const &t_cells)
Print timevalues of each vertex in the cell and the resulting cell->info()
static auto squared_radius (Vertex_handle_3 const &t_vertex) -> double
Calculate the squared radius from the origin.
Private Member Functions
auto classify_cells (std::vector< Cell_handle_3 > const &cells, bool t_debug_flag=false) const -> std::vector< Cell_handle_3 >
Classify cells.
auto collect_cells () const -> std::vector< Cell_handle_3 >
auto collect_edges () const -> std::vector< Edge_handle_3 >
auto collect_faces () const -> std::vector< Face_handle_3 >
auto collect_vertices () const -> std::vector< Vertex_handle_3 >
template<typename Triangulation >
auto fix_timeslices (Triangulation &&t_triangulation) -> bool
Fix simplices with incorrect foliation.
auto make_triangulation (Int_precision const t_simplices, Int_precision const t_timeslices, double const initial_radius=INITIAL_RADIUS, double const foliation_spacing=FOLIATION_SPACING) -> Delaunay3
Make a Delaunay Triangulation.
Static Private Member Functions
static auto filter_edges (std::vector< Edge_handle_3 > const &t_edges, bool t_is_Timelike_pred) -> std::vector< Edge_handle_3 >
Filter edges into timelike and spacelike.
static auto find_max_timevalue (std::vector< Vertex_handle_3 > const &t_vertices) -> Int_precision
Find maximum timevalues.
static auto find_min_timevalue (std::vector< Vertex_handle_3 > const &t_vertices) -> int
Find minimum timevalues.
static auto make_foliated_sphere (Int_precision const t_simplices, Int_precision const t_timeslices, double const initial_radius=INITIAL_RADIUS, double const foliation_spacing=FOLIATION_SPACING) -> Causal_vertices
Make foliated spheres.
static auto volume_per_timeslice (std::vector< Face_handle_3 > const &t_facets, bool t_debug_flag=false) -> std::multimap< Int_precision, Facet_3 >
Collect spacelike facets into a container indexed by time value.
Private Attributes
std::vector< Cell_handle_3 > m_cells
std::vector< Edge_handle_3 > m_edges
std::vector< Face_handle_3 > m_faces
double m_foliation_spacing {FOLIATION_SPACING}
double m_initial_radius {INITIAL_RADIUS}
Int_precision m_max_timevalue {0}
Int_precision m_min_timevalue {0}
std::vector< Cell_handle_3 > m_one_three
std::vector< Vertex_handle_3 > m_points
std::vector< Edge_handle_3 > m_spacelike_edges
std::multimap< Int_precision, Facet_3 > m_spacelike_facets
std::vector< Cell_handle_3 > m_three_one
std::vector< Edge_handle_3 > m_timelike_edges
Delaunay3 m_triangulation {Delaunay3{}}
std::vector< Cell_handle_3 > m_two_two
Friends
void swap (FoliatedTriangulation< 3 > &swap_from, FoliatedTriangulation< 3 > &swap_into) noexcept
Non-member swap function for Foliated Triangulations. Note that this function calls swap() from CGAL's Triangulation_3 base class, which assumes that the first triangulation is discarded after it is swapped into the second one.
Detailed Description
template<>
class FoliatedTriangulation< 3 >
3D Triangulation
Definition at line 88 of file Foliated_triangulation.hpp.
Member Typedef Documentation
squared_distance
using FoliatedTriangulation< 3 >::squared_distance = Kernel::Compute_squared_distance_3
CGAL::squared_distance See https://doc.cgal.org/latest/Kernel_23/group__squared__distance__grp.html#ga1ff73525660a052564d33fbdd61a4f71.
Returns
Square of Euclidean distance between two geometric objects
Definition at line 458 of file Foliated_triangulation.hpp.
Constructor & Destructor Documentation
FoliatedTriangulation() [1/3]
FoliatedTriangulation< 3 >::FoliatedTriangulation (Delaunay3 triangulation) inline explicit
Constructor using delaunay triangulation Pass-by-value-then-move. Delaunay3 is the ctor for the Delaunay triangulation.
Parameters
triangulation Delaunay triangulation
Definition at line 173 of file Foliated_triangulation.hpp.
FoliatedTriangulation() [2/3]
FoliatedTriangulation< 3 >::FoliatedTriangulation (Int_precision const t_simplices, Int_precision const t_timeslices, double const t_initial_radius = INITIAL_RADIUS, double const t_foliation_spacing = FOLIATION_SPACING) inline
Constructor with parameters.
Parameters
t_simplices Number of desired simplices
t_timeslices Number of desired timeslices
t_initial_radius Radius of first timeslice
t_foliation_spacing Radial separation between timeslices
Definition at line 194 of file Foliated_triangulation.hpp.
FoliatedTriangulation() [3/3]
FoliatedTriangulation< 3 >::FoliatedTriangulation (Causal_vertices cv, double const t_initial_radius = INITIAL_RADIUS, double const t_foliation_spacing = FOLIATION_SPACING) inline explicit
Constructor from Causal_vertices.
Parameters
cv Causal_vertices to place into the FoliatedTriangulation
Definition at line 218 of file Foliated_triangulation.hpp.
Member Function Documentation
check_all_cells()
auto FoliatedTriangulation< 3 >::check_all_cells () const -> bool inline
Check that all cells are correctly classified.
Returns
True if all cells are validly classified
Definition at line 733 of file Foliated_triangulation.hpp.
Referenced by Manifold< 3 >::check_simplices().
check_all_vertices()
auto FoliatedTriangulation< 3 >::check_all_vertices () const -> bool inline
Returns
True if all vertices have correct timevalues
Definition at line 538 of file Foliated_triangulation.hpp.
check_cells()
static auto FoliatedTriangulation< 3 >::check_cells (std::vector< Cell_handle_3 > const & t_cells) -> bool inline static
Check that all cells in a container are correctly classified.
Parameters
t_cells The container of cells to check
Returns
True if all cells in the container are validly classified
Definition at line 743 of file Foliated_triangulation.hpp.
Referenced by Manifold< 3 >::are_simplex_types_valid().
check_timeslices()
template<typename Triangulation > auto FoliatedTriangulation< 3 >::check_timeslices (Triangulation && t_triangulation) const -> std::optional<std::vector<Vertex_handle_3>> inline
Check simplices for correct foliation.
This function is called by fix_timeslices which is called by make_triangulation which is called by the constructor, and so must take the triangulation as an argument.
It should also be perfectly valid to call once the triangulation has been constructed; several unit tests do so.
Template Parameters
Triangulation Perfectly forwarded argument type
Parameters
t_triangulation Perfectly forwarded argument
Returns
A container of invalidly foliated vertices if they exist
Definition at line 807 of file Foliated_triangulation.hpp.
check_vertices()
auto FoliatedTriangulation< 3 >::check_vertices (std::vector< Vertex_handle_3 > const & vertices) const -> bool inline
Check if vertices have the correct timevalues.
Parameters
vertices The container of vertices to check
Returns
True if all vertices in the container have correct timevalues
Definition at line 547 of file Foliated_triangulation.hpp.
classify_cells()
auto FoliatedTriangulation< 3 >::classify_cells (std::vector< Cell_handle_3 > const & cells, bool t_debug_flag = false) const -> std::vector<Cell_handle_3> inline private
Classify cells.
Parameters
cells The container of simplices to classify
t_debug_flag Debugging info toggle
Returns
A container of simplices with Cell_type written to cell->info()
Todo:
Replace core of this function with call to expected_cell_type
Definition at line 1030 of file Foliated_triangulation.hpp.
classify_edge()
static auto FoliatedTriangulation< 3 >::classify_edge (Edge_handle_3 const & t_edge, bool t_debug_flag = false) -> bool inline static
Predicate to classify edge as timelike or spacelike.
Parameters
t_edge The Edge_handle to classify
t_debug_flag Debugging info toggle
Returns
true if timelike and false if spacelike
Definition at line 597 of file Foliated_triangulation.hpp.
collect_cells()
auto FoliatedTriangulation< 3 >::collect_cells () const -> std::vector<Cell_handle_3> inline private
Returns
Container of all the finite simplices in the triangulation
Definition at line 1008 of file Foliated_triangulation.hpp.
collect_edges()
auto FoliatedTriangulation< 3 >::collect_edges () const -> std::vector<Edge_handle_3> inline private
Returns
Container of all the finite edges in the triangulation
Definition at line 1169 of file Foliated_triangulation.hpp.
collect_faces()
auto FoliatedTriangulation< 3 >::collect_faces () const -> std::vector<Face_handle_3> inline private
Returns
Container of all the finite facets in the triangulation
Definition at line 1104 of file Foliated_triangulation.hpp.
collect_vertices()
auto FoliatedTriangulation< 3 >::collect_vertices () const -> std::vector<Vertex_handle_3> inline private
Returns
Container of all finite vertices in the triangulation
Definition at line 1209 of file Foliated_triangulation.hpp.
degree()
template<typename VertexHandle > auto FoliatedTriangulation< 3 >::degree (VertexHandle && t_vertex) const inline
See https://doc.cgal.org/latest/TDS_3/classTriangulationDataStructure__3.html#a51fce32aa7abf3d757bcabcebd22f2fe If we have n incident edges we should have 2(n-2) incident cells Forward parameters (see F.19 of C++ Core Guidelines)
Returns
The number of incident edges to a vertex
Definition at line 409 of file Foliated_triangulation.hpp.
Referenced by Manifold< 3 >::degree().
delaunay()
auto FoliatedTriangulation< 3 >::delaunay () -> Delaunay3& inline
Returns
A mutable reference to the Delaunay base class
Definition at line 275 of file Foliated_triangulation.hpp.
dimension()
auto FoliatedTriangulation< 3 >::dimension () const inline
Returns
Dimensionality of triangulation data structure (int)
Definition at line 350 of file Foliated_triangulation.hpp.
Referenced by Manifold< 3 >::dim(), and SCENARIO().
does_vertex_radius_match_timevalue()
auto FoliatedTriangulation< 3 >::does_vertex_radius_match_timevalue (Vertex_handle_3 t_vertex) const -> bool inline
Check the radius of a vertex from the origin with its timevalue.
Parameters
t_vertex The vertex to check
Returns
True if the effective radial distance squared matches timevalue squared
Definition at line 464 of file Foliated_triangulation.hpp.
References TOLERANCE.
expected_cell_type()
static auto FoliatedTriangulation< 3 >::expected_cell_type (Cell_handle_3 const & t_cell, bool t_debug_flag = false) inline static
Parameters
t_cell The simplex to check
Returns
The type of simplex
Definition at line 680 of file Foliated_triangulation.hpp.
expected_radius()
auto FoliatedTriangulation< 3 >::expected_radius (Vertex_handle_3 const & t_vertex) const -> double inline
Calculates the expected radial distance of a vertex given its timevalue.
The formula for the radius is:
\[R=I+S(t-1)\]
Where I is INITIAL_RADIUS, S is RADIAL_SEPARATION, and t is timevalue
Parameters
t_vertex The vertex to check
Returns
The expected radial distance of the vertex of that timevalue
Definition at line 499 of file Foliated_triangulation.hpp.
expected_timevalue()
auto FoliatedTriangulation< 3 >::expected_timevalue (Vertex_handle_3 const & t_vertex) const -> int inline
Calculate the expected timevalue for a vertex.
The formula for the expected timevalue is:
\[t=\frac{R-I+S}{S}\]
Where R is radius, I is INITIAL_RADIUS, and S is RADIAL_SEPARATION
Parameters
t_vertex The vertex to check
Returns
The expected timevalue of the vertex
Definition at line 528 of file Foliated_triangulation.hpp.
filter_cells()
static auto FoliatedTriangulation< 3 >::filter_cells (std::vector< Cell_handle_3 > const & t_cells, Cell_type const & t_cell_type) -> std::vector<Cell_handle_3> inline static
Filter simplices by Cell_type.
Parameters
t_cells The container of simplices to filter
t_cell_type The Cell_type predicate filter
Returns
A container of Cell_type simplices
Definition at line 646 of file Foliated_triangulation.hpp.
filter_edges()
static auto FoliatedTriangulation< 3 >::filter_edges (std::vector< Edge_handle_3 > const & t_edges, bool t_is_Timelike_pred) -> std::vector<Edge_handle_3> inline static private
Filter edges into timelike and spacelike.
Parameters
t_edges The container of edges to filter
t_is_Timelike_pred The predicate condition
Returns
A container of is_Timelike edges
Definition at line 1194 of file Foliated_triangulation.hpp.
find_incorrect_cells()
auto FoliatedTriangulation< 3 >::find_incorrect_cells () const -> std::vector<Cell_handle_3> inline
Returns
A container of incorrect cells
Definition at line 751 of file Foliated_triangulation.hpp.
find_incorrect_vertices()
auto FoliatedTriangulation< 3 >::find_incorrect_vertices () const -> std::vector<Vertex_handle_3> inline
Returns
A container of incorrect vertices
Definition at line 557 of file Foliated_triangulation.hpp.
find_max_timevalue()
static auto FoliatedTriangulation< 3 >::find_max_timevalue (std::vector< Vertex_handle_3 > const & t_vertices) -> Int_precision inline static private
Find maximum timevalues.
Parameters
t_vertices Container of vertices
Returns
The maximum timevalue
Definition at line 1228 of file Foliated_triangulation.hpp.
find_min_timevalue()
static auto FoliatedTriangulation< 3 >::find_min_timevalue (std::vector< Vertex_handle_3 > const & t_vertices) -> int inline static private
Find minimum timevalues.
Parameters
t_vertices Container of vertices
Returns
The minimum timevalue
Definition at line 1243 of file Foliated_triangulation.hpp.
finite_cells_begin()
auto FoliatedTriangulation< 3 >::finite_cells_begin () inline
Returns
An InputIterator to the beginning of the finite cells stored in https://doc.cgal.org/latest/STL_Extension/classCGAL_1_1Compact__container.html
Definition at line 285 of file Foliated_triangulation.hpp.
finite_cells_end()
auto FoliatedTriangulation< 3 >::finite_cells_end () inline
Returns
An InputIterator to the end of the finite cells stored in https://doc.cgal.org/latest/STL_Extension/classCGAL_1_1Compact__container.html
Definition at line 292 of file Foliated_triangulation.hpp.
fix_cells()
static void FoliatedTriangulation< 3 >::fix_cells (std::vector< Cell_handle_3 > const & t_cells) inline static
Fix simplices with the wrong type.
Parameters
t_cells The container of incorrect simplices
Definition at line 764 of file Foliated_triangulation.hpp.
fix_timeslices()
template<typename Triangulation > auto FoliatedTriangulation< 3 >::fix_timeslices (Triangulation && t_triangulation) -> bool inline private
Fix simplices with incorrect foliation.
This function iterates over all of the cells in the triangulation. Within each cell, it iterates over all of the vertices and reads timeslices. Validity of the cell is first checked by the is_valid() function. The foliation validity is then checked by finding maximum and minimum timeslices for all the vertices of a cell and ensuring that the difference is exactly 1. If a cell has a bad foliation, the vertex with the highest timeslice is deleted. The Delaunay triangulation is then recomputed on the remaining vertices.
Template Parameters
Triangulation Perfectly forwarded argument type
Parameters
t_triangulation Perfectly forwarded argument
Returns
True if there are no incorrectly foliated simplices
Definition at line 977 of file Foliated_triangulation.hpp.
fix_vertices()
void FoliatedTriangulation< 3 >::fix_vertices (std::vector< Vertex_handle_3 > const & incorrect_vertices) const inline
Fix vertices with wrong timevalues after foliation.
Parameters
incorrect_vertices The container of incorrect vertices
Definition at line 574 of file Foliated_triangulation.hpp.
flip()
template<typename... Ts> auto FoliatedTriangulation< 3 >::flip (Ts &&... args) inline
Call one of the TSD3.flip functions.
See https://doc.cgal.org/latest/Triangulation_3/classCGAL_1_1Triangulation__3.html#a883fed00b53cae9e85feb20230f54dd9
Template Parameters
Ts Variadic template of types of the arguments
Parameters
args Parameter pack of arguments to TDS3.flip
Returns
True if the flip occurred
Definition at line 338 of file Foliated_triangulation.hpp.
foliation_spacing()
auto FoliatedTriangulation< 3 >::foliation_spacing () const inline
Returns
The spacing between timeslices
Definition at line 401 of file Foliated_triangulation.hpp.
get_cells()
auto FoliatedTriangulation< 3 >::get_cells () const -> std::vector<Cell_handle_3> const& inline
Returns
Container of cells
Definition at line 636 of file Foliated_triangulation.hpp.
Referenced by Manifold< 3 >::is_correct(), and Manifold< 3 >::number_of_simplices().
get_delaunay()
auto FoliatedTriangulation< 3 >::get_delaunay () const -> Delaunay3 const& inline
Returns
A read-only reference to the Delaunay base class
Definition at line 278 of file Foliated_triangulation.hpp.
Referenced by Manifold< 3 >::is_edge(), Manifold< 3 >::is_vertex(), SCENARIO(), and Manifold< 3 >::update_triangulation().
get_one_three()
auto FoliatedTriangulation< 3 >::get_one_three () const -> std::vector<Cell_handle_3> const& inline
Returns
Container of (1,3) cells
Definition at line 673 of file Foliated_triangulation.hpp.
get_spacelike_edges()
auto FoliatedTriangulation< 3 >::get_spacelike_edges () const -> std::vector<Edge_handle_3> const& inline
Returns
Container of spacelike edges
Definition at line 379 of file Foliated_triangulation.hpp.
Referenced by Manifold< 3 >::get_spacelike_edges().
get_three_one()
auto FoliatedTriangulation< 3 >::get_three_one () const -> std::vector<Cell_handle_3> const& inline
Returns
Container of (3,1) cells
Definition at line 661 of file Foliated_triangulation.hpp.
get_timelike_edges()
auto FoliatedTriangulation< 3 >::get_timelike_edges () const -> std::vector<Edge_handle_3> const& inline
Returns
Container of timelike edges
Definition at line 372 of file Foliated_triangulation.hpp.
Referenced by Manifold< 3 >::get_timelike_edges().
get_two_two()
auto FoliatedTriangulation< 3 >::get_two_two () const -> std::vector<Cell_handle_3> const& inline
Returns
Container of (2,2) cells
Definition at line 667 of file Foliated_triangulation.hpp.
get_vertices()
auto FoliatedTriangulation< 3 >::get_vertices () const -> std::vector<Vertex_handle_3> const& inline
Returns
Container of vertices
Definition at line 386 of file Foliated_triangulation.hpp.
Referenced by Manifold< 3 >::get_vertices().
incident_cells() [1/2]
template<typename VertexHandle > auto FoliatedTriangulation< 3 >::incident_cells (VertexHandle && t_vh) const -> decltype(auto) inline
Call one of the TDS3.incident_cells functions.
See https://doc.cgal.org/latest/TDS_3/classTriangulationDataStructure__3.html#a93f8ab30228b2a515a5c9cdacd9d4d36
Template Parameters
VertexHandle Template parameter used to forward
Parameters
t_vh Vertex
Returns
A container of incident cells
Definition at line 423 of file Foliated_triangulation.hpp.
Referenced by Manifold< 3 >::incident_cells().
incident_cells() [2/2]
template<typename... Ts> auto FoliatedTriangulation< 3 >::incident_cells (Ts &&... args) const -> decltype(auto) inline
Perfect forwarding to Delaunay3.tds().incident_cells()
Template Parameters
Ts Variadic template used to forward
Parameters
args Parameter pack of arguments to call incident_cells()
Returns
A Cell_circulator
Definition at line 437 of file Foliated_triangulation.hpp.
infinite_vertex()
auto FoliatedTriangulation< 3 >::infinite_vertex () const inline
Returns
Returns the infinite vertex in the triangulation
Definition at line 344 of file Foliated_triangulation.hpp.
initial_radius()
auto FoliatedTriangulation< 3 >::initial_radius () const inline
Returns
The initial radius for timeslice = 1
Definition at line 398 of file Foliated_triangulation.hpp.
insert()
template<typename... Ts> auto FoliatedTriangulation< 3 >::insert (Ts &&... args) -> decltype(auto) inline
Perfect forwarding to Delaunay3.insert() See https://doc.cgal.org/latest/Triangulation_3/group__PkgDrawTriangulation3.html#ga6a09318e75a0fb017c3ee02521f62742.
Template Parameters
Ts Variadic template used to forward
Parameters
args Parameter pack of arguments to call insert()
Returns
A Vertex_handle
Definition at line 449 of file Foliated_triangulation.hpp.
is_cell_type_correct()
static auto FoliatedTriangulation< 3 >::is_cell_type_correct (Cell_handle_3 const & t_cell) -> bool inline static
Parameters
t_cell The simplex to check
Returns
True if the cell_info matches expected cell_info
Definition at line 723 of file Foliated_triangulation.hpp.
is_correct()
auto FoliatedTriangulation< 3 >::is_correct () const -> bool inline
Returns
True if the Foliated Triangulation class invariants hold
Todo:
Fix fatal error that occurs if check_all_cells() is added
Definition at line 263 of file Foliated_triangulation.hpp.
Referenced by Manifold< 3 >::is_correct().
is_delaunay()
auto FoliatedTriangulation< 3 >::is_delaunay () const -> bool inline
Returns
True if the triangulation is Delaunay
Definition at line 250 of file Foliated_triangulation.hpp.
Referenced by Manifold< 3 >::is_delaunay().
is_foliated()
auto FoliatedTriangulation< 3 >::is_foliated () const -> bool inline
Verifies the triangulation is properly foliated.
Can not be called until after Foliated_triangulation has been constructed (i.e. not in make_triangulation)
Returns
True if foliated correctly
Definition at line 244 of file Foliated_triangulation.hpp.
Referenced by Manifold< 3 >::is_foliated().
is_infinite()
template<typename VertexHandle > auto FoliatedTriangulation< 3 >::is_infinite (VertexHandle && t_vertex) const inline
Returns
If a cell or vertex contains or is the infinite vertex Forward parameters (see F.19 of C++ Core Guidelines)
Definition at line 324 of file Foliated_triangulation.hpp.
Referenced by SCENARIO().
is_initialized()
auto FoliatedTriangulation< 3 >::is_initialized () const -> bool inline
Returns
True if the Foliated Triangulation has been initialized correctly
Definition at line 269 of file Foliated_triangulation.hpp.
Referenced by SCENARIO().
is_tds_valid()
auto FoliatedTriangulation< 3 >::is_tds_valid () const -> bool inline
Returns
True if the triangulation data structure is valid
Definition at line 256 of file Foliated_triangulation.hpp.
Referenced by Manifold< 3 >::is_valid().
is_vertex_timevalue_correct()
auto FoliatedTriangulation< 3 >::is_vertex_timevalue_correct (Vertex_handle_3 const & t_vertex) const -> bool inline
Checks if vertex timevalue is correct.
Parameters
t_vertex The vertex to check
Returns
True if vertex->info() equals expected_timevalue()
Definition at line 477 of file Foliated_triangulation.hpp.
make_foliated_sphere()
static auto FoliatedTriangulation< 3 >::make_foliated_sphere (Int_precision const t_simplices, Int_precision const t_timeslices, double const initial_radius = INITIAL_RADIUS, double const foliation_spacing = FOLIATION_SPACING) -> Causal_vertices inline static private
Make foliated spheres.
Parameters
t_simplices The desired number of simplices in the triangulation
t_timeslices The desired number of timeslices in the triangulation
initial_radius The radius of the first time slice
foliation_spacing The distance between successive time slices
Returns
A container of (vertex, timevalue) pairs
Definition at line 933 of file Foliated_triangulation.hpp.
make_triangulation()
auto FoliatedTriangulation< 3 >::make_triangulation (Int_precision const t_simplices, Int_precision const t_timeslices, double const initial_radius = INITIAL_RADIUS, double const foliation_spacing = FOLIATION_SPACING) -> Delaunay3 inline private
Make a Delaunay Triangulation.
Parameters
t_simplices Number of desired simplices
t_timeslices Number of desired timeslices
initial_radius Radius of first timeslice
foliation_spacing Radial separation between timeslices
Returns
A Delaunay Triangulation
Definition at line 892 of file Foliated_triangulation.hpp.
max_time()
auto FoliatedTriangulation< 3 >::max_time () const inline
Returns
Maximum time value in triangulation
Definition at line 392 of file Foliated_triangulation.hpp.
Referenced by Manifold< 3 >::max_time().
min_time()
auto FoliatedTriangulation< 3 >::min_time () const inline
Returns
Minimum time value in triangulation
Definition at line 395 of file Foliated_triangulation.hpp.
Referenced by Manifold< 3 >::min_time().
N1_SL()
auto FoliatedTriangulation< 3 >::N1_SL () const inline
Returns
Number of spacelike edges
Definition at line 366 of file Foliated_triangulation.hpp.
Referenced by Manifold< 3 >::N1_SL().
N1_TL()
auto FoliatedTriangulation< 3 >::N1_TL () const inline
Returns
Number of timelike edges
Definition at line 360 of file Foliated_triangulation.hpp.
Referenced by Manifold< 3 >::N1_TL().
N2_SL()
auto FoliatedTriangulation< 3 >::N2_SL () const -> std::multimap<Int_precision, Facet_3> const& inline
Returns
Container of spacelike facets indexed by time value
Definition at line 353 of file Foliated_triangulation.hpp.
Referenced by Manifold< 3 >::N2_SL().
number_of_finite_cells()
auto FoliatedTriangulation< 3 >::number_of_finite_cells () const inline
Returns
Number of 3D simplices in triangulation data structure
Definition at line 298 of file Foliated_triangulation.hpp.
Referenced by Geometry< 3 >::Geometry(), and SCENARIO().
number_of_finite_edges()
auto FoliatedTriangulation< 3 >::number_of_finite_edges () const inline
Returns
Number of 1D edges in triangulation data structure
Definition at line 310 of file Foliated_triangulation.hpp.
Referenced by Manifold< 3 >::edges(), and SCENARIO().
number_of_finite_facets()
auto FoliatedTriangulation< 3 >::number_of_finite_facets () const inline
Returns
Number of 2D faces in triangulation data structure
Definition at line 304 of file Foliated_triangulation.hpp.
Referenced by Manifold< 3 >::faces(), and SCENARIO().
number_of_vertices()
auto FoliatedTriangulation< 3 >::number_of_vertices () const inline
Returns
Number of vertices in triangulation data structure
Definition at line 316 of file Foliated_triangulation.hpp.
Referenced by SCENARIO(), and Manifold< 3 >::vertices().
print_cells()
static void FoliatedTriangulation< 3 >::print_cells (std::vector< Cell_handle_3 > const & t_cells) inline static
Print timevalues of each vertex in the cell and the resulting cell->info()
Parameters
t_cells The cells to print
Definition at line 780 of file Foliated_triangulation.hpp.
squared_radius()
static auto FoliatedTriangulation< 3 >::squared_radius (Vertex_handle_3 const & t_vertex) -> double inline static
Calculate the squared radius from the origin.
Parameters
t_vertex The vertex to check
Returns
The squared radial distance of the vertex
Definition at line 509 of file Foliated_triangulation.hpp.
volume_per_timeslice()
static auto FoliatedTriangulation< 3 >::volume_per_timeslice (std::vector< Face_handle_3 > const & t_facets, bool t_debug_flag = false) -> std::multimap<Int_precision, Facet_3> inline static private
Collect spacelike facets into a container indexed by time value.
///
Parameters
t_facets A container of facets
t_debug_flag Debugging info toggle
Returns
Container with spacelike facets per timeslice
Definition at line 1127 of file Foliated_triangulation.hpp.
Friends And Related Function Documentation
swap
void swap (FoliatedTriangulation< 3 > & swap_from, FoliatedTriangulation< 3 > & swap_into) friend
Non-member swap function for Foliated Triangulations. Note that this function calls swap() from CGAL's Triangulation_3 base class, which assumes that the first triangulation is discarded after it is swapped into the second one.
Parameters
swap_from The value to be swapped from. Assumed to be discarded.
swap_into The value to be swapped into.
Definition at line 141 of file Foliated_triangulation.hpp.
Member Data Documentation
m_triangulation
Delaunay3 FoliatedTriangulation< 3 >::m_triangulation {Delaunay3{}} private
Data members initialized in order of declaration (Working Draft, Standard for C++ Programming Language, 12.6.2 section 13.3)
Definition at line 92 of file Foliated_triangulation.hpp.
The documentation for this class was generated from the following file:
include/Foliated_triangulation.hpp