CDT++: MoveStrategy< METROPOLIS, ManifoldType > Class Template Reference
MoveStrategy< METROPOLIS, ManifoldType > Class Template Reference
Metropolis-Hastings algorithm strategy.
#include <Metropolis.hpp>
Public Member Functions
MoveStrategy ()=default
Default ctor.
MoveStrategy (long double Alpha, long double K, long double Lambda, Int_precision passes, Int_precision checkpoint)
Metropolis function object constructor.
auto Alpha () const noexcept
auto CalculateA1 (move_tracker::move_type move) const noexcept
Calculate A1.
template<int dimension>
auto CalculateA2 (move_tracker::move_type move) const noexcept
Calculate A2.
catch (std::runtime_error const &RuntimeError)
auto checkpoint () const noexcept
auto get_accepted () const
auto get_attempted () const
auto get_failed () const
auto get_rejected () const
auto get_succeeded () const
auto get_trial () const
auto initialize (ManifoldType t_manifold) -> std::optional< MoveCommand< ManifoldType >> try
auto K () const noexcept
auto Lambda () const noexcept
auto operator() (ManifoldType const &t_manifold) -> ManifoldType
Call operator.
auto passes () const noexcept
void print_results ()
Display results of run.
auto try_move (move_tracker::move_type move) -> bool
Attempt a move of the selected type.
Private Attributes
move_tracker::MoveTracker< ManifoldType > m_accepted_moves
The number of moves accepted by the algorithm.
long double m_Alpha {}
The length of the timelike edges.
move_tracker::MoveTracker< ManifoldType > m_attempted_moves
The number of moves that were attempted by a MoveCommand.
Int_precision m_checkpoint {1}
The number of passes before a checkpoint.
move_tracker::MoveTracker< ManifoldType > m_failed_moves
The number of moves that a MoveCommand failed to make due to an error.
Geometry< ManifoldType::dimension > m_geometry
The current geometry of the manifold.
long double m_K {}
\(K=\frac{1}{8\pi G_{N}}\).
long double m_Lambda {}
\(\lambda=\frac{\Lambda}{8\pi G_{N}}\) where \(\Lambda\) is the cosmological constant
Int_precision m_passes {1}
The number of move passes executed by the algorithm.
move_tracker::MoveTracker< ManifoldType > m_rejected_moves
The number of moves rejected by the algorithm.
move_tracker::MoveTracker< ManifoldType > m_succeeded_moves
The number of moves that succeeded in the MoveCommand.
move_tracker::MoveTracker< ManifoldType > m_trial_moves
The number of moves the algorithm tried.
Detailed Description
template<typename ManifoldType>
class MoveStrategy< METROPOLIS, ManifoldType >
Metropolis-Hastings algorithm strategy.
The Metropolis-Hastings algorithm is a Markov Chain Monte Carlo method. The probability of making an ergodic (Pachner) move is:
\[P_{ergodic move}=a_{1}a_{2}\]
\[a_1=\frac{move[i]}{\sum\limits_{i}move[i]}\]
\[a_2=e^{\Delta S}\]
Template Parameters
ManifoldType The type of Manifold on which to apply the algorithm
Definition at line 41 of file Metropolis.hpp.
Constructor & Destructor Documentation
MoveStrategy()
template<typename ManifoldType > MoveStrategy< METROPOLIS, ManifoldType >::MoveStrategy (long double Alpha, long double K, long double Lambda, Int_precision passes, Int_precision checkpoint) inline
Metropolis function object constructor.
Setup of runtime job parameters.
Parameters
Alpha \(\alpha\) is the timelike edge length.
K \(k=\frac{1}{8\pi G_{Newton}}\)
Lambda \(\lambda=k*\Lambda\) where \(\Lambda\) is the Cosmological constant.
passes Number of passes of ergodic moves on triangulation.
checkpoint Print/write output for every n=checkpoint passes.
Definition at line 99 of file Metropolis.hpp.
Member Function Documentation
Alpha()
template<typename ManifoldType > auto MoveStrategy< METROPOLIS, ManifoldType >::Alpha () const inline noexcept
Returns
The length of the timelike edge
Definition at line 114 of file Metropolis.hpp.
CalculateA1()
template<typename ManifoldType > auto MoveStrategy< METROPOLIS, ManifoldType >::CalculateA1 (move_tracker::move_type move) const inline noexcept
Calculate A1.
Calculate the probability of making a move divided by the probability of its reverse, that is:
\[a_1=\frac{move[i]}{\sum\limits_{i}move[i]}\]
Parameters
move The type of move
Returns
\(a_1=\frac{move[i]}{\sum\limits_{i}move[i]}\)
Definition at line 153 of file Metropolis.hpp.
References PRECISION, and move_tracker::MoveTracker< ManifoldType >::total().
CalculateA2()
template<typename ManifoldType > template<int dimension> auto MoveStrategy< METROPOLIS, ManifoldType >::CalculateA2 (move_tracker::move_type move) const inline noexcept
Calculate A2.
Calculate \(a_2=e^{\Delta S}\)
Template Parameters
dimension The dimensionality of the triangulation
Parameters
move The type of move
Returns
\(a_2=e^{-\Delta S}\)
Definition at line 192 of file Metropolis.hpp.
References S3_bulk_action().
checkpoint()
template<typename ManifoldType > auto MoveStrategy< METROPOLIS, ManifoldType >::checkpoint () const inline noexcept
Returns
The number of passes before writing a checkpoint file
Definition at line 126 of file Metropolis.hpp.
get_accepted()
template<typename ManifoldType > auto MoveStrategy< METROPOLIS, ManifoldType >::get_accepted () const inline
Returns
The container of accepted moves
Definition at line 132 of file Metropolis.hpp.
get_attempted()
template<typename ManifoldType > auto MoveStrategy< METROPOLIS, ManifoldType >::get_attempted () const inline
Returns
The container of attempted moves
Definition at line 138 of file Metropolis.hpp.
get_failed()
template<typename ManifoldType > auto MoveStrategy< METROPOLIS, ManifoldType >::get_failed () const inline
Returns
The container of failed moves
Definition at line 144 of file Metropolis.hpp.
get_rejected()
template<typename ManifoldType > auto MoveStrategy< METROPOLIS, ManifoldType >::get_rejected () const inline
Returns
The container of rejected moves
Definition at line 135 of file Metropolis.hpp.
get_succeeded()
template<typename ManifoldType > auto MoveStrategy< METROPOLIS, ManifoldType >::get_succeeded () const inline
Returns
The container of successful moves
Definition at line 141 of file Metropolis.hpp.
get_trial()
template<typename ManifoldType > auto MoveStrategy< METROPOLIS, ManifoldType >::get_trial () const inline
Returns
The container of trial moves
Definition at line 129 of file Metropolis.hpp.
K()
template<typename ManifoldType > auto MoveStrategy< METROPOLIS, ManifoldType >::K () const inline noexcept
Returns
The normalized Newton's constant
Definition at line 117 of file Metropolis.hpp.
Lambda()
template<typename ManifoldType > auto MoveStrategy< METROPOLIS, ManifoldType >::Lambda () const inline noexcept
Returns
The normalized Cosmological constant
Definition at line 120 of file Metropolis.hpp.
operator()()
template<typename ManifoldType > auto MoveStrategy< METROPOLIS, ManifoldType >::operator() (ManifoldType const & t_manifold) -> ManifoldType inline
Call operator.
This makes the Metropolis class into a function object. Setup of the runtime job parameters is handled by the constructor. This () operator conducts all of the algorithmic work for Metropolis-Hastings on the manifold.
Parameters
t_manifold Manifold on which to operate
Returns
The manifold upon which the passes have been completed
Definition at line 379 of file Metropolis.hpp.
passes()
template<typename ManifoldType > auto MoveStrategy< METROPOLIS, ManifoldType >::passes () const inline noexcept
Returns
The number of passes to make
Definition at line 123 of file Metropolis.hpp.
try_move()
template<typename ManifoldType > auto MoveStrategy< METROPOLIS, ManifoldType >::try_move (move_tracker::move_type move) -> bool inline
Attempt a move of the selected type.
This function implements the core of the Metropolis-Hastings algorithm by generating a random number and comparing with the results of CalculateA1 and CalculateA2. If the move is accepted, this function calls make_move(). If not, it updates attempted_moves_.
Parameters
move The type of move
Returns
True if the move is accepted
Definition at line 283 of file Metropolis.hpp.
References generate_probability().
Member Data Documentation
m_attempted_moves
template<typename ManifoldType > move_tracker::MoveTracker<ManifoldType> MoveStrategy< METROPOLIS, ManifoldType >::m_attempted_moves private
The number of moves that were attempted by a MoveCommand.
This should equal accepted moves.
Definition at line 78 of file Metropolis.hpp.
m_checkpoint
template<typename ManifoldType > Int_precision MoveStrategy< METROPOLIS, ManifoldType >::m_checkpoint {1} private
The number of passes before a checkpoint.
Each checkpoint writes a file containing the current triangulation.
Definition at line 61 of file Metropolis.hpp.
m_passes
template<typename ManifoldType > Int_precision MoveStrategy< METROPOLIS, ManifoldType >::m_passes {1} private
The number of move passes executed by the algorithm.
Each move pass makes a number of attempts equal to the number of simplices in the triangulation.
Definition at line 56 of file Metropolis.hpp.
m_trial_moves
template<typename ManifoldType > move_tracker::MoveTracker<ManifoldType> MoveStrategy< METROPOLIS, ManifoldType >::m_trial_moves private
The number of moves the algorithm tried.
This equals accepted moves + rejected moves.
Definition at line 68 of file Metropolis.hpp.
The documentation for this class was generated from the following file:
include/Metropolis.hpp