codecov:
  token: d0630cb4-d416-4dff-95a1-7735a7f25cdc
  notify:
    require_ci_to_pass: no

coverage:
  precision: 2
  round: down
  range: "30...100"

  status:
    project:
      default:
        threshold: 3%
    patch: no
    changes: no

  notify:
      gitter:
        url: https://webhooks.gitter.im/e/c70e4d2749931f601747
        threshold: 1%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach, diff, flags, files, footer"
  behavior: default
  require_changes: false

ignore:
  - "tests/"
