var searchData=
[
  ['random_0',['Random',['../classcdt_1_1_random.html',1,'cdt::Random'],['../classcdt_1_1_random.html#a42b629b8f79ccafab3bf50e058939532',1,'cdt::Random::Random()'],['../classcdt_1_1_random.html#aedb2ffa91f84e7e29acf119dce82fcfa',1,'cdt::Random::Random(Random_seed const seed, Random_stream const stream=0)']]],
  ['random_20number_20generation_1',['Computational Geometry and Random-Number Generation',['../md__r_e_f_e_r_e_n_c_e_s.html#computational-geometry-and-random-number-generation',1,'']]],
  ['random_20number_20generators_2',['PCG random-number generators',['../md__r_e_f_e_r_e_n_c_e_s.html#pcg-random-number-generators',1,'']]],
  ['random_20runs_3',['Reproducible random runs',['../md_docs_2reproducibility.html',1,'']]],
  ['random_2ehpp_4',['Random.hpp',['../_random_8hpp.html',1,'']]],
  ['random_5felement_5',['random_element',['../_ergodic__moves__3_8hpp.html#ad8c9966d7a0fa4659201592e897487f7',1,'cdt::ergodic_moves::detail']]],
  ['read_5ffile_6',['read_file',['../_utilities_8hpp.html#ae6b1c185667fdd3dd9a9dee9a5087267',1,'cdt::utilities']]],
  ['reason_7',['reason',['../structcdt_1_1ergodic__moves_1_1_move_error.html#aaad7e1dddcfbfe480f198d6c5bcea5c1',1,'cdt::ergodic_moves::MoveError']]],
  ['record_8',['record',['../md_docs_2ergodic-moves.html#move-by-move-record',1,'Move-by-move record'],['../md_docs_2ergodic-moves.html#verification-record',1,'Verification record']]],
  ['reference_20suite_20status_9',['Current reference-suite status',['../index.html#current-reference-suite-status',1,'']]],
  ['references_10',['References',['../md_docs_2metropolis-hastings.html#references',1,'']]],
  ['references_20and_20citations_11',['References and Citations',['../md__r_e_f_e_r_e_n_c_e_s.html',1,'']]],
  ['regge_20calculus_12',['Regge calculus',['../md__r_e_f_e_r_e_n_c_e_s.html#regge-calculus',1,'']]],
  ['regge_20calculus_20and_20discrete_20action_13',['Regge Calculus and Discrete Action',['../md__r_e_f_e_r_e_n_c_e_s.html#regge-calculus-and-discrete-action',1,'']]],
  ['regression_20oracle_20scope_14',['Regression-oracle scope',['../index.html#regression-oracle-scope',1,'']]],
  ['rejected_15',['rejected',['../structcdt_1_1_move_strategy_3_01_strategies_1_1_m_e_t_r_o_p_o_l_i_s_00_01_manifold_type_01_4_1_1_run_statistics.html#a4eceef470ad07037a15b17d6f013f8d1',1,'cdt::MoveStrategy&lt; Strategies::METROPOLIS, ManifoldType &gt;::RunStatistics']]],
  ['release_16',['release',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#step-2-tag-the-merged-release',1,'Step 2: Tag the merged release'],['../md_docs_2_r_e_l_e_a_s_i_n_g.html#step-3-publish-and-verify-the-release',1,'Step 3: Publish and verify the release']]],
  ['release_20branch_17',['Validate the release branch',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#validate-the-release-branch',1,'']]],
  ['release_20critical_20fixes_18',['Release-critical fixes',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#release-critical-fixes',1,'']]],
  ['release_20metadata_19',['Update release metadata',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#update-release-metadata',1,'']]],
  ['release_20pull_20request_20',['Step 1: Prepare the release pull request',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#step-1-prepare-the-release-pull-request',1,'']]],
  ['releasing_20cdt_21',['Releasing CDT++',['../md_docs_2_r_e_l_e_a_s_i_n_g.html',1,'']]],
  ['reproducibility_5fmetadata_22',['Reproducibility_metadata',['../structcdt_1_1utilities_1_1_reproducibility__metadata.html',1,'cdt::utilities']]],
  ['reproducibility_5fmetadata_23',['reproducibility_metadata',['../classcdt_1_1_move_strategy_3_01_strategies_1_1_m_e_t_r_o_p_o_l_i_s_00_01_manifold_type_01_4.html#acc37eb6adcfdc7606a5e19028864c95f',1,'cdt::MoveStrategy&lt; Strategies::METROPOLIS, ManifoldType &gt;']]],
  ['reproducible_20performance_20baseline_24',['Reproducible performance baseline',['../md_docs_2cgal-integration.html#reproducible-performance-baseline',1,'']]],
  ['reproducible_20random_20runs_25',['Reproducible random runs',['../md_docs_2reproducibility.html',1,'']]],
  ['request_26',['Step 1: Prepare the release pull request',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#step-1-prepare-the-release-pull-request',1,'']]],
  ['reset_27',['reset',['../classcdt_1_1move__tracker_1_1_move_tracker.html#ac1ccb4579094a6aa0192c2c171927a1a',1,'cdt::move_tracker::MoveTracker']]],
  ['reset_5fcounters_28',['reset_counters',['../classcdt_1_1_move_command.html#aa5c67d97f7f56e7e552c326bb76e4ed1',1,'cdt::MoveCommand']]],
  ['reverse_5fmove_29',['reverse_move',['../classcdt_1_1_move_strategy_3_01_strategies_1_1_m_e_t_r_o_p_o_l_i_s_00_01_manifold_type_01_4.html#ae07dc2cb7e3b9c65668e0afd3bf0aa0a',1,'cdt::MoveStrategy&lt; Strategies::METROPOLIS, ManifoldType &gt;']]],
  ['roadmap_30',['Roadmap',['../index.html#roadmap',1,'']]],
  ['rounding_5fmode_31',['rounding_mode',['../_mpfr__value_8hpp.html#a94915c228cbf6b1286210d2398195b2a',1,'cdt::mpfr_values']]],
  ['rules_32',['Mutation and lifetime rules',['../md_docs_2cgal-integration.html#mutation-and-lifetime-rules',1,'']]],
  ['run_33',['Run',['../index.html#run',1,'']]],
  ['runs_34',['Reproducible random runs',['../md_docs_2reproducibility.html',1,'']]],
  ['runstatistics_35',['RunStatistics',['../structcdt_1_1_move_strategy_3_01_strategies_1_1_m_e_t_r_o_p_o_l_i_s_00_01_manifold_type_01_4_1_1_run_statistics.html',1,'cdt::MoveStrategy&lt; Strategies::METROPOLIS, ManifoldType &gt;']]],
  ['runtime_5fconfig_2ehpp_36',['Runtime_config.hpp',['../_runtime__config_8hpp.html',1,'']]]
];
