var searchData=
[
  ['a_20checkpoint_0',['Resume a checkpoint',['../index.html#resume-a-checkpoint',1,'']]],
  ['a_20simulation_1',['Run a simulation',['../index.html#run-a-simulation',1,'']]],
  ['acausal_2',['ACAUSAL',['../namespacecdt.html#adf93d8feb32e02c1d83d6d731484d4dfa658663a553d99a9ce4ab7675e6dd3ef2',1,'cdt']]],
  ['accept_5fpost_5fmutation_3',['accept_post_mutation',['../_ergodic__moves__3_8hpp.html#abb521a1685ffa48b590a33d825a9349c',1,'cdt::ergodic_moves::detail']]],
  ['acceptance_5fprobability_4',['acceptance_probability',['../classcdt_1_1_move_strategy_3_01_move_strategy_kind_1_1_m_e_t_r_o_p_o_l_i_s_00_01_manifold_type_01_4.html#a69a0904b8c4e673fd5cd986f6b46070d',1,'cdt::MoveStrategy&lt; MoveStrategyKind::METROPOLIS, ManifoldType &gt;']]],
  ['accepted_5',['accepted',['../structcdt_1_1utilities_1_1_move__statistics.html#a4f370f734452da4b6c1fc8958b433527',1,'cdt::utilities::Move_statistics::accepted'],['../classcdt_1_1_move_strategy_3_01_move_strategy_kind_1_1_m_e_t_r_o_p_o_l_i_s_00_01_manifold_type_01_4.html#a78b1d17994039bf86c067985c98b353b',1,'cdt::MoveStrategy&lt; MoveStrategyKind::METROPOLIS, ManifoldType &gt;::accepted()'],['../classcdt_1_1ergodic__moves_1_1_metropolis_transition.html#af54f561bec774c1d815894a1a3a54848',1,'cdt::ergodic_moves::MetropolisTransition::accepted()']]],
  ['accumulate_5fcommand_5fresults_6',['accumulate_command_results',['../_move__run_8hpp.html#a5ba7cdb8dcc6a4a60010de613afe1b7e',1,'cdt::detail']]],
  ['action_7',['Regge Calculus and Discrete Action',['../md__r_e_f_e_r_e_n_c_e_s.html#regge-calculus-and-discrete-action',1,'']]],
  ['action_20and_20metropolis_20hastings_20arithmetic_8',['Action and Metropolis-Hastings arithmetic',['../md_docs_2arithmetic-backend-evaluation.html#action-and-metropolis-hastings-arithmetic',1,'']]],
  ['action_20conventions_9',['Action conventions',['../md_docs_2metropolis-hastings.html#action-conventions',1,'']]],
  ['action_5fratio_10',['action_ratio',['../classcdt_1_1_move_strategy_3_01_move_strategy_kind_1_1_m_e_t_r_o_p_o_l_i_s_00_01_manifold_type_01_4.html#a5471c64e4720471ed354e49a38fb2e88',1,'cdt::MoveStrategy&lt; MoveStrategyKind::METROPOLIS, ManifoldType &gt;']]],
  ['actual_5fedges_11',['actual_edges',['../structcdt_1_1utilities_1_1_reproducibility__metadata.html#a159770b5dc2d9e9c899d3fae0015a5c8',1,'cdt::utilities::Reproducibility_metadata']]],
  ['actual_5ffaces_12',['actual_faces',['../structcdt_1_1utilities_1_1_reproducibility__metadata.html#af3a1f56d431ffd29e3966b830b17de2c',1,'cdt::utilities::Reproducibility_metadata']]],
  ['actual_5fsimplices_13',['actual_simplices',['../structcdt_1_1utilities_1_1_reproducibility__metadata.html#aec20b045f52b0afddd22f3a34c93e240',1,'cdt::utilities::Reproducibility_metadata']]],
  ['actual_5fvertices_14',['actual_vertices',['../structcdt_1_1utilities_1_1_reproducibility__metadata.html#ad5c17f36d18de346a7de31c46ef23afc',1,'cdt::utilities::Reproducibility_metadata']]],
  ['add_15',['add',['../_mpfr__value_8hpp.html#a9c406eb42cd5b2aa420034f95fd30b17',1,'cdt::mpfr_values']]],
  ['added_16',['Added',['../md__c_h_a_n_g_e_l_o_g.html#added',1,'Added'],['../md__c_h_a_n_g_e_l_o_g.html#added-1',1,'Added'],['../md__c_h_a_n_g_e_l_o_g.html#added-2',1,'Added']]],
  ['admissibility_17',['Checked flips and CDT admissibility',['../md_docs_2cgal-integration.html#checked-flips-and-cdt-admissibility',1,'']]],
  ['algorithm_18',['algorithm',['../md__r_e_f_e_r_e_n_c_e_s.html#metropolis-algorithm',1,'Metropolis algorithm'],['../md__r_e_f_e_r_e_n_c_e_s.html#metropolis-hastings-algorithm',1,'Metropolis-Hastings algorithm']]],
  ['alignment_5f32_5fbit_19',['ALIGNMENT_32_BIT',['../namespacecdt.html#a62a3bc3a3f1b2a14a0e444937d9a0a7b',1,'cdt']]],
  ['alignment_5f64_5fbit_20',['ALIGNMENT_64_BIT',['../namespacecdt.html#a42514e764636714442bbe549a53e0763',1,'cdt']]],
  ['alpha_21',['alpha',['../structcdt_1_1utilities_1_1_reproducibility__metadata.html#ac25d442788d48778affce6f30761d902',1,'cdt::utilities::Reproducibility_metadata::alpha'],['../classcdt_1_1_move_strategy_3_01_move_strategy_kind_1_1_m_e_t_r_o_p_o_l_i_s_00_01_manifold_type_01_4.html#ac1072d45d183eb70e76f6feffff3aefc',1,'cdt::MoveStrategy&lt; MoveStrategyKind::METROPOLIS, ManifoldType &gt;::alpha()'],['../classcdt_1_1runtime__config_1_1_simulation.html#ad0a8c0de58e8c7eb19550bddc9e0b5e7',1,'cdt::runtime_config::Simulation::alpha()'],['../classcdt_1_1s3__action_1_1_physical_parameters.html#ac620fe3ab3aa694581c3b055f356bc21',1,'cdt::s3_action::PhysicalParameters::alpha()']]],
  ['alternatives_22',['Alternatives',['../md_docs_2arithmetic-backend-evaluation.html#alternatives',1,'']]],
  ['an_20initial_20triangulation_23',['Generate and load an initial triangulation',['../index.html#generate-and-load-an-initial-triangulation',1,'']]],
  ['and_20cdt_20admissibility_24',['Checked flips and CDT admissibility',['../md_docs_2cgal-integration.html#checked-flips-and-cdt-admissibility',1,'']]],
  ['and_20citations_25',['References and Citations',['../md__r_e_f_e_r_e_n_c_e_s.html',1,'']]],
  ['and_20commit_20the_20release_20metadata_26',['Validate and commit the release metadata',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#validate-and-commit-the-release-metadata',1,'']]],
  ['and_20common_20contract_27',['Conventions and common contract',['../md_docs_2ergodic-moves.html#conventions-and-common-contract',1,'']]],
  ['and_20compiler_20contract_28',['Supported dependency and compiler contract',['../md_docs_2cgal-integration.html#supported-dependency-and-compiler-contract',1,'']]],
  ['and_20constraints_29',['Options and constraints',['../index.html#options-and-constraints',1,'']]],
  ['and_20correctness_30',['Determinism and correctness',['../md_docs_2multithreading.html#determinism-and-correctness',1,'']]],
  ['and_20delaunay_20expected_20complexity_31',['Random Voronoi and Delaunay expected complexity',['../md__r_e_f_e_r_e_n_c_e_s.html#random-voronoi-and-delaunay-expected-complexity',1,'']]],
  ['and_20discrete_20action_32',['Regge Calculus and Discrete Action',['../md__r_e_f_e_r_e_n_c_e_s.html#regge-calculus-and-discrete-action',1,'']]],
  ['and_20duplicate_20points_33',['Metadata, insertion, and duplicate points',['../md_docs_2cgal-integration.html#metadata-insertion-and-duplicate-points',1,'']]],
  ['and_20exact_20arithmetic_20policy_34',['Kernel and exact-arithmetic policy',['../md_docs_2cgal-integration.html#kernel-and-exact-arithmetic-policy',1,'']]],
  ['and_20geometry_20deltas_35',['State and geometry deltas',['../md_docs_2metropolis-hastings.html#state-and-geometry-deltas',1,'']]],
  ['and_20lifetime_20rules_36',['Mutation and lifetime rules',['../md_docs_2cgal-integration.html#mutation-and-lifetime-rules',1,'']]],
  ['and_20limitations_37',['Release scope and limitations',['../index.html#release-scope-and-limitations',1,'']]],
  ['and_20load_20an_20initial_20triangulation_38',['Generate and load an initial triangulation',['../index.html#generate-and-load-an-initial-triangulation',1,'']]],
  ['and_20local_20moves_39',['Simplicial Topology and Local Moves',['../md__r_e_f_e_r_e_n_c_e_s.html#simplicial-topology-and-local-moves',1,'']]],
  ['and_20metropolis_20hastings_20arithmetic_40',['Action and Metropolis-Hastings arithmetic',['../md_docs_2arithmetic-backend-evaluation.html#action-and-metropolis-hastings-arithmetic',1,'']]],
  ['and_20ownership_20behavior_41',['Failure and ownership behavior',['../md_docs_2cpp-api-quickstart.html#failure-and-ownership-behavior',1,'']]],
  ['and_20provenance_42',['Evaluation protocol and provenance',['../md_docs_2arithmetic-backend-evaluation.html#evaluation-protocol-and-provenance',1,'']]],
  ['and_20random_20number_20generation_43',['Computational Geometry and Random-Number Generation',['../md__r_e_f_e_r_e_n_c_e_s.html#computational-geometry-and-random-number-generation',1,'']]],
  ['and_20rollback_20gates_44',['Migration and rollback gates',['../md_docs_2arithmetic-backend-evaluation.html#migration-and-rollback-gates',1,'']]],
  ['and_20run_45',['Build and run',['../md_docs_2cpp-api-quickstart.html#build-and-run',1,'']]],
  ['and_20smoke_20policy_46',['Render manifest and smoke policy',['../md_docs_2viewer.html#render-manifest-and-smoke-policy',1,'']]],
  ['and_20support_47',['and support',['../md__s_e_c_u_r_i_t_y.html',1,'Security and support'],['../index.html#security-and-support',1,'Security and support']]],
  ['and_20tbb_20backed_20configurations_48',['Sequential and TBB-backed configurations',['../md_docs_2cgal-integration.html#sequential-and-tbb-backed-configurations',1,'']]],
  ['and_20test_49',['Build and test',['../md_docs_2multithreading.html#build-and-test',1,'']]],
  ['and_20verify_20the_20release_50',['Step 3: Publish and verify the release',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#step-3-publish-and-verify-the-release',1,'']]],
  ['and_20visual_20artifact_20contract_51',['Viewer and visual-artifact contract',['../md_docs_2viewer.html',1,'']]],
  ['api_52',['C++ API',['../index.html#c-api',1,'']]],
  ['api_20boundary_53',['C++ API boundary',['../md_docs_2api-boundary.html',1,'']]],
  ['api_20quickstart_54',['C++ API quickstart',['../md_docs_2cpp-api-quickstart.html',1,'']]],
  ['apply_5fmove_55',['apply_move',['../namespacecdt.html#ab4c41614ba4c6a6e04757b1e3f03dc66',1,'cdt']]],
  ['apply_5fmove_2ehpp_56',['Apply_move.hpp',['../_apply__move_8hpp.html',1,'']]],
  ['apply_5frandom_5fmove_57',['apply_random_move',['../classcdt_1_1_move_command.html#a560aea056adc42da33589dbc83a1a0b1',1,'cdt::MoveCommand']]],
  ['arc_5fcosine_58',['arc_cosine',['../_mpfr__value_8hpp.html#ab9402a4cc78576da5a029d740509e2bf',1,'cdt::mpfr_values']]],
  ['archival_20handoff_59',['Step 5: Stabilize, then complete the archival handoff',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#step-5-stabilize-then-complete-the-archival-handoff',1,'']]],
  ['archival_20provenance_60',['Refresh the stable archival provenance',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#refresh-the-stable-archival-provenance',1,'']]],
  ['arithmetic_61',['Action and Metropolis-Hastings arithmetic',['../md_docs_2arithmetic-backend-evaluation.html#action-and-metropolis-hastings-arithmetic',1,'']]],
  ['arithmetic_20evaluation_62',['GMP/MPFR-free arithmetic evaluation',['../md_docs_2arithmetic-backend-evaluation.html',1,'']]],
  ['arithmetic_20policy_63',['Kernel and exact-arithmetic policy',['../md_docs_2cgal-integration.html#kernel-and-exact-arithmetic-policy',1,'']]],
  ['artifact_64',['artifact',['../structcdt_1_1utilities_1_1_reproducibility__metadata.html#a0e42daedbfab9fa2abe09b7ba506f740',1,'cdt::utilities::Reproducibility_metadata']]],
  ['artifact_20contract_65',['Viewer and visual-artifact contract',['../md_docs_2viewer.html',1,'']]],
  ['artifact_20layout_66',['Artifact layout',['../md_docs_2comparison-harness.html#artifact-layout',1,'']]],
  ['artifactkind_67',['ArtifactKind',['../_utilities_8hpp.html#a46664ff29f65038f90a18f0523cfda41',1,'cdt::utilities']]],
  ['as_5finteger_68',['as_integer',['../_move__tracker_8hpp.html#a3040e41eb6cd8fecfedc80f19ed9373e',1,'cdt::move_tracker']]],
  ['attempt_5ftransition_69',['attempt_transition',['../classcdt_1_1_move_strategy_3_01_move_strategy_kind_1_1_m_e_t_r_o_p_o_l_i_s_00_01_manifold_type_01_4.html#ad01089b11fc5f16f13c07b91787d5da1',1,'cdt::MoveStrategy&lt; MoveStrategyKind::METROPOLIS, ManifoldType &gt;::attempt_transition(ManifoldType &amp;current, move_tracker::MoveType const move, long double const trial_value) -&gt; ergodic_moves::MetropolisTransition'],['../classcdt_1_1_move_strategy_3_01_move_strategy_kind_1_1_m_e_t_r_o_p_o_l_i_s_00_01_manifold_type_01_4.html#a70dc1c934382e2128d03d0d0bf7bf6e3',1,'cdt::MoveStrategy&lt; MoveStrategyKind::METROPOLIS, ManifoldType &gt;::attempt_transition(ManifoldType &amp;current) -&gt; ergodic_moves::MetropolisTransition']]],
  ['attempted_70',['attempted',['../structcdt_1_1utilities_1_1_move__statistics.html#aab982e5230e456fca971019eaba2ed93',1,'cdt::utilities::Move_statistics::attempted'],['../classcdt_1_1_move_strategy_3_01_move_strategy_kind_1_1_m_e_t_r_o_p_o_l_i_s_00_01_manifold_type_01_4.html#ad9aa1df77b3fbecd204bc240ff068395',1,'cdt::MoveStrategy&lt; MoveStrategyKind::METROPOLIS, ManifoldType &gt;::attempted()'],['../classcdt_1_1_move_strategy_3_01_move_strategy_kind_1_1_m_o_v_e___a_l_w_a_y_s_00_01_manifold_type_01_4.html#a5abab47a1328003a04f584333f4cb2b6',1,'cdt::MoveStrategy&lt; MoveStrategyKind::MOVE_ALWAYS, ManifoldType &gt;::attempted()'],['../classcdt_1_1_move_command.html#a20b11c2e1750abccbed42d13f5f0e737',1,'cdt::MoveCommand::attempted()']]],
  ['audit_71',['2+1D CDT ergodic move audit',['../md_docs_2ergodic-moves.html',1,'']]]
];
