var searchData=
[
  ['accept_5fpost_5fmutation_0',['accept_post_mutation',['../_ergodic__moves__3_8hpp.html#abb521a1685ffa48b590a33d825a9349c',1,'cdt::ergodic_moves::detail']]],
  ['acceptance_5fprobability_1',['acceptance_probability',['../classcdt_1_1_move_strategy_3_01_move_strategy_kind_1_1_m_e_t_r_o_p_o_l_i_s_00_01_manifold_type_01_4.html#a69a0904b8c4e673fd5cd986f6b46070d',1,'cdt::MoveStrategy&lt; MoveStrategyKind::METROPOLIS, ManifoldType &gt;']]],
  ['accepted_2',['accepted',['../structcdt_1_1_move_strategy_3_01_move_strategy_kind_1_1_m_e_t_r_o_p_o_l_i_s_00_01_manifold_type_01_4_1_1_run_statistics.html#ab2377b549b0548ae8331a42bbebc8f7b',1,'cdt::MoveStrategy&lt; MoveStrategyKind::METROPOLIS, ManifoldType &gt;::RunStatistics::accepted'],['../classcdt_1_1_move_strategy_3_01_move_strategy_kind_1_1_m_e_t_r_o_p_o_l_i_s_00_01_manifold_type_01_4.html#a78b1d17994039bf86c067985c98b353b',1,'cdt::MoveStrategy&lt; MoveStrategyKind::METROPOLIS, ManifoldType &gt;::accepted()']]],
  ['accumulate_5fcommand_5fresults_3',['accumulate_command_results',['../_move__run_8hpp.html#a5ba7cdb8dcc6a4a60010de613afe1b7e',1,'cdt::detail']]],
  ['action_4',['Regge Calculus and Discrete Action',['../md__r_e_f_e_r_e_n_c_e_s.html#regge-calculus-and-discrete-action',1,'']]],
  ['action_20and_20metropolis_20hastings_20arithmetic_5',['Action and Metropolis-Hastings arithmetic',['../md_docs_2arithmetic-backend-evaluation.html#action-and-metropolis-hastings-arithmetic',1,'']]],
  ['action_20conventions_6',['Action conventions',['../md_docs_2metropolis-hastings.html#action-conventions',1,'']]],
  ['action_5fratio_7',['action_ratio',['../classcdt_1_1_move_strategy_3_01_move_strategy_kind_1_1_m_e_t_r_o_p_o_l_i_s_00_01_manifold_type_01_4.html#a5471c64e4720471ed354e49a38fb2e88',1,'cdt::MoveStrategy&lt; MoveStrategyKind::METROPOLIS, ManifoldType &gt;']]],
  ['admissibility_8',['Checked flips and CDT admissibility',['../md_docs_2cgal-integration.html#checked-flips-and-cdt-admissibility',1,'']]],
  ['algorithm_9',['Metropolis-Hastings algorithm',['../md__r_e_f_e_r_e_n_c_e_s.html#metropolis-hastings-algorithm',1,'']]],
  ['alignment_5f32_5fbit_10',['ALIGNMENT_32_BIT',['../namespacecdt.html#a62a3bc3a3f1b2a14a0e444937d9a0a7b',1,'cdt']]],
  ['alignment_5f64_5fbit_11',['ALIGNMENT_64_BIT',['../namespacecdt.html#a42514e764636714442bbe549a53e0763',1,'cdt']]],
  ['alpha_12',['alpha',['../classcdt_1_1_move_strategy_3_01_move_strategy_kind_1_1_m_e_t_r_o_p_o_l_i_s_00_01_manifold_type_01_4.html#ac1072d45d183eb70e76f6feffff3aefc',1,'cdt::MoveStrategy&lt; MoveStrategyKind::METROPOLIS, ManifoldType &gt;']]],
  ['alternatives_13',['Alternatives',['../md_docs_2arithmetic-backend-evaluation.html#alternatives',1,'']]],
  ['analysis_14',['Static Analysis',['../index.html#static-analysis',1,'']]],
  ['and_20cdt_20admissibility_15',['Checked flips and CDT admissibility',['../md_docs_2cgal-integration.html#checked-flips-and-cdt-admissibility',1,'']]],
  ['and_20citations_16',['References and Citations',['../md__r_e_f_e_r_e_n_c_e_s.html',1,'']]],
  ['and_20common_20contract_17',['Conventions and common contract',['../md_docs_2ergodic-moves.html#conventions-and-common-contract',1,'']]],
  ['and_20compiler_20contract_18',['Supported dependency and compiler contract',['../md_docs_2cgal-integration.html#supported-dependency-and-compiler-contract',1,'']]],
  ['and_20correctness_19',['Determinism and correctness',['../md_docs_2multithreading.html#determinism-and-correctness',1,'']]],
  ['and_20delaunay_20expected_20complexity_20',['Random Voronoi and Delaunay expected complexity',['../md__r_e_f_e_r_e_n_c_e_s.html#random-voronoi-and-delaunay-expected-complexity',1,'']]],
  ['and_20discrete_20action_21',['Regge Calculus and Discrete Action',['../md__r_e_f_e_r_e_n_c_e_s.html#regge-calculus-and-discrete-action',1,'']]],
  ['and_20duplicate_20points_22',['Metadata, insertion, and duplicate points',['../md_docs_2cgal-integration.html#metadata-insertion-and-duplicate-points',1,'']]],
  ['and_20exact_20arithmetic_20policy_23',['Kernel and exact-arithmetic policy',['../md_docs_2cgal-integration.html#kernel-and-exact-arithmetic-policy',1,'']]],
  ['and_20geometry_20deltas_24',['State and geometry deltas',['../md_docs_2metropolis-hastings.html#state-and-geometry-deltas',1,'']]],
  ['and_20lifetime_20rules_25',['Mutation and lifetime rules',['../md_docs_2cgal-integration.html#mutation-and-lifetime-rules',1,'']]],
  ['and_20local_20moves_26',['Simplicial Topology and Local Moves',['../md__r_e_f_e_r_e_n_c_e_s.html#simplicial-topology-and-local-moves',1,'']]],
  ['and_20metropolis_20hastings_20arithmetic_27',['Action and Metropolis-Hastings arithmetic',['../md_docs_2arithmetic-backend-evaluation.html#action-and-metropolis-hastings-arithmetic',1,'']]],
  ['and_20provenance_28',['Evaluation protocol and provenance',['../md_docs_2arithmetic-backend-evaluation.html#evaluation-protocol-and-provenance',1,'']]],
  ['and_20random_20number_20generation_29',['Computational Geometry and Random-Number Generation',['../md__r_e_f_e_r_e_n_c_e_s.html#computational-geometry-and-random-number-generation',1,'']]],
  ['and_20rollback_20gates_30',['Migration and rollback gates',['../md_docs_2arithmetic-backend-evaluation.html#migration-and-rollback-gates',1,'']]],
  ['and_20tbb_20backed_20configurations_31',['Sequential and TBB-backed configurations',['../md_docs_2cgal-integration.html#sequential-and-tbb-backed-configurations',1,'']]],
  ['and_20test_32',['Build and test',['../md_docs_2multithreading.html#build-and-test',1,'']]],
  ['and_20verify_20the_20release_33',['Step 3: Publish and verify the release',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#step-3-publish-and-verify-the-release',1,'']]],
  ['api_20boundary_34',['C++ API boundary',['../md_docs_2api-boundary.html',1,'']]],
  ['apply_5fmove_35',['apply_move',['../namespacecdt.html#ab4c41614ba4c6a6e04757b1e3f03dc66',1,'cdt']]],
  ['apply_5fmove_2ehpp_36',['Apply_move.hpp',['../_apply__move_8hpp.html',1,'']]],
  ['apply_5frandom_5fmove_37',['apply_random_move',['../classcdt_1_1_move_command.html#a560aea056adc42da33589dbc83a1a0b1',1,'cdt::MoveCommand']]],
  ['arithmetic_38',['Action and Metropolis-Hastings arithmetic',['../md_docs_2arithmetic-backend-evaluation.html#action-and-metropolis-hastings-arithmetic',1,'']]],
  ['arithmetic_20evaluation_39',['GMP/MPFR-free arithmetic evaluation',['../md_docs_2arithmetic-backend-evaluation.html',1,'']]],
  ['arithmetic_20policy_40',['Kernel and exact-arithmetic policy',['../md_docs_2cgal-integration.html#kernel-and-exact-arithmetic-policy',1,'']]],
  ['artifact_20layout_41',['Artifact layout',['../md_docs_2comparison-harness.html#artifact-layout',1,'']]],
  ['as_5finteger_42',['as_integer',['../_move__tracker_8hpp.html#aa2b8d0eb3835b7852180843f4f00dfe1',1,'cdt::move_tracker']]],
  ['attempt_5ftransition_43',['attempt_transition',['../classcdt_1_1_move_strategy_3_01_move_strategy_kind_1_1_m_e_t_r_o_p_o_l_i_s_00_01_manifold_type_01_4.html#afb2498e1f88fc8de2da4ea96a2e83fc2',1,'cdt::MoveStrategy&lt; MoveStrategyKind::METROPOLIS, ManifoldType &gt;']]],
  ['attempted_44',['attempted',['../classcdt_1_1_move_strategy_3_01_move_strategy_kind_1_1_m_e_t_r_o_p_o_l_i_s_00_01_manifold_type_01_4.html#ad9aa1df77b3fbecd204bc240ff068395',1,'cdt::MoveStrategy&lt; MoveStrategyKind::METROPOLIS, ManifoldType &gt;::attempted()'],['../classcdt_1_1_move_strategy_3_01_move_strategy_kind_1_1_m_o_v_e___a_l_w_a_y_s_00_01_manifold_type_01_4.html#a5abab47a1328003a04f584333f4cb2b6',1,'cdt::MoveStrategy&lt; MoveStrategyKind::MOVE_ALWAYS, ManifoldType &gt;::attempted()'],['../classcdt_1_1_move_command.html#a20b11c2e1750abccbed42d13f5f0e737',1,'cdt::MoveCommand::attempted()']]],
  ['audit_45',['2+1D CDT ergodic move audit',['../md_docs_2ergodic-moves.html',1,'']]]
];
