var searchData=
[
  ['random_20number_20generation_0',['Computational Geometry and Random-Number Generation',['../md__r_e_f_e_r_e_n_c_e_s.html#computational-geometry-and-random-number-generation',1,'']]],
  ['random_20number_20generators_1',['PCG random-number generators',['../md__r_e_f_e_r_e_n_c_e_s.html#pcg-random-number-generators',1,'']]],
  ['random_20runs_2',['Reproducible random runs',['../md_docs_2reproducibility.html',1,'']]],
  ['record_3',['record',['../md_docs_2ergodic-moves.html#move-by-move-record',1,'Move-by-move record'],['../md_docs_2ergodic-moves.html#verification-record',1,'Verification record']]],
  ['reference_20suite_20status_4',['Current reference-suite status',['../index.html#current-reference-suite-status',1,'']]],
  ['references_5',['References',['../md_docs_2metropolis-hastings.html#references',1,'']]],
  ['references_20and_20citations_6',['References and Citations',['../md__r_e_f_e_r_e_n_c_e_s.html',1,'']]],
  ['regge_20calculus_7',['Regge calculus',['../md__r_e_f_e_r_e_n_c_e_s.html#regge-calculus',1,'']]],
  ['regge_20calculus_20and_20discrete_20action_8',['Regge Calculus and Discrete Action',['../md__r_e_f_e_r_e_n_c_e_s.html#regge-calculus-and-discrete-action',1,'']]],
  ['regression_20oracle_20scope_9',['Regression-oracle scope',['../index.html#regression-oracle-scope',1,'']]],
  ['release_10',['release',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#step-2-tag-the-merged-release',1,'Step 2: Tag the merged release'],['../md_docs_2_r_e_l_e_a_s_i_n_g.html#step-3-publish-and-verify-the-release',1,'Step 3: Publish and verify the release']]],
  ['release_20branch_11',['Validate the release branch',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#validate-the-release-branch',1,'']]],
  ['release_20critical_20fixes_12',['Release-critical fixes',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#release-critical-fixes',1,'']]],
  ['release_20metadata_13',['Update release metadata',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#update-release-metadata',1,'']]],
  ['release_20pull_20request_14',['Step 1: Prepare the release pull request',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#step-1-prepare-the-release-pull-request',1,'']]],
  ['releasing_20cdt_15',['Releasing CDT++',['../md_docs_2_r_e_l_e_a_s_i_n_g.html',1,'']]],
  ['reproducible_20performance_20baseline_16',['Reproducible performance baseline',['../md_docs_2cgal-integration.html#reproducible-performance-baseline',1,'']]],
  ['reproducible_20random_20runs_17',['Reproducible random runs',['../md_docs_2reproducibility.html',1,'']]],
  ['request_18',['Step 1: Prepare the release pull request',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#step-1-prepare-the-release-pull-request',1,'']]],
  ['roadmap_19',['Roadmap',['../index.html#roadmap',1,'']]],
  ['rules_20',['Mutation and lifetime rules',['../md_docs_2cgal-integration.html#mutation-and-lifetime-rules',1,'']]],
  ['run_21',['Run',['../index.html#run',1,'']]],
  ['runs_22',['Reproducible random runs',['../md_docs_2reproducibility.html',1,'']]]
];
