var searchData=
[
  ['a_20checkpoint_0',['Resume a checkpoint',['../index.html#resume-a-checkpoint',1,'']]],
  ['a_20simulation_1',['Run a simulation',['../index.html#run-a-simulation',1,'']]],
  ['action_2',['Regge Calculus and Discrete Action',['../md__r_e_f_e_r_e_n_c_e_s.html#regge-calculus-and-discrete-action',1,'']]],
  ['action_20and_20metropolis_20hastings_20arithmetic_3',['Action and Metropolis-Hastings arithmetic',['../md_docs_2arithmetic-backend-evaluation.html#action-and-metropolis-hastings-arithmetic',1,'']]],
  ['action_20conventions_4',['Action conventions',['../md_docs_2metropolis-hastings.html#action-conventions',1,'']]],
  ['added_5',['Added',['../md__c_h_a_n_g_e_l_o_g.html#added',1,'Added'],['../md__c_h_a_n_g_e_l_o_g.html#added-1',1,'Added'],['../md__c_h_a_n_g_e_l_o_g.html#added-2',1,'Added']]],
  ['admissibility_6',['Checked flips and CDT admissibility',['../md_docs_2cgal-integration.html#checked-flips-and-cdt-admissibility',1,'']]],
  ['algorithm_7',['algorithm',['../md__r_e_f_e_r_e_n_c_e_s.html#metropolis-algorithm',1,'Metropolis algorithm'],['../md__r_e_f_e_r_e_n_c_e_s.html#metropolis-hastings-algorithm',1,'Metropolis-Hastings algorithm']]],
  ['alternatives_8',['Alternatives',['../md_docs_2arithmetic-backend-evaluation.html#alternatives',1,'']]],
  ['an_20initial_20triangulation_9',['Generate and load an initial triangulation',['../index.html#generate-and-load-an-initial-triangulation',1,'']]],
  ['and_20cdt_20admissibility_10',['Checked flips and CDT admissibility',['../md_docs_2cgal-integration.html#checked-flips-and-cdt-admissibility',1,'']]],
  ['and_20citations_11',['References and Citations',['../md__r_e_f_e_r_e_n_c_e_s.html',1,'']]],
  ['and_20commit_20the_20release_20metadata_12',['Validate and commit the release metadata',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#validate-and-commit-the-release-metadata',1,'']]],
  ['and_20common_20contract_13',['Conventions and common contract',['../md_docs_2ergodic-moves.html#conventions-and-common-contract',1,'']]],
  ['and_20compiler_20contract_14',['Supported dependency and compiler contract',['../md_docs_2cgal-integration.html#supported-dependency-and-compiler-contract',1,'']]],
  ['and_20constraints_15',['Options and constraints',['../index.html#options-and-constraints',1,'']]],
  ['and_20correctness_16',['Determinism and correctness',['../md_docs_2multithreading.html#determinism-and-correctness',1,'']]],
  ['and_20delaunay_20expected_20complexity_17',['Random Voronoi and Delaunay expected complexity',['../md__r_e_f_e_r_e_n_c_e_s.html#random-voronoi-and-delaunay-expected-complexity',1,'']]],
  ['and_20discrete_20action_18',['Regge Calculus and Discrete Action',['../md__r_e_f_e_r_e_n_c_e_s.html#regge-calculus-and-discrete-action',1,'']]],
  ['and_20duplicate_20points_19',['Metadata, insertion, and duplicate points',['../md_docs_2cgal-integration.html#metadata-insertion-and-duplicate-points',1,'']]],
  ['and_20exact_20arithmetic_20policy_20',['Kernel and exact-arithmetic policy',['../md_docs_2cgal-integration.html#kernel-and-exact-arithmetic-policy',1,'']]],
  ['and_20geometry_20deltas_21',['State and geometry deltas',['../md_docs_2metropolis-hastings.html#state-and-geometry-deltas',1,'']]],
  ['and_20lifetime_20rules_22',['Mutation and lifetime rules',['../md_docs_2cgal-integration.html#mutation-and-lifetime-rules',1,'']]],
  ['and_20limitations_23',['Release scope and limitations',['../index.html#release-scope-and-limitations',1,'']]],
  ['and_20load_20an_20initial_20triangulation_24',['Generate and load an initial triangulation',['../index.html#generate-and-load-an-initial-triangulation',1,'']]],
  ['and_20local_20moves_25',['Simplicial Topology and Local Moves',['../md__r_e_f_e_r_e_n_c_e_s.html#simplicial-topology-and-local-moves',1,'']]],
  ['and_20metropolis_20hastings_20arithmetic_26',['Action and Metropolis-Hastings arithmetic',['../md_docs_2arithmetic-backend-evaluation.html#action-and-metropolis-hastings-arithmetic',1,'']]],
  ['and_20ownership_20behavior_27',['Failure and ownership behavior',['../md_docs_2cpp-api-quickstart.html#failure-and-ownership-behavior',1,'']]],
  ['and_20provenance_28',['Evaluation protocol and provenance',['../md_docs_2arithmetic-backend-evaluation.html#evaluation-protocol-and-provenance',1,'']]],
  ['and_20random_20number_20generation_29',['Computational Geometry and Random-Number Generation',['../md__r_e_f_e_r_e_n_c_e_s.html#computational-geometry-and-random-number-generation',1,'']]],
  ['and_20rollback_20gates_30',['Migration and rollback gates',['../md_docs_2arithmetic-backend-evaluation.html#migration-and-rollback-gates',1,'']]],
  ['and_20run_31',['Build and run',['../md_docs_2cpp-api-quickstart.html#build-and-run',1,'']]],
  ['and_20smoke_20policy_32',['Render manifest and smoke policy',['../md_docs_2viewer.html#render-manifest-and-smoke-policy',1,'']]],
  ['and_20support_33',['and support',['../md__s_e_c_u_r_i_t_y.html',1,'Security and support'],['../index.html#security-and-support',1,'Security and support']]],
  ['and_20tbb_20backed_20configurations_34',['Sequential and TBB-backed configurations',['../md_docs_2cgal-integration.html#sequential-and-tbb-backed-configurations',1,'']]],
  ['and_20test_35',['Build and test',['../md_docs_2multithreading.html#build-and-test',1,'']]],
  ['and_20verify_20the_20release_36',['Step 3: Publish and verify the release',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#step-3-publish-and-verify-the-release',1,'']]],
  ['and_20visual_20artifact_20contract_37',['Viewer and visual-artifact contract',['../md_docs_2viewer.html',1,'']]],
  ['api_38',['C++ API',['../index.html#c-api',1,'']]],
  ['api_20boundary_39',['C++ API boundary',['../md_docs_2api-boundary.html',1,'']]],
  ['api_20quickstart_40',['C++ API quickstart',['../md_docs_2cpp-api-quickstart.html',1,'']]],
  ['archival_20handoff_41',['Step 5: Stabilize, then complete the archival handoff',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#step-5-stabilize-then-complete-the-archival-handoff',1,'']]],
  ['archival_20provenance_42',['Refresh the stable archival provenance',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#refresh-the-stable-archival-provenance',1,'']]],
  ['arithmetic_43',['Action and Metropolis-Hastings arithmetic',['../md_docs_2arithmetic-backend-evaluation.html#action-and-metropolis-hastings-arithmetic',1,'']]],
  ['arithmetic_20evaluation_44',['GMP/MPFR-free arithmetic evaluation',['../md_docs_2arithmetic-backend-evaluation.html',1,'']]],
  ['arithmetic_20policy_45',['Kernel and exact-arithmetic policy',['../md_docs_2cgal-integration.html#kernel-and-exact-arithmetic-policy',1,'']]],
  ['artifact_20contract_46',['Viewer and visual-artifact contract',['../md_docs_2viewer.html',1,'']]],
  ['artifact_20layout_47',['Artifact layout',['../md_docs_2comparison-harness.html#artifact-layout',1,'']]],
  ['audit_48',['2+1D CDT ergodic move audit',['../md_docs_2ergodic-moves.html',1,'']]]
];
