var searchData=
[
  ['action_0',['Regge Calculus and Discrete Action',['../md__r_e_f_e_r_e_n_c_e_s.html#regge-calculus-and-discrete-action',1,'']]],
  ['action_20conventions_1',['Action conventions',['../md_docs_2metropolis-hastings.html#action-conventions',1,'']]],
  ['admissibility_2',['Checked flips and CDT admissibility',['../md_docs_2cgal-integration.html#checked-flips-and-cdt-admissibility',1,'']]],
  ['algorithm_3',['Metropolis-Hastings algorithm',['../md__r_e_f_e_r_e_n_c_e_s.html#metropolis-hastings-algorithm',1,'']]],
  ['analysis_4',['Static Analysis',['../index.html#static-analysis',1,'']]],
  ['and_20cdt_20admissibility_5',['Checked flips and CDT admissibility',['../md_docs_2cgal-integration.html#checked-flips-and-cdt-admissibility',1,'']]],
  ['and_20citations_6',['References and Citations',['../md__r_e_f_e_r_e_n_c_e_s.html',1,'']]],
  ['and_20common_20contract_7',['Conventions and common contract',['../md_docs_2ergodic-moves.html#conventions-and-common-contract',1,'']]],
  ['and_20compiler_20contract_8',['Supported dependency and compiler contract',['../md_docs_2cgal-integration.html#supported-dependency-and-compiler-contract',1,'']]],
  ['and_20correctness_9',['Determinism and correctness',['../md_docs_2multithreading.html#determinism-and-correctness',1,'']]],
  ['and_20delaunay_20expected_20complexity_10',['Random Voronoi and Delaunay expected complexity',['../md__r_e_f_e_r_e_n_c_e_s.html#random-voronoi-and-delaunay-expected-complexity',1,'']]],
  ['and_20discrete_20action_11',['Regge Calculus and Discrete Action',['../md__r_e_f_e_r_e_n_c_e_s.html#regge-calculus-and-discrete-action',1,'']]],
  ['and_20duplicate_20points_12',['Metadata, insertion, and duplicate points',['../md_docs_2cgal-integration.html#metadata-insertion-and-duplicate-points',1,'']]],
  ['and_20exact_20arithmetic_20policy_13',['Kernel and exact-arithmetic policy',['../md_docs_2cgal-integration.html#kernel-and-exact-arithmetic-policy',1,'']]],
  ['and_20geometry_20deltas_14',['State and geometry deltas',['../md_docs_2metropolis-hastings.html#state-and-geometry-deltas',1,'']]],
  ['and_20lifetime_20rules_15',['Mutation and lifetime rules',['../md_docs_2cgal-integration.html#mutation-and-lifetime-rules',1,'']]],
  ['and_20local_20moves_16',['Simplicial Topology and Local Moves',['../md__r_e_f_e_r_e_n_c_e_s.html#simplicial-topology-and-local-moves',1,'']]],
  ['and_20random_20number_20generation_17',['Computational Geometry and Random-Number Generation',['../md__r_e_f_e_r_e_n_c_e_s.html#computational-geometry-and-random-number-generation',1,'']]],
  ['and_20tbb_20backed_20configurations_18',['Sequential and TBB-backed configurations',['../md_docs_2cgal-integration.html#sequential-and-tbb-backed-configurations',1,'']]],
  ['and_20test_19',['Build and test',['../md_docs_2multithreading.html#build-and-test',1,'']]],
  ['and_20verify_20the_20release_20',['Step 3: Publish and verify the release',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#step-3-publish-and-verify-the-release',1,'']]],
  ['api_20boundary_21',['C++ API boundary',['../md_docs_2api-boundary.html',1,'']]],
  ['arithmetic_20policy_22',['Kernel and exact-arithmetic policy',['../md_docs_2cgal-integration.html#kernel-and-exact-arithmetic-policy',1,'']]],
  ['audit_23',['2+1D CDT ergodic move audit',['../md_docs_2ergodic-moves.html',1,'']]]
];
