var searchData=
[
  ['c_20api_20boundary_0',['C++ API boundary',['../md_docs_2api-boundary.html',1,'']]],
  ['c_20api_20quickstart_1',['C++ API quickstart',['../md_docs_2cpp-api-quickstart.html',1,'']]],
  ['c_20rust_20comparison_20harness_2',['Offline C++/Rust comparison harness',['../md_docs_2comparison-harness.html',1,'']]],
  ['calculus_3',['Regge calculus',['../md__r_e_f_e_r_e_n_c_e_s.html#regge-calculus',1,'']]],
  ['calculus_20and_20discrete_20action_4',['Regge Calculus and Discrete Action',['../md__r_e_f_e_r_e_n_c_e_s.html#regge-calculus-and-discrete-action',1,'']]],
  ['carlo_20methods_5',['Monte Carlo Methods',['../md__r_e_f_e_r_e_n_c_e_s.html#monte-carlo-methods',1,'']]],
  ['causal_20dynamical_20triangulations_20theory_6',['Foundational Causal Dynamical Triangulations Theory',['../md__r_e_f_e_r_e_n_c_e_s.html#foundational-causal-dynamical-triangulations-theory',1,'']]],
  ['cdt_7',['CDT',['../index.html#citing-cdt',1,'Citing CDT++'],['../md_docs_2_r_e_l_e_a_s_i_n_g.html',1,'Releasing CDT++']]],
  ['cdt_202001_8',['Three-dimensional CDT (2001)',['../md__r_e_f_e_r_e_n_c_e_s.html#three-dimensional-cdt-2001',1,'']]],
  ['cdt_20admissibility_9',['Checked flips and CDT admissibility',['../md_docs_2cgal-integration.html#checked-flips-and-cdt-admissibility',1,'']]],
  ['cdt_20ergodic_20move_20audit_10',['2+1D CDT ergodic move audit',['../md_docs_2ergodic-moves.html',1,'']]],
  ['cdt_20framework_11',['Original CDT framework',['../md__r_e_f_e_r_e_n_c_e_s.html#original-cdt-framework',1,'']]],
  ['cdt_20framework_202001_12',['CDT framework (2001)',['../md__r_e_f_e_r_e_n_c_e_s.html#cdt-framework-2001',1,'']]],
  ['cdt_20plusplus_13',['CDT-plusplus',['../index.html',1,'']]],
  ['cdt_20reference_20fixture_20package_14',['CDT++ reference fixture package',['../dir_6e133a56364528c326e124d8bed524d8.html#cdt-reference-fixture-package',1,'']]],
  ['cgal_206_202_20integration_20contract_15',['CGAL 6.2 integration contract',['../md_docs_2cgal-integration.html',1,'']]],
  ['cgal_20contract_16',['Multithreaded CGAL contract',['../md_docs_2multithreading.html',1,'']]],
  ['cgal_20triangulations_17',['CGAL triangulations',['../md__r_e_f_e_r_e_n_c_e_s.html#cgal-triangulations',1,'']]],
  ['check_18',['Move-selection performance check',['../md_docs_2reproducibility.html#move-selection-performance-check',1,'']]],
  ['checked_20flips_20and_20cdt_20admissibility_19',['Checked flips and CDT admissibility',['../md_docs_2cgal-integration.html#checked-flips-and-cdt-admissibility',1,'']]],
  ['checklist_20',['Upgrade checklist',['../md_docs_2cgal-integration.html#upgrade-checklist',1,'']]],
  ['citations_21',['References and Citations',['../md__r_e_f_e_r_e_n_c_e_s.html',1,'']]],
  ['cite_20this_20software_22',['How to Cite This Software',['../md__r_e_f_e_r_e_n_c_e_s.html#how-to-cite-this-software',1,'']]],
  ['citing_20cdt_23',['Citing CDT++',['../index.html#citing-cdt',1,'']]],
  ['classification_24',['Header classification',['../md_docs_2api-boundary.html#header-classification',1,'']]],
  ['clean_20up_25',['Step 4: Clean up',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#step-4-clean-up',1,'']]],
  ['command_20line_20reference_26',['Command-line reference',['../index.html#command-line-reference',1,'']]],
  ['common_20contract_27',['Conventions and common contract',['../md_docs_2ergodic-moves.html#conventions-and-common-contract',1,'']]],
  ['comparison_28',['Offline Comparison',['../index.html#offline-comparison',1,'']]],
  ['comparison_20harness_29',['comparison harness',['../dir_6e133a56364528c326e124d8bed524d8.html#local-comparison-harness',1,'Local comparison harness'],['../md_docs_2comparison-harness.html',1,'Offline C++/Rust comparison harness']]],
  ['compatibility_20policy_30',['Compatibility policy',['../md_docs_2api-boundary.html#compatibility-policy',1,'']]],
  ['compiler_20contract_31',['Supported dependency and compiler contract',['../md_docs_2cgal-integration.html#supported-dependency-and-compiler-contract',1,'']]],
  ['complexity_32',['complexity',['../md__r_e_f_e_r_e_n_c_e_s.html#random-voronoi-and-delaunay-expected-complexity',1,'Random Voronoi and Delaunay expected complexity'],['../md__r_e_f_e_r_e_n_c_e_s.html#three-dimensional-delaunay-complexity',1,'Three-dimensional Delaunay complexity']]],
  ['computational_20geometry_20and_20random_20number_20generation_33',['Computational Geometry and Random-Number Generation',['../md__r_e_f_e_r_e_n_c_e_s.html#computational-geometry-and-random-number-generation',1,'']]],
  ['configurations_34',['Sequential and TBB-backed configurations',['../md_docs_2cgal-integration.html#sequential-and-tbb-backed-configurations',1,'']]],
  ['consumption_35',['Rust consumption',['../dir_6e133a56364528c326e124d8bed524d8.html#rust-consumption',1,'']]],
  ['contents_36',['Table of contents',['../index.html#table-of-contents',1,'']]],
  ['contract_37',['contract',['../md_docs_2cgal-integration.html',1,'CGAL 6.2 integration contract'],['../md_docs_2ergodic-moves.html#conventions-and-common-contract',1,'Conventions and common contract'],['../md_docs_2metropolis-hastings.html',1,'Metropolis-Hastings transition contract'],['../md_docs_2multithreading.html',1,'Multithreaded CGAL contract'],['../md_docs_2reproducibility.html#persistence-contract',1,'Persistence contract'],['../md_docs_2comparison-harness.html#producer-contract',1,'Producer contract'],['../md_docs_2cgal-integration.html#supported-dependency-and-compiler-contract',1,'Supported dependency and compiler contract'],['../md_docs_2viewer.html',1,'Viewer and visual-artifact contract']]],
  ['contracts_38',['Required contracts',['../md_docs_2arithmetic-backend-evaluation.html#required-contracts',1,'']]],
  ['contributing_39',['Contributing',['../index.html#contributing',1,'']]],
  ['conventions_40',['Conventions',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#conventions',1,'']]],
  ['conventions_41',['Action conventions',['../md_docs_2metropolis-hastings.html#action-conventions',1,'']]],
  ['conventions_20and_20common_20contract_42',['Conventions and common contract',['../md_docs_2ergodic-moves.html#conventions-and-common-contract',1,'']]],
  ['correctness_43',['Determinism and correctness',['../md_docs_2multithreading.html#determinism-and-correctness',1,'']]],
  ['correctness_20results_44',['Correctness results',['../md_docs_2arithmetic-backend-evaluation.html#correctness-results',1,'']]],
  ['counters_45',['Counters',['../md_docs_2metropolis-hastings.html#counters',1,'']]],
  ['coverage_46',['Coverage',['../index.html#coverage',1,'']]],
  ['critical_20fixes_47',['Release-critical fixes',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#release-critical-fixes',1,'']]],
  ['current_20reference_20suite_20status_48',['Current reference-suite status',['../index.html#current-reference-suite-status',1,'']]]
];
