var searchData=
[
  ['tag_20the_20merged_20release_0',['Step 2: Tag the merged release',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#step-2-tag-the-merged-release',1,'']]],
  ['tbb_20backed_20configurations_1',['Sequential and TBB-backed configurations',['../md_docs_2cgal-integration.html#sequential-and-tbb-backed-configurations',1,'']]],
  ['test_2',['Build and test',['../md_docs_2multithreading.html#build-and-test',1,'']]],
  ['tested_20release_20matrix_3',['Tested release matrix',['../index.html#tested-release-matrix',1,'']]],
  ['the_20archival_20handoff_4',['Step 5: Stabilize, then complete the archival handoff',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#step-5-stabilize-then-complete-the-archival-handoff',1,'']]],
  ['the_20merged_20release_5',['Step 2: Tag the merged release',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#step-2-tag-the-merged-release',1,'']]],
  ['the_20release_6',['Step 3: Publish and verify the release',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#step-3-publish-and-verify-the-release',1,'']]],
  ['the_20release_20metadata_7',['Validate and commit the release metadata',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#validate-and-commit-the-release-metadata',1,'']]],
  ['the_20release_20pull_20request_8',['Step 1: Prepare the release pull request',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#step-1-prepare-the-release-pull-request',1,'']]],
  ['the_20stable_20archival_20provenance_9',['Refresh the stable archival provenance',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#refresh-the-stable-archival-provenance',1,'']]],
  ['then_20complete_20the_20archival_20handoff_10',['Step 5: Stabilize, then complete the archival handoff',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#step-5-stabilize-then-complete-the-archival-handoff',1,'']]],
  ['theory_11',['Foundational Causal Dynamical Triangulations Theory',['../md__r_e_f_e_r_e_n_c_e_s.html#foundational-causal-dynamical-triangulations-theory',1,'']]],
  ['this_20software_12',['How to Cite This Software',['../md__r_e_f_e_r_e_n_c_e_s.html#how-to-cite-this-software',1,'']]],
  ['thread_20limit_13',['Runtime thread limit',['../md_docs_2multithreading.html#runtime-thread-limit',1,'']]],
  ['three_20dimensional_20cdt_202001_14',['Three-dimensional CDT (2001)',['../md__r_e_f_e_r_e_n_c_e_s.html#three-dimensional-cdt-2001',1,'']]],
  ['three_20dimensional_20delaunay_20complexity_15',['Three-dimensional Delaunay complexity',['../md__r_e_f_e_r_e_n_c_e_s.html#three-dimensional-delaunay-complexity',1,'']]],
  ['to_20cite_20this_20software_16',['How to Cite This Software',['../md__r_e_f_e_r_e_n_c_e_s.html#how-to-cite-this-software',1,'']]],
  ['tolerances_17',['Quantity-specific tolerances',['../md_docs_2metropolis-hastings.html#quantity-specific-tolerances',1,'']]],
  ['topology_20and_20local_20moves_18',['Simplicial Topology and Local Moves',['../md__r_e_f_e_r_e_n_c_e_s.html#simplicial-topology-and-local-moves',1,'']]],
  ['transition_20contract_19',['Metropolis-Hastings transition contract',['../md_docs_2metropolis-hastings.html',1,'']]],
  ['triangulation_20',['Generate and load an initial triangulation',['../index.html#generate-and-load-an-initial-triangulation',1,'']]],
  ['triangulation_20interchange_21',['Initial-triangulation interchange',['../dir_6e133a56364528c326e124d8bed524d8.html#initial-triangulation-interchange',1,'']]],
  ['triangulations_22',['triangulations',['../md__r_e_f_e_r_e_n_c_e_s.html#cgal-triangulations',1,'CGAL triangulations'],['../index.html#generate-many-initial-triangulations',1,'Generate many initial triangulations']]],
  ['triangulations_20theory_23',['Foundational Causal Dynamical Triangulations Theory',['../md__r_e_f_e_r_e_n_c_e_s.html#foundational-causal-dynamical-triangulations-theory',1,'']]]
];
