var searchData=
[
  ['sanitizers_0',['Sanitizers',['../index.html#sanitizers',1,'Sanitizers'],['../md_docs_2multithreading.html#sanitizers-1',1,'Sanitizers']]],
  ['scaling_20record_1',['Matched scaling record',['../md_docs_2multithreading.html#matched-scaling-record',1,'']]],
  ['scientific_20boundary_2',['Scientific boundary',['../md_docs_2comparison-harness.html#scientific-boundary',1,'']]],
  ['scope_3',['Regression-oracle scope',['../index.html#regression-oracle-scope',1,'']]],
  ['scope_20and_20limitations_4',['Release scope and limitations',['../index.html#release-scope-and-limitations',1,'']]],
  ['scope_20limits_5',['Scope limits',['../dir_6e133a56364528c326e124d8bed524d8.html#scope-limits',1,'']]],
  ['security_20and_20support_6',['Security and support',['../md__s_e_c_u_r_i_t_y.html',1,'Security and support'],['../index.html#security-and-support',1,'Security and support']]],
  ['selection_20performance_20check_7',['Move-selection performance check',['../md_docs_2reproducibility.html#move-selection-performance-check',1,'']]],
  ['sequential_20and_20tbb_20backed_20configurations_8',['Sequential and TBB-backed configurations',['../md_docs_2cgal-integration.html#sequential-and-tbb-backed-configurations',1,'']]],
  ['setup_9',['Setup',['../index.html#setup',1,'']]],
  ['simplicial_20topology_20and_20local_20moves_10',['Simplicial Topology and Local Moves',['../md__r_e_f_e_r_e_n_c_e_s.html#simplicial-topology-and-local-moves',1,'']]],
  ['smoke_20policy_11',['Render manifest and smoke policy',['../md_docs_2viewer.html#render-manifest-and-smoke-policy',1,'']]],
  ['software_12',['How to Cite This Software',['../md__r_e_f_e_r_e_n_c_e_s.html#how-to-cite-this-software',1,'']]],
  ['specific_20tolerances_13',['Quantity-specific tolerances',['../md_docs_2metropolis-hastings.html#quantity-specific-tolerances',1,'']]],
  ['sphere_20construction_14',['Delaunay empty-sphere construction',['../md__r_e_f_e_r_e_n_c_e_s.html#delaunay-empty-sphere-construction',1,'']]],
  ['spherical_20population_20estimator_15',['Spherical population estimator',['../md_docs_2cgal-integration.html#spherical-population-estimator',1,'']]],
  ['stabilize_20then_20complete_20the_20archival_20handoff_16',['Step 5: Stabilize, then complete the archival handoff',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#step-5-stabilize-then-complete-the-archival-handoff',1,'']]],
  ['stable_20archival_20provenance_17',['Refresh the stable archival provenance',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#refresh-the-stable-archival-provenance',1,'']]],
  ['state_20and_20geometry_20deltas_18',['State and geometry deltas',['../md_docs_2metropolis-hastings.html#state-and-geometry-deltas',1,'']]],
  ['static_20analysis_19',['Static Analysis',['../index.html#static-analysis',1,'']]],
  ['status_20',['status',['../index.html#archival-and-maintenance-status',1,'Archival and maintenance status'],['../index.html#current-reference-suite-status',1,'Current reference-suite status']]],
  ['step_201_3a_20prepare_20the_20release_20pull_20request_21',['Step 1: Prepare the release pull request',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#step-1-prepare-the-release-pull-request',1,'']]],
  ['step_202_3a_20tag_20the_20merged_20release_22',['Step 2: Tag the merged release',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#step-2-tag-the-merged-release',1,'']]],
  ['step_203_3a_20publish_20and_20verify_20the_20release_23',['Step 3: Publish and verify the release',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#step-3-publish-and-verify-the-release',1,'']]],
  ['step_204_3a_20clean_20up_24',['Step 4: Clean up',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#step-4-clean-up',1,'']]],
  ['step_205_3a_20stabilize_20then_20complete_20the_20archival_20handoff_25',['Step 5: Stabilize, then complete the archival handoff',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#step-5-stabilize-then-complete-the-archival-handoff',1,'']]],
  ['stream_20policy_26',['Parallel stream policy',['../md_docs_2reproducibility.html#parallel-stream-policy',1,'']]],
  ['suite_20status_27',['Current reference-suite status',['../index.html#current-reference-suite-status',1,'']]],
  ['summary_28',['Release summary',['../md__c_h_a_n_g_e_l_o_g.html#release-summary',1,'']]],
  ['support_29',['support',['../md__s_e_c_u_r_i_t_y.html',1,'Security and support'],['../index.html#security-and-support',1,'Security and support']]],
  ['supported_20dependency_20and_20compiler_20contract_30',['Supported dependency and compiler contract',['../md_docs_2cgal-integration.html#supported-dependency-and-compiler-contract',1,'']]],
  ['supported_20execution_20boundary_31',['Supported execution boundary',['../md_docs_2multithreading.html#supported-execution-boundary',1,'']]],
  ['supported_20workflow_32',['Supported workflow',['../md_docs_2viewer.html#supported-workflow',1,'']]]
];
