var searchData=
[
  ['sanitizers_0',['Sanitizers',['../index.html#sanitizers',1,'Sanitizers'],['../md_docs_2multithreading.html#sanitizers-1',1,'Sanitizers']]],
  ['scaling_20record_1',['Matched scaling record',['../md_docs_2multithreading.html#matched-scaling-record',1,'']]],
  ['scientific_20boundary_2',['Scientific boundary',['../md_docs_2comparison-harness.html#scientific-boundary',1,'']]],
  ['scope_3',['Regression-oracle scope',['../index.html#regression-oracle-scope',1,'']]],
  ['scope_20limits_4',['Scope limits',['../dir_6e133a56364528c326e124d8bed524d8.html#scope-limits',1,'']]],
  ['selection_20performance_20check_5',['Move-selection performance check',['../md_docs_2reproducibility.html#move-selection-performance-check',1,'']]],
  ['sequential_20and_20tbb_20backed_20configurations_6',['Sequential and TBB-backed configurations',['../md_docs_2cgal-integration.html#sequential-and-tbb-backed-configurations',1,'']]],
  ['setup_7',['Setup',['../index.html#setup',1,'']]],
  ['simplicial_20topology_20and_20local_20moves_8',['Simplicial Topology and Local Moves',['../md__r_e_f_e_r_e_n_c_e_s.html#simplicial-topology-and-local-moves',1,'']]],
  ['software_9',['How to Cite This Software',['../md__r_e_f_e_r_e_n_c_e_s.html#how-to-cite-this-software',1,'']]],
  ['specific_20tolerances_10',['Quantity-specific tolerances',['../md_docs_2metropolis-hastings.html#quantity-specific-tolerances',1,'']]],
  ['spherical_20population_20estimator_11',['Spherical population estimator',['../md_docs_2cgal-integration.html#spherical-population-estimator',1,'']]],
  ['state_20and_20geometry_20deltas_12',['State and geometry deltas',['../md_docs_2metropolis-hastings.html#state-and-geometry-deltas',1,'']]],
  ['static_20analysis_13',['Static Analysis',['../index.html#static-analysis',1,'']]],
  ['status_14',['status',['../index.html#current-reference-suite-status',1,'Current reference-suite status'],['../index.html#maintenance-status',1,'Maintenance status']]],
  ['step_201_3a_20prepare_20the_20release_20pull_20request_15',['Step 1: Prepare the release pull request',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#step-1-prepare-the-release-pull-request',1,'']]],
  ['step_202_3a_20tag_20the_20merged_20release_16',['Step 2: Tag the merged release',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#step-2-tag-the-merged-release',1,'']]],
  ['step_203_3a_20publish_20and_20verify_20the_20release_17',['Step 3: Publish and verify the release',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#step-3-publish-and-verify-the-release',1,'']]],
  ['step_204_3a_20clean_20up_18',['Step 4: Clean up',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#step-4-clean-up',1,'']]],
  ['stream_20policy_19',['Parallel stream policy',['../md_docs_2reproducibility.html#parallel-stream-policy',1,'']]],
  ['suite_20status_20',['Current reference-suite status',['../index.html#current-reference-suite-status',1,'']]],
  ['supported_20dependency_20and_20compiler_20contract_21',['Supported dependency and compiler contract',['../md_docs_2cgal-integration.html#supported-dependency-and-compiler-contract',1,'']]],
  ['supported_20execution_20boundary_22',['Supported execution boundary',['../md_docs_2multithreading.html#supported-execution-boundary',1,'']]]
];
