var searchData=
[
  ['pachner_20moves_0',['Pachner moves',['../md__r_e_f_e_r_e_n_c_e_s.html#pachner-moves',1,'']]],
  ['package_1',['CDT++ reference fixture package',['../dir_6e133a56364528c326e124d8bed524d8.html#cdt-reference-fixture-package',1,'']]],
  ['package_20layout_2',['Package layout',['../dir_6e133a56364528c326e124d8bed524d8.html#package-layout',1,'']]],
  ['packaging_3',['Packaging',['../md_docs_2arithmetic-backend-evaluation.html#packaging',1,'']]],
  ['parallel_20stream_20policy_4',['Parallel stream policy',['../md_docs_2reproducibility.html#parallel-stream-policy',1,'']]],
  ['pcg_20random_20number_20generators_5',['PCG random-number generators',['../md__r_e_f_e_r_e_n_c_e_s.html#pcg-random-number-generators',1,'']]],
  ['performance_6',['Performance',['../md__c_h_a_n_g_e_l_o_g.html#performance',1,'']]],
  ['performance_20baseline_7',['Reproducible performance baseline',['../md_docs_2cgal-integration.html#reproducible-performance-baseline',1,'']]],
  ['performance_20check_8',['Move-selection performance check',['../md_docs_2reproducibility.html#move-selection-performance-check',1,'']]],
  ['performance_20results_9',['Performance results',['../md_docs_2arithmetic-backend-evaluation.html#performance-results',1,'']]],
  ['persistence_20contract_10',['Persistence contract',['../md_docs_2reproducibility.html#persistence-contract',1,'']]],
  ['plusplus_11',['CDT-plusplus',['../index.html',1,'']]],
  ['points_12',['Metadata, insertion, and duplicate points',['../md_docs_2cgal-integration.html#metadata-insertion-and-duplicate-points',1,'']]],
  ['policy_13',['policy',['../md_docs_2api-boundary.html#compatibility-policy',1,'Compatibility policy'],['../md_docs_2api-boundary.html#generated-reference-policy',1,'Generated reference policy'],['../md_docs_2cgal-integration.html#kernel-and-exact-arithmetic-policy',1,'Kernel and exact-arithmetic policy'],['../md_docs_2metropolis-hastings.html#numerical-policy',1,'Numerical policy'],['../md_docs_2reproducibility.html#parallel-stream-policy',1,'Parallel stream policy'],['../md_docs_2viewer.html#render-manifest-and-smoke-policy',1,'Render manifest and smoke policy']]],
  ['population_20estimator_14',['Spherical population estimator',['../md_docs_2cgal-integration.html#spherical-population-estimator',1,'']]],
  ['predicates_15',['Robust geometric predicates',['../md__r_e_f_e_r_e_n_c_e_s.html#robust-geometric-predicates',1,'']]],
  ['prepare_20the_20release_20pull_20request_16',['Step 1: Prepare the release pull request',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#step-1-prepare-the-release-pull-request',1,'']]],
  ['prerequisites_17',['Prerequisites',['../index.html#prerequisites',1,'']]],
  ['producer_20contract_18',['Producer contract',['../md_docs_2comparison-harness.html#producer-contract',1,'']]],
  ['production_20inventory_19',['Production inventory',['../md_docs_2arithmetic-backend-evaluation.html#production-inventory',1,'']]],
  ['production_20usage_20inventory_20',['Production usage inventory',['../md_docs_2cgal-integration.html#production-usage-inventory',1,'']]],
  ['proposal_20kernel_21',['Proposal kernel',['../md_docs_2metropolis-hastings.html#proposal-kernel',1,'']]],
  ['protocol_20and_20provenance_22',['Evaluation protocol and provenance',['../md_docs_2arithmetic-backend-evaluation.html#evaluation-protocol-and-provenance',1,'']]],
  ['provenance_23',['provenance',['../md_docs_2arithmetic-backend-evaluation.html#evaluation-protocol-and-provenance',1,'Evaluation protocol and provenance'],['../md_docs_2_r_e_l_e_a_s_i_n_g.html#refresh-the-stable-archival-provenance',1,'Refresh the stable archival provenance']]],
  ['publish_20and_20verify_20the_20release_24',['Step 3: Publish and verify the release',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#step-3-publish-and-verify-the-release',1,'']]],
  ['pull_20request_25',['Step 1: Prepare the release pull request',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#step-1-prepare-the-release-pull-request',1,'']]]
];
