var searchData=
[
  ['action_0',['Regge Calculus and Discrete Action',['../md__r_e_f_e_r_e_n_c_e_s.html#regge-calculus-and-discrete-action',1,'']]],
  ['action_20and_20metropolis_20hastings_20arithmetic_1',['Action and Metropolis-Hastings arithmetic',['../md_docs_2arithmetic-backend-evaluation.html#action-and-metropolis-hastings-arithmetic',1,'']]],
  ['action_20conventions_2',['Action conventions',['../md_docs_2metropolis-hastings.html#action-conventions',1,'']]],
  ['added_3',['Added',['../md__c_h_a_n_g_e_l_o_g.html#added',1,'Added'],['../md__c_h_a_n_g_e_l_o_g.html#added-1',1,'Added'],['../md__c_h_a_n_g_e_l_o_g.html#added-2',1,'Added']]],
  ['admissibility_4',['Checked flips and CDT admissibility',['../md_docs_2cgal-integration.html#checked-flips-and-cdt-admissibility',1,'']]],
  ['algorithm_5',['algorithm',['../md__r_e_f_e_r_e_n_c_e_s.html#metropolis-algorithm',1,'Metropolis algorithm'],['../md__r_e_f_e_r_e_n_c_e_s.html#metropolis-hastings-algorithm',1,'Metropolis-Hastings algorithm']]],
  ['alternatives_6',['Alternatives',['../md_docs_2arithmetic-backend-evaluation.html#alternatives',1,'']]],
  ['analysis_7',['Static Analysis',['../index.html#static-analysis',1,'']]],
  ['and_20cdt_20admissibility_8',['Checked flips and CDT admissibility',['../md_docs_2cgal-integration.html#checked-flips-and-cdt-admissibility',1,'']]],
  ['and_20citations_9',['References and Citations',['../md__r_e_f_e_r_e_n_c_e_s.html',1,'']]],
  ['and_20commit_20the_20release_20metadata_10',['Validate and commit the release metadata',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#validate-and-commit-the-release-metadata',1,'']]],
  ['and_20common_20contract_11',['Conventions and common contract',['../md_docs_2ergodic-moves.html#conventions-and-common-contract',1,'']]],
  ['and_20compiler_20contract_12',['Supported dependency and compiler contract',['../md_docs_2cgal-integration.html#supported-dependency-and-compiler-contract',1,'']]],
  ['and_20correctness_13',['Determinism and correctness',['../md_docs_2multithreading.html#determinism-and-correctness',1,'']]],
  ['and_20delaunay_20expected_20complexity_14',['Random Voronoi and Delaunay expected complexity',['../md__r_e_f_e_r_e_n_c_e_s.html#random-voronoi-and-delaunay-expected-complexity',1,'']]],
  ['and_20discrete_20action_15',['Regge Calculus and Discrete Action',['../md__r_e_f_e_r_e_n_c_e_s.html#regge-calculus-and-discrete-action',1,'']]],
  ['and_20duplicate_20points_16',['Metadata, insertion, and duplicate points',['../md_docs_2cgal-integration.html#metadata-insertion-and-duplicate-points',1,'']]],
  ['and_20exact_20arithmetic_20policy_17',['Kernel and exact-arithmetic policy',['../md_docs_2cgal-integration.html#kernel-and-exact-arithmetic-policy',1,'']]],
  ['and_20geometry_20deltas_18',['State and geometry deltas',['../md_docs_2metropolis-hastings.html#state-and-geometry-deltas',1,'']]],
  ['and_20lifetime_20rules_19',['Mutation and lifetime rules',['../md_docs_2cgal-integration.html#mutation-and-lifetime-rules',1,'']]],
  ['and_20limitations_20',['Release scope and limitations',['../index.html#release-scope-and-limitations',1,'']]],
  ['and_20local_20moves_21',['Simplicial Topology and Local Moves',['../md__r_e_f_e_r_e_n_c_e_s.html#simplicial-topology-and-local-moves',1,'']]],
  ['and_20maintenance_20status_22',['Archival and maintenance status',['../index.html#archival-and-maintenance-status',1,'']]],
  ['and_20metropolis_20hastings_20arithmetic_23',['Action and Metropolis-Hastings arithmetic',['../md_docs_2arithmetic-backend-evaluation.html#action-and-metropolis-hastings-arithmetic',1,'']]],
  ['and_20ownership_20behavior_24',['Failure and ownership behavior',['../md_docs_2cpp-api-quickstart.html#failure-and-ownership-behavior',1,'']]],
  ['and_20provenance_25',['Evaluation protocol and provenance',['../md_docs_2arithmetic-backend-evaluation.html#evaluation-protocol-and-provenance',1,'']]],
  ['and_20random_20number_20generation_26',['Computational Geometry and Random-Number Generation',['../md__r_e_f_e_r_e_n_c_e_s.html#computational-geometry-and-random-number-generation',1,'']]],
  ['and_20rollback_20gates_27',['Migration and rollback gates',['../md_docs_2arithmetic-backend-evaluation.html#migration-and-rollback-gates',1,'']]],
  ['and_20run_28',['Build and run',['../md_docs_2cpp-api-quickstart.html#build-and-run',1,'']]],
  ['and_20smoke_20policy_29',['Render manifest and smoke policy',['../md_docs_2viewer.html#render-manifest-and-smoke-policy',1,'']]],
  ['and_20support_30',['and support',['../md__s_e_c_u_r_i_t_y.html',1,'Security and support'],['../index.html#security-and-support',1,'Security and support']]],
  ['and_20tbb_20backed_20configurations_31',['Sequential and TBB-backed configurations',['../md_docs_2cgal-integration.html#sequential-and-tbb-backed-configurations',1,'']]],
  ['and_20test_32',['Build and test',['../md_docs_2multithreading.html#build-and-test',1,'']]],
  ['and_20verify_20the_20release_33',['Step 3: Publish and verify the release',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#step-3-publish-and-verify-the-release',1,'']]],
  ['and_20visual_20artifact_20contract_34',['Viewer and visual-artifact contract',['../md_docs_2viewer.html',1,'']]],
  ['api_20boundary_35',['C++ API boundary',['../md_docs_2api-boundary.html',1,'']]],
  ['api_20quickstart_36',['C++ API quickstart',['../md_docs_2cpp-api-quickstart.html',1,'']]],
  ['archival_20and_20maintenance_20status_37',['Archival and maintenance status',['../index.html#archival-and-maintenance-status',1,'']]],
  ['archival_20handoff_38',['Step 5: Stabilize, then complete the archival handoff',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#step-5-stabilize-then-complete-the-archival-handoff',1,'']]],
  ['archival_20provenance_39',['Refresh the stable archival provenance',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#refresh-the-stable-archival-provenance',1,'']]],
  ['arithmetic_40',['Action and Metropolis-Hastings arithmetic',['../md_docs_2arithmetic-backend-evaluation.html#action-and-metropolis-hastings-arithmetic',1,'']]],
  ['arithmetic_20evaluation_41',['GMP/MPFR-free arithmetic evaluation',['../md_docs_2arithmetic-backend-evaluation.html',1,'']]],
  ['arithmetic_20policy_42',['Kernel and exact-arithmetic policy',['../md_docs_2cgal-integration.html#kernel-and-exact-arithmetic-policy',1,'']]],
  ['artifact_20contract_43',['Viewer and visual-artifact contract',['../md_docs_2viewer.html',1,'']]],
  ['artifact_20layout_44',['Artifact layout',['../md_docs_2comparison-harness.html#artifact-layout',1,'']]],
  ['audit_45',['2+1D CDT ergodic move audit',['../md_docs_2ergodic-moves.html',1,'']]]
];
