var searchData=
[
  ['maintenance_0',['Maintenance',['../md__c_h_a_n_g_e_l_o_g.html#maintenance',1,'Maintenance'],['../md__c_h_a_n_g_e_l_o_g.html#maintenance-1',1,'Maintenance'],['../md__c_h_a_n_g_e_l_o_g.html#maintenance-2',1,'Maintenance']]],
  ['maintenance_1',['vcpkg maintenance',['../index.html#vcpkg-maintenance',1,'']]],
  ['maintenance_20status_2',['Archival and maintenance status',['../index.html#archival-and-maintenance-status',1,'']]],
  ['manifest_20and_20smoke_20policy_3',['Render manifest and smoke policy',['../md_docs_2viewer.html#render-manifest-and-smoke-policy',1,'']]],
  ['matched_20scaling_20record_4',['Matched scaling record',['../md_docs_2multithreading.html#matched-scaling-record',1,'']]],
  ['matrix_5',['Tested release matrix',['../index.html#tested-release-matrix',1,'']]],
  ['merged_20release_6',['Step 2: Tag the merged release',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#step-2-tag-the-merged-release',1,'']]],
  ['metadata_7',['metadata',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#update-release-metadata',1,'Update release metadata'],['../md_docs_2_r_e_l_e_a_s_i_n_g.html#validate-and-commit-the-release-metadata',1,'Validate and commit the release metadata']]],
  ['metadata_20insertion_20and_20duplicate_20points_8',['Metadata, insertion, and duplicate points',['../md_docs_2cgal-integration.html#metadata-insertion-and-duplicate-points',1,'']]],
  ['methods_9',['Monte Carlo Methods',['../md__r_e_f_e_r_e_n_c_e_s.html#monte-carlo-methods',1,'']]],
  ['metropolis_20algorithm_10',['Metropolis algorithm',['../md__r_e_f_e_r_e_n_c_e_s.html#metropolis-algorithm',1,'']]],
  ['metropolis_20hastings_20algorithm_11',['Metropolis-Hastings algorithm',['../md__r_e_f_e_r_e_n_c_e_s.html#metropolis-hastings-algorithm',1,'']]],
  ['metropolis_20hastings_20arithmetic_12',['Action and Metropolis-Hastings arithmetic',['../md_docs_2arithmetic-backend-evaluation.html#action-and-metropolis-hastings-arithmetic',1,'']]],
  ['metropolis_20hastings_20transition_20contract_13',['Metropolis-Hastings transition contract',['../md_docs_2metropolis-hastings.html',1,'']]],
  ['migration_20and_20rollback_20gates_14',['Migration and rollback gates',['../md_docs_2arithmetic-backend-evaluation.html#migration-and-rollback-gates',1,'']]],
  ['monte_20carlo_20methods_15',['Monte Carlo Methods',['../md__r_e_f_e_r_e_n_c_e_s.html#monte-carlo-methods',1,'']]],
  ['move_20audit_16',['2+1D CDT ergodic move audit',['../md_docs_2ergodic-moves.html',1,'']]],
  ['move_20by_20move_20record_17',['Move-by-move record',['../md_docs_2ergodic-moves.html#move-by-move-record',1,'']]],
  ['move_20record_18',['Move-by-move record',['../md_docs_2ergodic-moves.html#move-by-move-record',1,'']]],
  ['move_20selection_20performance_20check_19',['Move-selection performance check',['../md_docs_2reproducibility.html#move-selection-performance-check',1,'']]],
  ['moves_20',['Simplicial Topology and Local Moves',['../md__r_e_f_e_r_e_n_c_e_s.html#simplicial-topology-and-local-moves',1,'']]],
  ['moves_21',['Pachner moves',['../md__r_e_f_e_r_e_n_c_e_s.html#pachner-moves',1,'']]],
  ['mpfr_20free_20arithmetic_20evaluation_22',['GMP/MPFR-free arithmetic evaluation',['../md_docs_2arithmetic-backend-evaluation.html',1,'']]],
  ['multithreaded_20cgal_20contract_23',['Multithreaded CGAL contract',['../md_docs_2multithreading.html',1,'']]],
  ['mutation_20and_20lifetime_20rules_24',['Mutation and lifetime rules',['../md_docs_2cgal-integration.html#mutation-and-lifetime-rules',1,'']]]
];
