var searchData=
[
  ['pachner_20moves_0',['Pachner moves',['../md__r_e_f_e_r_e_n_c_e_s.html#pachner-moves',1,'']]],
  ['package_1',['CDT++ reference fixture package',['../dir_6e133a56364528c326e124d8bed524d8.html#cdt-reference-fixture-package',1,'']]],
  ['package_20layout_2',['Package layout',['../dir_6e133a56364528c326e124d8bed524d8.html#package-layout',1,'']]],
  ['packaging_3',['Packaging',['../md_docs_2arithmetic-backend-evaluation.html#packaging',1,'']]],
  ['parallel_20stream_20policy_4',['Parallel stream policy',['../md_docs_2reproducibility.html#parallel-stream-policy',1,'']]],
  ['pcg_20random_20number_20generators_5',['PCG random-number generators',['../md__r_e_f_e_r_e_n_c_e_s.html#pcg-random-number-generators',1,'']]],
  ['performance_20baseline_6',['Reproducible performance baseline',['../md_docs_2cgal-integration.html#reproducible-performance-baseline',1,'']]],
  ['performance_20check_7',['Move-selection performance check',['../md_docs_2reproducibility.html#move-selection-performance-check',1,'']]],
  ['performance_20results_8',['Performance results',['../md_docs_2arithmetic-backend-evaluation.html#performance-results',1,'']]],
  ['persistence_20contract_9',['Persistence contract',['../md_docs_2reproducibility.html#persistence-contract',1,'']]],
  ['plusplus_10',['CDT-plusplus',['../index.html',1,'']]],
  ['points_11',['Metadata, insertion, and duplicate points',['../md_docs_2cgal-integration.html#metadata-insertion-and-duplicate-points',1,'']]],
  ['policy_12',['policy',['../md_docs_2api-boundary.html#compatibility-policy',1,'Compatibility policy'],['../md_docs_2cgal-integration.html#kernel-and-exact-arithmetic-policy',1,'Kernel and exact-arithmetic policy'],['../md_docs_2metropolis-hastings.html#numerical-policy',1,'Numerical policy'],['../md_docs_2reproducibility.html#parallel-stream-policy',1,'Parallel stream policy']]],
  ['population_20estimator_13',['Spherical population estimator',['../md_docs_2cgal-integration.html#spherical-population-estimator',1,'']]],
  ['prepare_20the_20release_20pull_20request_14',['Step 1: Prepare the release pull request',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#step-1-prepare-the-release-pull-request',1,'']]],
  ['prerequisites_15',['Prerequisites',['../index.html#prerequisites',1,'']]],
  ['producer_20contract_16',['Producer contract',['../md_docs_2comparison-harness.html#producer-contract',1,'']]],
  ['production_20inventory_17',['Production inventory',['../md_docs_2arithmetic-backend-evaluation.html#production-inventory',1,'']]],
  ['production_20usage_20inventory_18',['Production usage inventory',['../md_docs_2cgal-integration.html#production-usage-inventory',1,'']]],
  ['project_20layout_19',['Project Layout',['../index.html#project-layout',1,'']]],
  ['proposal_20kernel_20',['Proposal kernel',['../md_docs_2metropolis-hastings.html#proposal-kernel',1,'']]],
  ['protocol_20and_20provenance_21',['Evaluation protocol and provenance',['../md_docs_2arithmetic-backend-evaluation.html#evaluation-protocol-and-provenance',1,'']]],
  ['provenance_22',['Evaluation protocol and provenance',['../md_docs_2arithmetic-backend-evaluation.html#evaluation-protocol-and-provenance',1,'']]],
  ['publish_20and_20verify_20the_20release_23',['Step 3: Publish and verify the release',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#step-3-publish-and-verify-the-release',1,'']]],
  ['pull_20request_24',['Step 1: Prepare the release pull request',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#step-1-prepare-the-release-pull-request',1,'']]]
];
