var searchData=
[
  ['random_20number_20generation_0',['Computational Geometry and Random-Number Generation',['../md__r_e_f_e_r_e_n_c_e_s.html#computational-geometry-and-random-number-generation',1,'']]],
  ['random_20number_20generators_1',['PCG random-number generators',['../md__r_e_f_e_r_e_n_c_e_s.html#pcg-random-number-generators',1,'']]],
  ['random_20runs_2',['Reproducible random runs',['../md_docs_2reproducibility.html',1,'']]],
  ['random_20voronoi_20and_20delaunay_20expected_20complexity_3',['Random Voronoi and Delaunay expected complexity',['../md__r_e_f_e_r_e_n_c_e_s.html#random-voronoi-and-delaunay-expected-complexity',1,'']]],
  ['record_4',['record',['../md_docs_2multithreading.html#matched-scaling-record',1,'Matched scaling record'],['../md_docs_2ergodic-moves.html#move-by-move-record',1,'Move-by-move record'],['../md_docs_2ergodic-moves.html#verification-record',1,'Verification record']]],
  ['reference_5',['Command-line reference',['../index.html#command-line-reference',1,'']]],
  ['reference_20fixture_20package_6',['CDT++ reference fixture package',['../dir_6e133a56364528c326e124d8bed524d8.html#cdt-reference-fixture-package',1,'']]],
  ['reference_20suite_20status_7',['Current reference-suite status',['../index.html#current-reference-suite-status',1,'']]],
  ['references_8',['References',['../md_docs_2metropolis-hastings.html#references',1,'']]],
  ['references_20and_20citations_9',['References and Citations',['../md__r_e_f_e_r_e_n_c_e_s.html',1,'']]],
  ['regeneration_10',['Regeneration',['../dir_6e133a56364528c326e124d8bed524d8.html#regeneration',1,'']]],
  ['regge_20calculus_11',['Regge calculus',['../md__r_e_f_e_r_e_n_c_e_s.html#regge-calculus',1,'']]],
  ['regge_20calculus_20and_20discrete_20action_12',['Regge Calculus and Discrete Action',['../md__r_e_f_e_r_e_n_c_e_s.html#regge-calculus-and-discrete-action',1,'']]],
  ['regression_20oracle_20scope_13',['Regression-oracle scope',['../index.html#regression-oracle-scope',1,'']]],
  ['release_14',['release',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#step-2-tag-the-merged-release',1,'Step 2: Tag the merged release'],['../md_docs_2_r_e_l_e_a_s_i_n_g.html#step-3-publish-and-verify-the-release',1,'Step 3: Publish and verify the release']]],
  ['release_20branch_15',['Validate the release branch',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#validate-the-release-branch',1,'']]],
  ['release_20critical_20fixes_16',['Release-critical fixes',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#release-critical-fixes',1,'']]],
  ['release_20metadata_17',['Update release metadata',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#update-release-metadata',1,'']]],
  ['release_20pull_20request_18',['Step 1: Prepare the release pull request',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#step-1-prepare-the-release-pull-request',1,'']]],
  ['releasing_20cdt_19',['Releasing CDT++',['../md_docs_2_r_e_l_e_a_s_i_n_g.html',1,'']]],
  ['reproducible_20performance_20baseline_20',['Reproducible performance baseline',['../md_docs_2cgal-integration.html#reproducible-performance-baseline',1,'']]],
  ['reproducible_20random_20runs_21',['Reproducible random runs',['../md_docs_2reproducibility.html',1,'']]],
  ['reproduction_22',['Offline reproduction',['../md_docs_2comparison-harness.html#offline-reproduction',1,'']]],
  ['request_23',['Step 1: Prepare the release pull request',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#step-1-prepare-the-release-pull-request',1,'']]],
  ['roadmap_24',['Roadmap',['../index.html#roadmap',1,'']]],
  ['rules_25',['Mutation and lifetime rules',['../md_docs_2cgal-integration.html#mutation-and-lifetime-rules',1,'']]],
  ['runs_26',['Reproducible random runs',['../md_docs_2reproducibility.html',1,'']]],
  ['runtime_20thread_20limit_27',['Runtime thread limit',['../md_docs_2multithreading.html#runtime-thread-limit',1,'']]],
  ['rust_20comparison_20harness_28',['Offline C++/Rust comparison harness',['../md_docs_2comparison-harness.html',1,'']]],
  ['rust_20consumption_29',['Rust consumption',['../dir_6e133a56364528c326e124d8bed524d8.html#rust-consumption',1,'']]]
];
