var searchData=
[
  ['action_0',['Regge Calculus and Discrete Action',['../md__r_e_f_e_r_e_n_c_e_s.html#regge-calculus-and-discrete-action',1,'']]],
  ['admissibility_1',['Checked flips and CDT admissibility',['../md_docs_2cgal-integration.html#checked-flips-and-cdt-admissibility',1,'']]],
  ['algorithm_2',['Metropolis-Hastings algorithm',['../md__r_e_f_e_r_e_n_c_e_s.html#metropolis-hastings-algorithm',1,'']]],
  ['analysis_3',['Static Analysis',['../index.html#static-analysis',1,'']]],
  ['and_20cdt_20admissibility_4',['Checked flips and CDT admissibility',['../md_docs_2cgal-integration.html#checked-flips-and-cdt-admissibility',1,'']]],
  ['and_20citations_5',['References and Citations',['../md__r_e_f_e_r_e_n_c_e_s.html',1,'']]],
  ['and_20common_20contract_6',['Conventions and common contract',['../md_docs_2ergodic-moves.html#conventions-and-common-contract',1,'']]],
  ['and_20compiler_20contract_7',['Supported dependency and compiler contract',['../md_docs_2cgal-integration.html#supported-dependency-and-compiler-contract',1,'']]],
  ['and_20correctness_8',['Determinism and correctness',['../md_docs_2multithreading.html#determinism-and-correctness',1,'']]],
  ['and_20discrete_20action_9',['Regge Calculus and Discrete Action',['../md__r_e_f_e_r_e_n_c_e_s.html#regge-calculus-and-discrete-action',1,'']]],
  ['and_20duplicate_20points_10',['Metadata, insertion, and duplicate points',['../md_docs_2cgal-integration.html#metadata-insertion-and-duplicate-points',1,'']]],
  ['and_20exact_20arithmetic_20policy_11',['Kernel and exact-arithmetic policy',['../md_docs_2cgal-integration.html#kernel-and-exact-arithmetic-policy',1,'']]],
  ['and_20geometry_20deltas_12',['State and geometry deltas',['../md_docs_2metropolis-hastings.html#state-and-geometry-deltas',1,'']]],
  ['and_20lifetime_20rules_13',['Mutation and lifetime rules',['../md_docs_2cgal-integration.html#mutation-and-lifetime-rules',1,'']]],
  ['and_20local_20moves_14',['Simplicial Topology and Local Moves',['../md__r_e_f_e_r_e_n_c_e_s.html#simplicial-topology-and-local-moves',1,'']]],
  ['and_20random_20number_20generation_15',['Computational Geometry and Random-Number Generation',['../md__r_e_f_e_r_e_n_c_e_s.html#computational-geometry-and-random-number-generation',1,'']]],
  ['and_20tbb_20backed_20configurations_16',['Sequential and TBB-backed configurations',['../md_docs_2cgal-integration.html#sequential-and-tbb-backed-configurations',1,'']]],
  ['and_20test_17',['Build and test',['../md_docs_2multithreading.html#build-and-test',1,'']]],
  ['and_20verify_20the_20release_18',['Step 3: Publish and verify the release',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#step-3-publish-and-verify-the-release',1,'']]],
  ['api_20boundary_19',['C++ API boundary',['../md_docs_2api-boundary.html',1,'']]],
  ['arithmetic_20policy_20',['Kernel and exact-arithmetic policy',['../md_docs_2cgal-integration.html#kernel-and-exact-arithmetic-policy',1,'']]],
  ['audit_21',['2+1D CDT ergodic move audit',['../md_docs_2ergodic-moves.html',1,'']]]
];
