var searchData=
[
  ['table_20of_20contents_0',['Table of contents',['../index.html#table-of-contents',1,'']]],
  ['tag_20the_20merged_20release_1',['Step 2: Tag the merged release',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#step-2-tag-the-merged-release',1,'']]],
  ['tbb_20backed_20configurations_2',['Sequential and TBB-backed configurations',['../md_docs_2cgal-integration.html#sequential-and-tbb-backed-configurations',1,'']]],
  ['test_3',['Build and test',['../md_docs_2multithreading.html#build-and-test',1,'']]],
  ['tested_20release_20matrix_4',['Tested release matrix',['../index.html#tested-release-matrix',1,'']]],
  ['testing_5',['Testing',['../index.html#testing',1,'']]],
  ['the_20archival_20handoff_6',['Step 5: Stabilize, then complete the archival handoff',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#step-5-stabilize-then-complete-the-archival-handoff',1,'']]],
  ['the_20merged_20release_7',['Step 2: Tag the merged release',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#step-2-tag-the-merged-release',1,'']]],
  ['the_20release_8',['Step 3: Publish and verify the release',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#step-3-publish-and-verify-the-release',1,'']]],
  ['the_20release_20metadata_9',['Validate and commit the release metadata',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#validate-and-commit-the-release-metadata',1,'']]],
  ['the_20release_20pull_20request_10',['Step 1: Prepare the release pull request',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#step-1-prepare-the-release-pull-request',1,'']]],
  ['the_20stable_20archival_20provenance_11',['Refresh the stable archival provenance',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#refresh-the-stable-archival-provenance',1,'']]],
  ['then_20complete_20the_20archival_20handoff_12',['Step 5: Stabilize, then complete the archival handoff',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#step-5-stabilize-then-complete-the-archival-handoff',1,'']]],
  ['theory_13',['Foundational Causal Dynamical Triangulations Theory',['../md__r_e_f_e_r_e_n_c_e_s.html#foundational-causal-dynamical-triangulations-theory',1,'']]],
  ['this_20software_14',['How to Cite This Software',['../md__r_e_f_e_r_e_n_c_e_s.html#how-to-cite-this-software',1,'']]],
  ['thread_20limit_15',['Runtime thread limit',['../md_docs_2multithreading.html#runtime-thread-limit',1,'']]],
  ['three_20dimensional_20cdt_202001_16',['Three-dimensional CDT (2001)',['../md__r_e_f_e_r_e_n_c_e_s.html#three-dimensional-cdt-2001',1,'']]],
  ['three_20dimensional_20delaunay_20complexity_17',['Three-dimensional Delaunay complexity',['../md__r_e_f_e_r_e_n_c_e_s.html#three-dimensional-delaunay-complexity',1,'']]],
  ['to_20cite_20this_20software_18',['How to Cite This Software',['../md__r_e_f_e_r_e_n_c_e_s.html#how-to-cite-this-software',1,'']]],
  ['tolerances_19',['Quantity-specific tolerances',['../md_docs_2metropolis-hastings.html#quantity-specific-tolerances',1,'']]],
  ['topology_20and_20local_20moves_20',['Simplicial Topology and Local Moves',['../md__r_e_f_e_r_e_n_c_e_s.html#simplicial-topology-and-local-moves',1,'']]],
  ['transition_20contract_21',['Metropolis-Hastings transition contract',['../md_docs_2metropolis-hastings.html',1,'']]],
  ['triangulations_22',['CGAL triangulations',['../md__r_e_f_e_r_e_n_c_e_s.html#cgal-triangulations',1,'']]],
  ['triangulations_20theory_23',['Foundational Causal Dynamical Triangulations Theory',['../md__r_e_f_e_r_e_n_c_e_s.html#foundational-causal-dynamical-triangulations-theory',1,'']]]
];
