var searchData=
[
  ['c_20api_0',['C++ API',['../index.html#c-api',1,'']]],
  ['c_20api_20boundary_1',['C++ API boundary',['../md_docs_2api-boundary.html',1,'']]],
  ['c_20api_20quickstart_2',['C++ API quickstart',['../md_docs_2cpp-api-quickstart.html',1,'']]],
  ['c_20rust_20comparison_20harness_3',['Offline C++/Rust comparison harness',['../md_docs_2comparison-harness.html',1,'']]],
  ['calculus_4',['Regge calculus',['../md__r_e_f_e_r_e_n_c_e_s.html#regge-calculus',1,'']]],
  ['calculus_20and_20discrete_20action_5',['Regge Calculus and Discrete Action',['../md__r_e_f_e_r_e_n_c_e_s.html#regge-calculus-and-discrete-action',1,'']]],
  ['carlo_20methods_6',['Monte Carlo Methods',['../md__r_e_f_e_r_e_n_c_e_s.html#monte-carlo-methods',1,'']]],
  ['causal_20dynamical_20triangulations_20theory_7',['Foundational Causal Dynamical Triangulations Theory',['../md__r_e_f_e_r_e_n_c_e_s.html#foundational-causal-dynamical-triangulations-theory',1,'']]],
  ['cdt_8',['CDT',['../index.html#citing-cdt',1,'Citing CDT++'],['../md_docs_2_r_e_l_e_a_s_i_n_g.html',1,'Releasing CDT++']]],
  ['cdt_202001_9',['Three-dimensional CDT (2001)',['../md__r_e_f_e_r_e_n_c_e_s.html#three-dimensional-cdt-2001',1,'']]],
  ['cdt_20admissibility_10',['Checked flips and CDT admissibility',['../md_docs_2cgal-integration.html#checked-flips-and-cdt-admissibility',1,'']]],
  ['cdt_20ergodic_20move_20audit_11',['2+1D CDT ergodic move audit',['../md_docs_2ergodic-moves.html',1,'']]],
  ['cdt_20framework_12',['Original CDT framework',['../md__r_e_f_e_r_e_n_c_e_s.html#original-cdt-framework',1,'']]],
  ['cdt_20framework_202001_13',['CDT framework (2001)',['../md__r_e_f_e_r_e_n_c_e_s.html#cdt-framework-2001',1,'']]],
  ['cdt_20plusplus_14',['CDT-plusplus',['../index.html',1,'']]],
  ['cdt_20reference_20fixture_20package_15',['CDT++ reference fixture package',['../dir_6e133a56364528c326e124d8bed524d8.html#cdt-reference-fixture-package',1,'']]],
  ['cgal_206_202_20integration_20contract_16',['CGAL 6.2 integration contract',['../md_docs_2cgal-integration.html',1,'']]],
  ['cgal_20contract_17',['Multithreaded CGAL contract',['../md_docs_2multithreading.html',1,'']]],
  ['cgal_20design_18',['CGAL design',['../md__r_e_f_e_r_e_n_c_e_s.html#cgal-design',1,'']]],
  ['cgal_20triangulations_19',['CGAL triangulations',['../md__r_e_f_e_r_e_n_c_e_s.html#cgal-triangulations',1,'']]],
  ['changed_20',['Changed',['../md__c_h_a_n_g_e_l_o_g.html#changed',1,'Changed'],['../md__c_h_a_n_g_e_l_o_g.html#changed-1',1,'Changed']]],
  ['changelog_21',['Changelog',['../md__c_h_a_n_g_e_l_o_g.html',1,'']]],
  ['check_22',['Move-selection performance check',['../md_docs_2reproducibility.html#move-selection-performance-check',1,'']]],
  ['checked_20flips_20and_20cdt_20admissibility_23',['Checked flips and CDT admissibility',['../md_docs_2cgal-integration.html#checked-flips-and-cdt-admissibility',1,'']]],
  ['checklist_24',['Upgrade checklist',['../md_docs_2cgal-integration.html#upgrade-checklist',1,'']]],
  ['checkpoint_25',['Resume a checkpoint',['../index.html#resume-a-checkpoint',1,'']]],
  ['checkpoint_20continuation_26',['Exact checkpoint continuation',['../md_docs_2reproducibility.html#exact-checkpoint-continuation',1,'']]],
  ['citations_27',['References and Citations',['../md__r_e_f_e_r_e_n_c_e_s.html',1,'']]],
  ['cite_20this_20software_28',['How to Cite This Software',['../md__r_e_f_e_r_e_n_c_e_s.html#how-to-cite-this-software',1,'']]],
  ['citing_20cdt_29',['Citing CDT++',['../index.html#citing-cdt',1,'']]],
  ['classification_30',['Header classification',['../md_docs_2api-boundary.html#header-classification',1,'']]],
  ['clean_20up_31',['Step 4: Clean up',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#step-4-clean-up',1,'']]],
  ['command_20line_20usage_32',['Command-line usage',['../index.html#command-line-usage',1,'']]],
  ['commit_20the_20release_20metadata_33',['Validate and commit the release metadata',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#validate-and-commit-the-release-metadata',1,'']]],
  ['common_20contract_34',['Conventions and common contract',['../md_docs_2ergodic-moves.html#conventions-and-common-contract',1,'']]],
  ['comparison_20harness_35',['comparison harness',['../dir_6e133a56364528c326e124d8bed524d8.html#local-comparison-harness',1,'Local comparison harness'],['../md_docs_2comparison-harness.html',1,'Offline C++/Rust comparison harness']]],
  ['compatibility_20policy_36',['Compatibility policy',['../md_docs_2api-boundary.html#compatibility-policy',1,'']]],
  ['compiler_20contract_37',['Supported dependency and compiler contract',['../md_docs_2cgal-integration.html#supported-dependency-and-compiler-contract',1,'']]],
  ['complete_20the_20archival_20handoff_38',['Step 5: Stabilize, then complete the archival handoff',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#step-5-stabilize-then-complete-the-archival-handoff',1,'']]],
  ['complexity_39',['complexity',['../md__r_e_f_e_r_e_n_c_e_s.html#random-voronoi-and-delaunay-expected-complexity',1,'Random Voronoi and Delaunay expected complexity'],['../md__r_e_f_e_r_e_n_c_e_s.html#three-dimensional-delaunay-complexity',1,'Three-dimensional Delaunay complexity']]],
  ['computational_20geometry_20and_20random_20number_20generation_40',['Computational Geometry and Random-Number Generation',['../md__r_e_f_e_r_e_n_c_e_s.html#computational-geometry-and-random-number-generation',1,'']]],
  ['configurations_41',['Sequential and TBB-backed configurations',['../md_docs_2cgal-integration.html#sequential-and-tbb-backed-configurations',1,'']]],
  ['constraints_42',['Options and constraints',['../index.html#options-and-constraints',1,'']]],
  ['construction_43',['Delaunay empty-sphere construction',['../md__r_e_f_e_r_e_n_c_e_s.html#delaunay-empty-sphere-construction',1,'']]],
  ['consumption_44',['Rust consumption',['../dir_6e133a56364528c326e124d8bed524d8.html#rust-consumption',1,'']]],
  ['contents_45',['Contents',['../index.html#contents',1,'']]],
  ['continuation_46',['Exact checkpoint continuation',['../md_docs_2reproducibility.html#exact-checkpoint-continuation',1,'']]],
  ['contract_47',['contract',['../md_docs_2cgal-integration.html',1,'CGAL 6.2 integration contract'],['../md_docs_2ergodic-moves.html#conventions-and-common-contract',1,'Conventions and common contract'],['../md_docs_2metropolis-hastings.html',1,'Metropolis-Hastings transition contract'],['../md_docs_2multithreading.html',1,'Multithreaded CGAL contract'],['../md_docs_2reproducibility.html#persistence-contract',1,'Persistence contract'],['../md_docs_2comparison-harness.html#producer-contract',1,'Producer contract'],['../md_docs_2cgal-integration.html#supported-dependency-and-compiler-contract',1,'Supported dependency and compiler contract'],['../md_docs_2viewer.html',1,'Viewer and visual-artifact contract']]],
  ['contracts_48',['Required contracts',['../md_docs_2arithmetic-backend-evaluation.html#required-contracts',1,'']]],
  ['contributing_49',['Contributing',['../index.html#contributing',1,'']]],
  ['conventions_50',['Conventions',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#conventions',1,'']]],
  ['conventions_51',['Action conventions',['../md_docs_2metropolis-hastings.html#action-conventions',1,'']]],
  ['conventions_20and_20common_20contract_52',['Conventions and common contract',['../md_docs_2ergodic-moves.html#conventions-and-common-contract',1,'']]],
  ['correctness_53',['Determinism and correctness',['../md_docs_2multithreading.html#determinism-and-correctness',1,'']]],
  ['correctness_20results_54',['Correctness results',['../md_docs_2arithmetic-backend-evaluation.html#correctness-results',1,'']]],
  ['counters_55',['Counters',['../md_docs_2metropolis-hastings.html#counters',1,'']]],
  ['critical_20fixes_56',['Release-critical fixes',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#release-critical-fixes',1,'']]]
];
