var searchData=
[
  ['action_0',['Regge Calculus and Discrete Action',['../md__r_e_f_e_r_e_n_c_e_s.html#regge-calculus-and-discrete-action',1,'']]],
  ['action_20and_20metropolis_20hastings_20arithmetic_1',['Action and Metropolis-Hastings arithmetic',['../md_docs_2arithmetic-backend-evaluation.html#action-and-metropolis-hastings-arithmetic',1,'']]],
  ['action_20conventions_2',['Action conventions',['../md_docs_2metropolis-hastings.html#action-conventions',1,'']]],
  ['admissibility_3',['Checked flips and CDT admissibility',['../md_docs_2cgal-integration.html#checked-flips-and-cdt-admissibility',1,'']]],
  ['algorithm_4',['Metropolis-Hastings algorithm',['../md__r_e_f_e_r_e_n_c_e_s.html#metropolis-hastings-algorithm',1,'']]],
  ['alternatives_5',['Alternatives',['../md_docs_2arithmetic-backend-evaluation.html#alternatives',1,'']]],
  ['analysis_6',['Static Analysis',['../index.html#static-analysis',1,'']]],
  ['and_20cdt_20admissibility_7',['Checked flips and CDT admissibility',['../md_docs_2cgal-integration.html#checked-flips-and-cdt-admissibility',1,'']]],
  ['and_20citations_8',['References and Citations',['../md__r_e_f_e_r_e_n_c_e_s.html',1,'']]],
  ['and_20common_20contract_9',['Conventions and common contract',['../md_docs_2ergodic-moves.html#conventions-and-common-contract',1,'']]],
  ['and_20compiler_20contract_10',['Supported dependency and compiler contract',['../md_docs_2cgal-integration.html#supported-dependency-and-compiler-contract',1,'']]],
  ['and_20correctness_11',['Determinism and correctness',['../md_docs_2multithreading.html#determinism-and-correctness',1,'']]],
  ['and_20delaunay_20expected_20complexity_12',['Random Voronoi and Delaunay expected complexity',['../md__r_e_f_e_r_e_n_c_e_s.html#random-voronoi-and-delaunay-expected-complexity',1,'']]],
  ['and_20discrete_20action_13',['Regge Calculus and Discrete Action',['../md__r_e_f_e_r_e_n_c_e_s.html#regge-calculus-and-discrete-action',1,'']]],
  ['and_20duplicate_20points_14',['Metadata, insertion, and duplicate points',['../md_docs_2cgal-integration.html#metadata-insertion-and-duplicate-points',1,'']]],
  ['and_20exact_20arithmetic_20policy_15',['Kernel and exact-arithmetic policy',['../md_docs_2cgal-integration.html#kernel-and-exact-arithmetic-policy',1,'']]],
  ['and_20geometry_20deltas_16',['State and geometry deltas',['../md_docs_2metropolis-hastings.html#state-and-geometry-deltas',1,'']]],
  ['and_20lifetime_20rules_17',['Mutation and lifetime rules',['../md_docs_2cgal-integration.html#mutation-and-lifetime-rules',1,'']]],
  ['and_20local_20moves_18',['Simplicial Topology and Local Moves',['../md__r_e_f_e_r_e_n_c_e_s.html#simplicial-topology-and-local-moves',1,'']]],
  ['and_20metropolis_20hastings_20arithmetic_19',['Action and Metropolis-Hastings arithmetic',['../md_docs_2arithmetic-backend-evaluation.html#action-and-metropolis-hastings-arithmetic',1,'']]],
  ['and_20ownership_20behavior_20',['Failure and ownership behavior',['../md_docs_2cpp-api-quickstart.html#failure-and-ownership-behavior',1,'']]],
  ['and_20provenance_21',['Evaluation protocol and provenance',['../md_docs_2arithmetic-backend-evaluation.html#evaluation-protocol-and-provenance',1,'']]],
  ['and_20random_20number_20generation_22',['Computational Geometry and Random-Number Generation',['../md__r_e_f_e_r_e_n_c_e_s.html#computational-geometry-and-random-number-generation',1,'']]],
  ['and_20rollback_20gates_23',['Migration and rollback gates',['../md_docs_2arithmetic-backend-evaluation.html#migration-and-rollback-gates',1,'']]],
  ['and_20run_24',['Build and run',['../md_docs_2cpp-api-quickstart.html#build-and-run',1,'']]],
  ['and_20smoke_20policy_25',['Render manifest and smoke policy',['../md_docs_2viewer.html#render-manifest-and-smoke-policy',1,'']]],
  ['and_20tbb_20backed_20configurations_26',['Sequential and TBB-backed configurations',['../md_docs_2cgal-integration.html#sequential-and-tbb-backed-configurations',1,'']]],
  ['and_20test_27',['Build and test',['../md_docs_2multithreading.html#build-and-test',1,'']]],
  ['and_20verify_20the_20release_28',['Step 3: Publish and verify the release',['../md_docs_2_r_e_l_e_a_s_i_n_g.html#step-3-publish-and-verify-the-release',1,'']]],
  ['and_20visual_20artifact_20contract_29',['Viewer and visual-artifact contract',['../md_docs_2viewer.html',1,'']]],
  ['api_20boundary_30',['C++ API boundary',['../md_docs_2api-boundary.html',1,'']]],
  ['api_20quickstart_31',['C++ API quickstart',['../md_docs_2cpp-api-quickstart.html',1,'']]],
  ['arithmetic_32',['Action and Metropolis-Hastings arithmetic',['../md_docs_2arithmetic-backend-evaluation.html#action-and-metropolis-hastings-arithmetic',1,'']]],
  ['arithmetic_20evaluation_33',['GMP/MPFR-free arithmetic evaluation',['../md_docs_2arithmetic-backend-evaluation.html',1,'']]],
  ['arithmetic_20policy_34',['Kernel and exact-arithmetic policy',['../md_docs_2cgal-integration.html#kernel-and-exact-arithmetic-policy',1,'']]],
  ['artifact_20contract_35',['Viewer and visual-artifact contract',['../md_docs_2viewer.html',1,'']]],
  ['artifact_20layout_36',['Artifact layout',['../md_docs_2comparison-harness.html#artifact-layout',1,'']]],
  ['audit_37',['2+1D CDT ergodic move audit',['../md_docs_2ergodic-moves.html',1,'']]]
];
