"""Tests for the generated Doxygen site validator."""

import tempfile
import unittest
from pathlib import Path

from scripts import validate_generated_site


class GeneratedSiteValidationTests(unittest.TestCase):
    """Exercise archival pages, references, identifiers, and regression checks."""

    def _valid_site(self) -> Path:
        """Create the smallest complete generated-site contract."""
        root = Path(self.enterContext(tempfile.TemporaryDirectory()))
        target_fragments = validate_generated_site.REQUIRED_TARGETS
        for relative, fragments in target_fragments.items():
            anchors = "".join(f'<h2 id="{fragment}">{fragment}</h2>' for fragment in fragments)
            body = anchors
            if relative == "index.html":
                body += """
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<script src="clipboard.js"></script>
<script>codefold.init();</script>
<img src="S3-7-27528-I1-R1.png" alt="fixture"/>
"""
            target = root / relative
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(f"<!doctype html><html><body>{body}</body></html>", encoding="utf-8")

        for relative in validate_generated_site.REQUIRED_ASSETS:
            target = root / relative
            target.parent.mkdir(parents=True, exist_ok=True)
            if relative == "doxygen.css":
                target.write_text("@media (prefers-color-scheme: dark) {}\n", encoding="utf-8")
            elif target.suffix in {".css", ".js"}:
                target.write_text("/* generated test asset */\n", encoding="utf-8")
            else:
                target.write_bytes(b"generated test asset")
        (root / "graph.svg").write_text("<!-- Generated by graphviz -->\n<svg></svg>\n", encoding="utf-8")
        return root

    def test_complete_site_validates(self) -> None:
        """The bounded archival surface passes without network access."""
        site = self._valid_site()

        page_count = validate_generated_site.validate(site)

        self.assertEqual(page_count, len(validate_generated_site.REQUIRED_TARGETS))

    def test_missing_local_page_and_fragment_are_rejected(self) -> None:
        """Every generated local page and fragment reference must resolve."""
        for reference, diagnostic in (
            ("missing.html", "missing local target"),
            ("index.html#missing", "missing fragment"),
        ):
            with self.subTest(reference=reference):
                site = self._valid_site()
                (site / "index.html").write_text(
                    (site / "index.html").read_text(encoding="utf-8") + f'<a href="{reference}">broken</a>',
                    encoding="utf-8",
                )

                with self.assertRaisesRegex(validate_generated_site.GeneratedSiteError, diagnostic):
                    validate_generated_site.validate(site)

    def test_duplicate_identifier_is_rejected(self) -> None:
        """A page cannot publish two targets under the same HTML id."""
        site = self._valid_site()
        (site / "index.html").write_text(
            (site / "index.html").read_text(encoding="utf-8") + '<div id="introduction"></div>',
            encoding="utf-8",
        )

        with self.assertRaisesRegex(validate_generated_site.GeneratedSiteError, "duplicate id 'introduction'"):
            validate_generated_site.validate(site)

    def test_doxygen_117_duplicate_link_label_is_rejected(self) -> None:
        """Doxygen 1.17's immediately repeated linked prose must remain caught."""
        site = self._valid_site()
        (site / "index.html").write_text(
            (site / "index.html").read_text(encoding="utf-8") + '<p><a class="el" href="#introduction">Introduction</a>Introduction</p>',
            encoding="utf-8",
        )

        with self.assertRaisesRegex(validate_generated_site.GeneratedSiteError, "duplicated rendered link label 'Introduction'"):
            validate_generated_site.validate(site)

    def test_literal_markdown_in_rendered_prose_is_rejected(self) -> None:
        """A Markdown link emitted as prose is not accepted as rendered output."""
        site = self._valid_site()
        (site / "index.html").write_text(
            (site / "index.html").read_text(encoding="utf-8") + "<p>The [Justfile](Justfile) defines commands.</p>",
            encoding="utf-8",
        )

        with self.assertRaisesRegex(validate_generated_site.GeneratedSiteError, "literal Markdown link"):
            validate_generated_site.validate(site)

    def test_missing_stylesheet_asset_is_rejected(self) -> None:
        """Local CSS resources are part of the self-contained site contract."""
        site = self._valid_site()
        (site / "doxygen.css").write_text(
            '@media (prefers-color-scheme: dark) {}\n.hero { background: url("missing.png"); }\n',
            encoding="utf-8",
        )

        with self.assertRaisesRegex(validate_generated_site.GeneratedSiteError, "missing stylesheet asset 'missing.png'"):
            validate_generated_site.validate(site)

    def test_unused_mermaid_client_is_rejected(self) -> None:
        """The archive must not acquire Doxygen 1.17's unused CDN dependency."""
        site = self._valid_site()
        (site / "menu.js").write_text(
            "import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs';\n",
            encoding="utf-8",
        )

        with self.assertRaisesRegex(validate_generated_site.GeneratedSiteError, "unused Mermaid client dependency"):
            validate_generated_site.validate(site)

    def test_scoped_implementation_completeness_warnings_are_ignored(self) -> None:
        """Only completeness noise from unsupported symbols and source artifacts is ignored."""
        root = Path(self.enterContext(tempfile.TemporaryDirectory()))
        warning_log = root / "warnings.log"
        warning_log.write_text(
            "include/A.hpp:1: warning: Member helper (function) of namespace cdt::detail is not documented.\n"
            "<helper>:1: warning: parameters of member cdt::module::detail::helper are not documented\n"
            "include/Legacy.hpp:1: warning: Member old (function) of namespace cdt::experimental::old is not documented.\n"
            "src/cdt.cpp:1: warning: Member main(int argc) (function) of file cdt.cpp is not documented.\n"
            "src/cdt.cpp:1: warning: parameters of member main are not documented\n"
            "<catch>:1: warning: parameters of member catch are not documented\n"
            "<main>:1: warning: parameters of member main are not documented\n",
            encoding="utf-8",
        )

        ignored = validate_generated_site.validate_warning_log(warning_log)

        self.assertEqual(ignored, 7)

    def test_public_completeness_warning_is_rejected(self) -> None:
        """An undocumented supported symbol must fail documentation validation."""
        root = Path(self.enterContext(tempfile.TemporaryDirectory()))
        warning_log = root / "warnings.log"
        warning_log.write_text(
            "include/Public.hpp:1: warning: Member run (function) of namespace cdt is not documented.\n",
            encoding="utf-8",
        )

        with self.assertRaisesRegex(validate_generated_site.GeneratedSiteError, "Public.hpp.*run"):
            validate_generated_site.validate_warning_log(warning_log)

    def test_public_parameter_warning_is_rejected(self) -> None:
        """Missing caller-contract details on a supported function remain fatal."""
        root = Path(self.enterContext(tempfile.TemporaryDirectory()))
        warning_log = root / "warnings.log"
        warning_log.write_text(
            "include/Public.hpp:1: warning: parameters of member cdt::run are not documented\n",
            encoding="utf-8",
        )

        with self.assertRaisesRegex(validate_generated_site.GeneratedSiteError, "parameters of member cdt::run"):
            validate_generated_site.validate_warning_log(warning_log)

    def test_public_main_parameter_warning_is_rejected(self) -> None:
        """The source-entry exemption must not hide a public header declaration."""
        root = Path(self.enterContext(tempfile.TemporaryDirectory()))
        warning_log = root / "warnings.log"
        warning_log.write_text(
            "include/Public.hpp:1: warning: parameters of member main are not documented\n",
            encoding="utf-8",
        )

        with self.assertRaisesRegex(validate_generated_site.GeneratedSiteError, "Public.hpp.*member main"):
            validate_generated_site.validate_warning_log(warning_log)

    def test_malformed_internal_documentation_warning_is_rejected(self) -> None:
        """Internal scope never excuses broken Doxygen markup or references."""
        root = Path(self.enterContext(tempfile.TemporaryDirectory()))
        warning_log = root / "warnings.log"
        warning_log.write_text(
            "include/Internal.hpp:1: warning: unable to resolve reference to cdt::detail::missing\n",
            encoding="utf-8",
        )

        with self.assertRaisesRegex(validate_generated_site.GeneratedSiteError, "unable to resolve reference"):
            validate_generated_site.validate_warning_log(warning_log)


if __name__ == "__main__":
    unittest.main()
