@echo off

SETLOCAL ENABLEEXTENSIONS
SET "SCRIPT_DIR=%~dp0"
FOR %%I IN ("%SCRIPT_DIR%..") DO SET "REPO_ROOT=%%~fI"

IF DEFINED CDT_VCPKG_CACHE_DIR (
  SET "PINNED_VCPKG_ROOT=%CDT_VCPKG_CACHE_DIR%"
) ELSE (
  SET "PINNED_VCPKG_ROOT=%REPO_ROOT%\.cache\vcpkg"
)

IF DEFINED VCPKG_ROOT (
  SET "CDT_VCPKG_CACHE_DIR=%VCPKG_ROOT%"
  CALL "%SCRIPT_DIR%bootstrap-vcpkg.bat" --check >NUL 2>NUL
  IF NOT ERRORLEVEL 1 GOTO VCPKG_READY
  echo Ignoring VCPKG_ROOT=%VCPKG_ROOT%; using the repository-pinned checkout instead. 1>&2
)

SET "CDT_VCPKG_CACHE_DIR=%PINNED_VCPKG_ROOT%"
SET "VCPKG_ROOT=%PINNED_VCPKG_ROOT%"
CALL "%SCRIPT_DIR%bootstrap-vcpkg.bat" || EXIT /B 1

:VCPKG_READY
SET "VCPKG_ROOT=%CDT_VCPKG_CACHE_DIR%"
CD /D "%REPO_ROOT%" || EXIT /B 1
CALL :PREPARE_CMAKE_CACHE || EXIT /B 1
cmake --preset reference -S . || EXIT /B 1
cmake --build --preset reference --target cdt || EXIT /B 1
EXIT /B 0

:PREPARE_CMAKE_CACHE
SET "CMAKE_CACHE=%REPO_ROOT%\out\build\reference\CMakeCache.txt"
SET "EXPECTED_TOOLCHAIN=%VCPKG_ROOT:\=/%/scripts/buildsystems/vcpkg.cmake"
SET "EXPECTED_INSTALLED=%REPO_ROOT:\=/%/out/build/reference/vcpkg_installed"
SET "CACHED_TOOLCHAIN="
SET "CACHED_INSTALLED="
IF EXIST "%CMAKE_CACHE%" FOR /F "tokens=1,* delims==" %%A IN ('FINDSTR /B /C:"CMAKE_TOOLCHAIN_FILE:" "%CMAKE_CACHE%"') DO SET "CACHED_TOOLCHAIN=%%B"
IF EXIST "%CMAKE_CACHE%" FOR /F "tokens=1,* delims==" %%A IN ('FINDSTR /B /C:"VCPKG_INSTALLED_DIR:" "%CMAKE_CACHE%"') DO SET "CACHED_INSTALLED=%%B"
SET "CACHED_TOOLCHAIN=%CACHED_TOOLCHAIN:\=/%"
SET "CACHED_INSTALLED=%CACHED_INSTALLED:\=/%"
IF EXIST "%CMAKE_CACHE%" IF /I NOT "%CACHED_TOOLCHAIN%"=="%EXPECTED_TOOLCHAIN%" GOTO REFRESH_CMAKE_CACHE
IF EXIST "%CMAKE_CACHE%" IF /I NOT "%CACHED_INSTALLED%"=="%EXPECTED_INSTALLED%" GOTO REFRESH_CMAKE_CACHE
EXIT /B 0

:REFRESH_CMAKE_CACHE
ECHO vcpkg configuration changed; refreshing CMake configuration state. 1>&2
DEL /F /Q "%CMAKE_CACHE%" || EXIT /B 1
IF EXIST "%REPO_ROOT%\out\build\reference\CMakeFiles\." RMDIR /S /Q "%REPO_ROOT%\out\build\reference\CMakeFiles" || EXIT /B 1
EXIT /B 0
