"""Regenerate every CDT++ reference artifact from one clean source commit."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from scripts.validate_reference_fixtures import (
    load_json,
    parse_json_object,
    parse_key_value_payload,
    validate_document,
)

ROOT = Path(__file__).resolve().parents[1]
MANIFESTS = ROOT / "reference" / "manifests" / "v1"

REFERENCE_COMMANDS = [
    {
        "id": "canonical-fixture",
        "artifacts": ["reference/raw/v1/cpp-reference.json"],
    },
    {
        "id": "bounded-end-to-end",
        "artifacts": ["reference/raw/v1/end-to-end.txt"],
    },
    {
        "id": "persistence-roundtrip",
        "artifacts": [
            "reference/raw/v1/persistence-v1.off",
            "reference/raw/v1/persistence-v1.off.meta",
        ],
    },
]

CANONICAL_PRODUCER_PATHS = {
    "--fixture-binary": "out/build/reference/tests/CDT_reference_fixture",
    "--cdt-binary": "out/build/reference/src/cdt",
    "--initialize-binary": "out/build/reference/src/initialize",
    "--benchmark-binary": "out/build/parallel/tests/CDT_cgal_benchmark",
}

CMAKE_CACHE_PATHS = (
    ROOT / "out" / "build" / "reference" / "CMakeCache.txt",
    ROOT / "out" / "build" / "parallel" / "CMakeCache.txt",
)


@dataclass(frozen=True)
class RegenerationMetadata:
    """Run-scoped provenance that must not come from a manifest template."""

    revision: str
    recorded_at_utc: str
    cmake_version: str


def run_command(
    command: list[str],
    *,
    cwd: Path = ROOT,
    timeout: int = 900,
) -> str:
    """Run one producer without a shell and return its exact standard output."""
    completed = subprocess.run(  # noqa: S603
        command,
        cwd=cwd,
        check=False,
        capture_output=True,
        text=True,
        timeout=timeout,
    )
    if completed.returncode != 0:
        rendered = " ".join(command)
        message = f"reference producer failed with exit {completed.returncode}: {rendered}\n{completed.stderr.strip()}"
        raise RuntimeError(message)
    return completed.stdout


def clean_source_revision() -> str:
    """Return HEAD only when every tracked and untracked source path is clean."""
    status = run_command(
        ["git", "status", "--porcelain", "--untracked-files=all"],
        timeout=30,
    )
    if status:
        message = "reference regeneration requires a clean worktree; commit the implementation and regeneration workflow first"
        raise RuntimeError(message)
    revision = run_command(["git", "rev-parse", "HEAD"], timeout=30).strip()
    if len(revision) != 40 or any(character not in "0123456789abcdef" for character in revision):
        message = f"git returned an invalid source revision: {revision!r}"
        raise RuntimeError(message)
    return revision


def executable(path: Path) -> Path:
    """Resolve and validate one repository-owned producer executable."""
    resolved = path if path.is_absolute() else ROOT / path
    if not resolved.is_file() or not os.access(resolved, os.X_OK):
        message = f"reference producer is missing or not executable: {resolved}"
        raise ValueError(message)
    return resolved


def display_path(path: Path) -> str:
    """Render a producer path relative to the repository when possible."""
    resolved = path if path.is_absolute() else ROOT / path
    try:
        return str(resolved.resolve().relative_to(ROOT.resolve()))
    except ValueError:
        return str(resolved)


def sha256(payload: bytes) -> str:
    """Return a lowercase SHA-256 digest for generated bytes."""
    return hashlib.sha256(payload).hexdigest()


def artifact_digest(path: str, generated: dict[str, bytes]) -> str:
    """Hash generated bytes or an authored package input."""
    if path in generated:
        return sha256(generated[path])
    return sha256((ROOT / path).read_bytes())


def refresh_artifacts(
    manifest: dict[str, Any],
    generated: dict[str, bytes],
) -> None:
    """Refresh every artifact checksum without changing its media type."""
    for artifact in manifest["artifacts"]:
        artifact["sha256"] = artifact_digest(str(artifact["path"]), generated)


def record_commands(
    records: list[dict[str, Any]],
    command_lines: list[list[str]],
) -> list[dict[str, Any]]:
    """Attach exact argv arrays to the artifacts each command produced."""
    if len(records) != len(command_lines):
        message = "producer command metadata does not match the generated artifacts"
        raise ValueError(message)
    return [
        {
            **record,
            "command_line": command_line,
        }
        for record, command_line in zip(records, command_lines, strict=True)
    ]


def validate_producer_paths(
    reference_commands: list[list[str]],
    scaling_commands: list[list[str]],
) -> None:
    """Require every recorded argv[0] to use the canonical build layout."""
    recorded = (
        ("--fixture-binary", reference_commands[0][0]),
        ("--cdt-binary", reference_commands[1][0]),
        ("--initialize-binary", reference_commands[2][0]),
        *(("--benchmark-binary", command[0]) for command in scaling_commands),
    )
    for option, path in recorded:
        expected = CANONICAL_PRODUCER_PATHS[option]
        if path != expected:
            message = f"{option} must use the canonical producer path {expected!r}; got {path!r}"
            raise ValueError(message)


def canonical_timestamp(value: str | None) -> str:
    """Return a canonical UTC timestamp, rejecting ambiguous overrides."""
    if value is None:
        instant = datetime.now(UTC).replace(microsecond=0)
    else:
        try:
            instant = datetime.fromisoformat(value)
        except ValueError as error:
            message = f"invalid --recorded-at-utc value: {value!r}"
            raise ValueError(message) from error
        if instant.tzinfo is None or instant.utcoffset() is None:
            message = "--recorded-at-utc must include a UTC offset"
            raise ValueError(message)
        instant = instant.astimezone(UTC)
    return instant.isoformat().replace("+00:00", "Z")


def cmake_command_from_cache(cache_path: Path) -> Path:
    """Return the exact CMake executable recorded by one configured build."""
    prefix = "CMAKE_COMMAND:INTERNAL="
    commands = [line.removeprefix(prefix) for line in cache_path.read_text(encoding="utf-8").splitlines() if line.startswith(prefix)]
    if len(commands) != 1:
        message = f"{cache_path}: expected exactly one configured CMake command"
        raise RuntimeError(message)
    command = Path(commands[0])
    if not command.is_file():
        message = f"{cache_path}: configured CMake executable does not exist: {command}"
        raise RuntimeError(message)
    return command


def configured_cmake_version(
    cache_paths: tuple[Path, ...] = CMAKE_CACHE_PATHS,
) -> str:
    """Return the common CMake version that configured every producer build."""
    prefix = "cmake version "
    versions: dict[Path, str] = {}
    for cache_path in cache_paths:
        command = cmake_command_from_cache(cache_path)
        lines = run_command([str(command), "--version"], timeout=30).splitlines()
        if not lines or not lines[0].startswith(prefix):
            observed = lines[0] if lines else ""
            message = f"{cache_path}: cannot parse CMake version from {observed!r}"
            raise RuntimeError(message)
        versions[cache_path] = lines[0].removeprefix(prefix)
    if len(set(versions.values())) != 1:
        rendered = ", ".join(f"{path}: {version}" for path, version in versions.items())
        message = f"producer builds were configured by different CMake versions: {rendered}"
        raise RuntimeError(message)
    return next(iter(versions.values()))


def producer_commands(
    fixture: Path,
    cdt: Path,
    initialize: Path,
    benchmark: Path,
) -> tuple[list[str], list[str], list[str], list[list[str]]]:
    """Return the four producer command families with resolved executables."""
    return (
        [str(fixture)],
        [
            str(cdt),
            "-s",
            "-n2",
            "-t2",
            "-a1",
            "-k0",
            "-l1",
            "-p1",
            "-c1",
            "--seed",
            "92",
            "--threads",
            "1",
            "--no-output",
        ],
        [
            str(initialize),
            "-s",
            "-n2",
            "-t2",
            "-o",
            "--seed",
            "92",
            "--threads",
            "1",
        ],
        [[str(benchmark), "640", "5", "50", str(threads), "1"] for threads in (1, 2, 4)],
    )


def produce_raw_artifacts(
    revision: str,
    fixture_command: list[str],
    bounded_command: list[str],
    persistence_command: list[str],
    benchmark_commands: list[list[str]],
) -> tuple[dict[str, bytes], dict[str, Any], list[dict[str, str]]]:
    """Run every producer and retain its direct, unnormalized output."""
    generated: dict[str, bytes] = {}
    fixture_output = run_command(fixture_command)
    fixture_json = parse_json_object(fixture_output, fixture_command[0])
    if fixture_json["implementation"]["revision"] != revision:
        message = "fixture binary does not embed the clean source revision; reconfigure and rebuild it"
        raise RuntimeError(message)
    generated["reference/raw/v1/cpp-reference.json"] = fixture_output.encode()
    generated["reference/raw/v1/end-to-end.txt"] = run_command(bounded_command).encode()

    with tempfile.TemporaryDirectory(prefix="cdt-reference-persistence-") as temp:
        temp_path = Path(temp)
        run_command(persistence_command, cwd=temp_path)
        payloads = list(temp_path.glob("*.off"))
        if len(payloads) != 1:
            message = f"persistence producer did not create exactly one OFF payload: {payloads}"
            raise RuntimeError(message)
        payload = payloads[0]
        metadata = payload.with_suffix(".off.meta")
        if not metadata.is_file():
            message = f"persistence producer did not create {metadata.name}"
            raise RuntimeError(message)
        generated["reference/raw/v1/persistence-v1.off"] = payload.read_bytes()
        generated["reference/raw/v1/persistence-v1.off.meta"] = metadata.read_bytes()

    scaling_records: list[dict[str, str]] = []
    for threads, command in zip((1, 2, 4), benchmark_commands, strict=True):
        output = run_command(command)
        record = parse_key_value_payload(output, command[0])
        if record.get("implementation.revision") != revision:
            message = f"{threads}-thread benchmark does not embed the clean source revision; reconfigure and rebuild it"
            raise RuntimeError(message)
        scaling_records.append(record)
        generated[f"reference/raw/v1/scaling-threads-{threads}.txt"] = output.encode()
    return generated, fixture_json, scaling_records


def validate_platform_identity(
    fixture_json: dict[str, Any],
    scaling_records: list[dict[str, str]],
) -> None:
    """Protect the current macOS-arm64 manifest names from cross-host misuse."""
    implementation = fixture_json["implementation"]
    first_scaling = scaling_records[0]
    identities = {
        (
            str(implementation["operating_system"]),
            str(implementation["hardware"]),
        ),
        (
            first_scaling["build.system"],
            first_scaling["build.processor"],
        ),
    }
    if identities != {("Darwin", "arm64")}:
        message = "the v1 manifest templates are macOS-arm64-specific; add explicit templates before regenerating on another platform"
        raise RuntimeError(message)


def make_reference_manifest(
    generated: dict[str, bytes],
    fixture_json: dict[str, Any],
    metadata: RegenerationMetadata,
    command_lines: list[list[str]],
) -> dict[str, Any]:
    """Build the canonical/persistence manifest from producer metadata."""
    manifest = json.loads((MANIFESTS / "macos-arm64.json").read_text(encoding="utf-8"))
    implementation = fixture_json["implementation"]
    recorded_date = metadata.recorded_at_utc[:10].replace("-", "")
    manifest["run_id"] = f"cdt-reference-v1-{implementation['operating_system'].lower()}-{implementation['hardware'].lower()}-{recorded_date}"
    manifest["recorded_at_utc"] = metadata.recorded_at_utc
    manifest["implementation"].update(
        {
            "version": implementation["version"],
            "source_revision": metadata.revision,
        }
    )
    manifest["implementation"].pop("note", None)
    manifest["toolchain"] = {
        "compiler": implementation["compiler"],
        "cxx_standard": implementation["cxx_standard"],
        "standard_library": implementation["standard_library"],
        "cmake": metadata.cmake_version,
        "cgal": implementation["cgal_version"],
    }
    manifest.pop("verification", None)
    manifest["build"]["profile"] = implementation["build_profile"]
    manifest["host"].update(
        {
            "operating_system": implementation["operating_system"],
            "architecture": implementation["hardware"],
            "logical_threads": implementation["logical_threads"],
        }
    )
    manifest["commands"] = record_commands(REFERENCE_COMMANDS, command_lines)
    refresh_artifacts(manifest, generated)
    return manifest


def make_scaling_manifest(
    generated: dict[str, bytes],
    records: list[dict[str, str]],
    metadata: RegenerationMetadata,
    command_lines: list[list[str]],
) -> dict[str, Any]:
    """Build the matched scaling manifest from benchmark metadata."""
    first = records[0]
    recorded_date = metadata.recorded_at_utc[:10].replace("-", "")
    manifest = json.loads((MANIFESTS / "scaling-macos-arm64.json").read_text(encoding="utf-8"))
    manifest["run_id"] = f"cdt-scaling-v1-{first['build.system'].lower()}-{first['build.processor'].lower()}-{recorded_date}"
    manifest["recorded_at_utc"] = metadata.recorded_at_utc
    manifest["implementation"].update(
        {
            "version": first["implementation.version"],
            "source_revision": metadata.revision,
        }
    )
    manifest["implementation"].pop("note", None)
    manifest["toolchain"] = {
        "compiler": f"{first['build.compiler_id']} {first['build.compiler_version']}",
        "cxx_standard": int(first["build.cxx_standard"]),
        "standard_library": first["build.standard_library"],
        "cmake": metadata.cmake_version,
        "cgal": first["dependency.cgal_version"],
        "tbb": first["dependency.tbb_version"],
    }
    manifest.pop("verification", None)
    manifest["build"]["profile"] = first["build.configuration"]
    manifest["host"].update(
        {
            "operating_system": first["build.system"],
            "architecture": first["build.processor"],
            "logical_threads": int(first["hardware.logical_threads"]),
        }
    )
    command_records = [
        {
            "id": f"scaling-threads-{threads}",
            "artifacts": [f"reference/raw/v1/scaling-threads-{threads}.txt"],
        }
        for threads in (1, 2, 4)
    ]
    manifest["commands"] = record_commands(command_records, command_lines)
    refresh_artifacts(manifest, generated)
    return manifest


def record_regeneration_verification(
    manifest: dict[str, Any],
    metadata: RegenerationMetadata,
) -> None:
    """Record only evidence produced by the current regeneration run."""
    manifest["verification"] = {
        "producer_regeneration": {
            "status": "passed",
            "source_revision": metadata.revision,
            "recorded_at_utc": metadata.recorded_at_utc,
        }
    }


def validate_generated_json(
    fixture_json: dict[str, Any],
    reference_manifest: dict[str, Any],
    scaling_manifest: dict[str, Any],
) -> None:
    """Apply the package schemas before any generated bytes are published."""
    result_schema = load_json(ROOT / "reference" / "schema" / "result-v1.schema.json")
    manifest_schema = load_json(ROOT / "reference" / "schema" / "run-manifest-v1.schema.json")
    validate_document(fixture_json, result_schema, Path("generated fixture"))
    validate_document(
        reference_manifest,
        manifest_schema,
        Path("generated reference manifest"),
    )
    validate_document(
        scaling_manifest,
        manifest_schema,
        Path("generated scaling manifest"),
    )


def publish_artifacts(generated: dict[str, bytes]) -> None:
    """Write all bytes to sibling temporaries before replacing any artifact."""
    pending: list[tuple[Path, Path]] = []
    try:
        for relative_path, payload in generated.items():
            destination = ROOT / relative_path
            destination.parent.mkdir(parents=True, exist_ok=True)
            descriptor, temporary_name = tempfile.mkstemp(prefix=f".{destination.name}.", dir=destination.parent)
            temporary = Path(temporary_name)
            with os.fdopen(descriptor, "wb") as stream:
                stream.write(payload)
                stream.flush()
                os.fsync(stream.fileno())
            pending.append((temporary, destination))
        for temporary, destination in pending:
            temporary.replace(destination)
    finally:
        for temporary, _destination in pending:
            temporary.unlink(missing_ok=True)


def regenerate(
    fixture_binary: Path,
    cdt_binary: Path,
    initialize_binary: Path,
    benchmark_binary: Path,
    recorded_at_utc: str | None,
) -> None:
    """Generate all raw outputs, then publish them with refreshed manifests."""
    revision = clean_source_revision()
    paths = (
        executable(fixture_binary),
        executable(cdt_binary),
        executable(initialize_binary),
        executable(benchmark_binary),
    )
    fixture_command, bounded_command, persistence_command, benchmark_commands = producer_commands(*paths)
    generated, fixture_json, scaling_records = produce_raw_artifacts(
        revision,
        fixture_command,
        bounded_command,
        persistence_command,
        benchmark_commands,
    )
    validate_platform_identity(fixture_json, scaling_records)
    recorded = canonical_timestamp(recorded_at_utc)
    reference_commands = [
        [display_path(fixture_binary)],
        [display_path(cdt_binary), *bounded_command[1:]],
        [display_path(initialize_binary), *persistence_command[1:]],
    ]
    scaling_commands = [[display_path(benchmark_binary), *command[1:]] for command in benchmark_commands]
    validate_producer_paths(reference_commands, scaling_commands)
    metadata = RegenerationMetadata(revision, recorded, configured_cmake_version())
    reference_manifest = make_reference_manifest(generated, fixture_json, metadata, reference_commands)
    scaling_manifest = make_scaling_manifest(generated, scaling_records, metadata, scaling_commands)
    record_regeneration_verification(reference_manifest, metadata)
    record_regeneration_verification(scaling_manifest, metadata)
    validate_generated_json(fixture_json, reference_manifest, scaling_manifest)
    generated["reference/manifests/v1/macos-arm64.json"] = (json.dumps(reference_manifest, indent=2, ensure_ascii=False) + "\n").encode()
    generated["reference/manifests/v1/scaling-macos-arm64.json"] = (json.dumps(scaling_manifest, indent=2, ensure_ascii=False) + "\n").encode()
    publish_artifacts(generated)
    print(f"Regenerated reference/raw/v1 and reference/manifests/v1 from {revision}.")


def main() -> int:
    """Parse regeneration paths and publish the complete reference package."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--fixture-binary",
        type=Path,
        default=Path("out/build/reference/tests/CDT_reference_fixture"),
    )
    parser.add_argument(
        "--cdt-binary",
        type=Path,
        default=Path("out/build/reference/src/cdt"),
    )
    parser.add_argument(
        "--initialize-binary",
        type=Path,
        default=Path("out/build/reference/src/initialize"),
    )
    parser.add_argument(
        "--benchmark-binary",
        type=Path,
        default=Path("out/build/parallel/tests/CDT_cgal_benchmark"),
    )
    parser.add_argument(
        "--recorded-at-utc",
        help="override the ISO-8601 manifest timestamp for controlled regeneration",
    )
    parser.add_argument(
        "--check-clean",
        action="store_true",
        help="verify the clean source precondition without running producers",
    )
    arguments = parser.parse_args()
    if arguments.check_clean:
        revision = clean_source_revision()
        print(f"Reference regeneration source is clean at {revision}.")
        return 0
    regenerate(
        arguments.fixture_binary,
        arguments.cdt_binary,
        arguments.initialize_binary,
        arguments.benchmark_binary,
        arguments.recorded_at_utc,
    )
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, RuntimeError, TypeError, ValueError, subprocess.SubprocessError) as error:
        print(f"error: {error}", file=sys.stderr)
        raise SystemExit(1) from None
