---
name: Address Sanitizer

"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
          submodules: true

      - name: Setup
        run: |
          sudo apt update
          sudo apt-get install --yes \
            automake autoconf autoconf-archive build-essential ccache \
            libtool-bin ninja-build texinfo yasm

      - name: Setup Clang
        uses: pkgxdev/setup@4d4ae97af87ccb39ab8be4e073dea697fef2c6f7  # v5.0.0
        with:
          +: llvm.org@20

      - run: clang --version

      - name: Restore artifacts or setup vcpkg
        uses: lukka/run-vcpkg@b1a0dd252f06b9e25b3c022a9a03bd7a427fb6a2  # v11.6

      - name: Configure
        run: cmake --preset=asan

      - name: Build
        run: cmake --build build -j 2

      - name: Run tests
        working-directory: build
        continue-on-error: true
        run: ctest -VV

      - name: Run ASAN on initialize
        working-directory: build/src
        continue-on-error: true
        run: ./initialize --s -n32000 -t11 -o

      - name: Run ASAN on cdt-opt
        working-directory: build/src
        continue-on-error: true
        run: ./cdt-opt

      - name: Run ASAN on cdt
        working-directory: build/src
        continue-on-error: true
        run: ./cdt --s -n64 -t3 -a.6 -k1.1 -l.1 -p10
