---
name: CodeCov

"on":
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  codecov:
    name: CodeCov
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup
        run: |
          sudo apt update
          sudo apt-get install --yes \
            automake autoconf autoconf-archive build-essential ccache \
            libtool-bin ninja-build texinfo yasm

      - name: Setup GCC
        uses: pkgxdev/setup@4d4ae97af87ccb39ab8be4e073dea697fef2c6f7  # v5.0.0
        with:
          +: gnu.org/gcc@16

      - run: gcc --version

      - name: Restore artifacts or setup vcpkg
        uses: lukka/run-vcpkg@b1a0dd252f06b9e25b3c022a9a03bd7a427fb6a2  # v11.6

      - name: Configure
        run: >-
          cmake -G Ninja -D CMAKE_BUILD_TYPE=RelWithDebInfo
          -D ENABLE_TESTING:BOOL=TRUE -D ENABLE_COVERAGE:BOOL=TRUE
          -S . -B build

      - name: Build
        run: cmake --build build -j 2

      - name: Test
        working-directory: build
        continue-on-error: true
        run: ctest --rerun-failed --output-on-failure -j 2

      - name: Generate coverage info
        working-directory: build
        continue-on-error: true
        run: |
          mkdir gcov-reports
          pushd gcov-reports
          find ../tests/CMakeFiles/CDT_test.dir -name '*.o' -print0 |
            while IFS= read -r -d '' object_file; do
              echo "Processing ${object_file} file..."
              gcov -o "${object_file}" x
            done
          find . -maxdepth 1 -type f | wc -l
          popd

      - name: Submit to codecov.io
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f  # v7.0.0
        with:
          directory: build/gcov-reports
          fail_ci_if_error: false
          use_oidc: true
          verbose: true
