name: CodeCov

on: [push, pull_request, workflow_dispatch]

jobs:
  codecov:
    name: CodeCov
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup
        run: |
          brew install automake autoconf autoconf-archive libtool texinfo yasm ninja python ccache lcov

      - name: Restore artifacts, or setup vcpkg
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgGitCommitId: 7e7c62d863b1bf599c1d104b76cd8b74475844d4

      - name: Install vcpkg packages and configure CMake
        shell: bash
        run: |
          vcpkg install
          cmake -G Ninja -D CMAKE_BUILD_TYPE=RelWithDebInfo -D ENABLE_TESTING:BOOL=TRUE -D ENABLE_COVERAGE:BOOL=TRUE -S . -B build

      - name: Build
        run: cmake --build build

      - name: Generate coverage
        continue-on-error: true
        run: |
          cd $GITHUB_WORKSPACE/build
          ctest --schedule-random --rerun-failed --output-on-failure -j2
          lcov --capture --directory . --output-file coverage.info
          lcov --remove coverage.info '/usr/*' '*/usr/include/*' '*/vcpkg_installed/*' --output-file coverage.info
          lcov --list coverage.info

      - name: Upload coverage to CodeCov
        run: |
          cd $GITHUB_WORKSPACE/build
          bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"