name: CodeCov

on: [push, pull_request, workflow_dispatch]

jobs:
  codecov:
    name: CodeCov
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: 3.11.1

      - name: Setup
        run: |
          sudo apt update
          sudo apt-get install build-essential automake autoconf autoconf-archive texinfo libtool-bin yasm ninja-build ccache lcov

      - name: Restore artifacts, or setup vcpkg
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgGitCommitId: 12c2a93b4007612b5ffa980c9d2235eb0bcac10f

      - name: Install vcpkg packages and configure CMake
        shell: bash
        run: |
          vcpkg install
          cmake -G Ninja -D CMAKE_BUILD_TYPE=RelWithDebInfo -D ENABLE_TESTING:BOOL=TRUE -D ENABLE_COVERAGE:BOOL=TRUE -S . -B build

      - name: Configure
        run: cmake --preset=ci-coverage

      - name: Build
        run: cmake --build build/coverage -j 2

      - name: Test
        working-directory: build/coverage
        run: ctest --output-on-failure -j 2

      - name: Process coverage info
        working-directory: build/coverage
        run: |
          lcov -c -d . -o coverage.info
          lcov -l coverage.info

      - name: Submit to codecov.io
        uses: codecov/codecov-action@v3
        with:
          files: build/coverage/coverage.info
          fail_ci_if_error: true
          verbose: true