name: Linux Clang

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: 15
          platform: x64

      - name: Setup
        run: |
          sudo apt update
          sudo apt-get install build-essential automake autoconf autoconf-archive texinfo libtool-bin yasm ninja-build ccache

      - name: Restore artifacts or setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: c6d6efed3e9b4242765bfe1b5c5befffd85f7b92

      - name: Configure
        run: cmake --preset=build

      - name: Build
        run:  cmake --build build -j 2

      - name: Test
        working-directory: build
        continue-on-error: true
        run: ctest --rerun-failed --output-on-failure -j 2