name: Linux

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: Cache vcpkg
        uses: actions/cache@v2
        id: cache-vcpkg
        with:
          path: $HOME/.cache/vcpkg
          key: ${{ runner.os }}-vcpkg-v1
          restore-keys: $${{ runner.os }}-vcpkg-v1

      - name: Setup GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64

      - name: Setup
        run: |
          sudo apt update
          sudo apt-get install build-essential automake autoconf autoconf-archive texinfo libtool-bin yasm ninja-build ccache
          cd $VCPKG_INSTALLATION_ROOT
          git pull
          ./bootstrap-vcpkg.sh
          vcpkg integrate install

      - name: Install vcpkg packages and configure CMake
        shell: bash
        run: |
          vcpkg install --feature-flags=manifests
          export VCPKG_ROOT="$VCPKG_INSTALLATION_ROOT"
          cmake -G Ninja -D CMAKE_BUILD_TYPE=RelWithDebInfo -D ENABLE_TESTING:BOOL=TRUE -D ENABLE_COVERAGE:BOOL=TRUE -S . -B build

      - name: Build
        run: cmake --build build