name: Linux Clang

on: [push, pull_request, workflow_dispatch]

concurrency:
  # Documentation suggests ${{ github.head_ref }}, but that's only available on pull_request/pull_request_target triggers, so using ${{ github.ref }}.
  # On master, we want all builds to complete even if merging happens faster to make it easier to discover at which point something broke.
  group: ${{ github.ref == 'refs/heads/master' && format('ci-master-{0}', github.sha) || format('ci-{0}', github.ref) }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup
        run: |
          sudo apt update
          sudo apt-get install build-essential automake autoconf autoconf-archive texinfo libtool-bin yasm ninja-build ccache

      - name: Setup Clang
        uses: pkgxdev/setup@v1
        with:
          +: clang@16

      -  run: clang --version

      - name: Restore artifacts or setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: 01acfdfde3ed99280d3883a8fccd5fa4408f5214

      - name: Configure
        run: cmake --preset=build

      - name: Build
        run:  cmake --build build -j 2

      - name: Test
        working-directory: build
        continue-on-error: true
        run: ctest --rerun-failed --output-on-failure -j 2