name: Linux GCC

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 12
          platform: x64

      - name: Setup
        run: |
          sudo apt update
          sudo apt-get install build-essential automake autoconf autoconf-archive texinfo libtool-bin yasm ninja-build ccache

      - name: Restore artifacts, or setup vcpkg
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgGitCommitId: 12c2a93b4007612b5ffa980c9d2235eb0bcac10f

      - name: Install vcpkg packages and configure CMake
        shell: bash
        run: |
          vcpkg install
          cmake -G Ninja -D CMAKE_BUILD_TYPE=RelWithDebInfo -D ENABLE_TESTING:BOOL=TRUE -S . -B build

      - name: Build
        run: |
          gcc -v
          cmake --build build