name: Linux GCC

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 12
          platform: x64

      - name: Setup
        run: |
          sudo apt update
          sudo apt-get install build-essential automake autoconf autoconf-archive texinfo libtool-bin yasm ninja-build ccache

      - name: Restore artifacts or setup vcpkg
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgGitCommitId: b81bc3a83fdbdffe80325eeabb2ec735a1f3c29d

      - name: Configure
        run: cmake --preset=build

      - name: Build
        run: cmake --build build -j 2