name: macOS

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true

    - name: Setup
      run: |
        brew install automake autoconf autoconf-archive libtool texinfo yasm ninja python ccache pkg-config

    - name: Restore artifacts or setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: 70fd7df7a9e2d3d47ab6bf87fc7347a6c2d06fda

    - name: Configure
      run: cmake --preset=build

    - name: Build
      run: cmake --build build -j 2

    - name: Test
      working-directory: build
      continue-on-error: true
      run: ctest --rerun-failed --output-on-failure -j 2