name: macOS

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true

    - name: Setup
      run: |
        brew install automake autoconf autoconf-archive libtool texinfo yasm ninja python ccache

    - name: Restore artifacts, or setup vcpkg
      uses: lukka/run-vcpkg@v10
      with:
        vcpkgGitCommitId: 89295c9fe22e97ca9e380a6c771ccf2ff09dca95

    - name: Install vcpkg packages and configure CMake
      shell: bash
      run: |
        vcpkg install --feature-flags=manifests
        cmake -G Ninja -D CMAKE_BUILD_TYPE=RelWithDebInfo -D ENABLE_TESTING:BOOL=TRUE -S . -B build

    - name: Build
      run: cmake --build build