name: macOS

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true

    - name: Setup
      run: |
        brew install automake autoconf autoconf-archive libtool texinfo yasm ninja python ccache

    - name: Restore artifacts, or setup vcpkg
      uses: lukka/run-vcpkg@v10
      with:
        vcpkgGitCommitId: 6d6910d8cb7331b0dc35b38ce663f2aa6a4663f4

    - name: Install vcpkg packages and configure CMake
      shell: bash
      run: |
        vcpkg install
        cmake -G Ninja -D CMAKE_BUILD_TYPE=RelWithDebInfo -D ENABLE_TESTING:BOOL=TRUE -S . -B build

    - name: Build
      run: |
        gcc -v
        cmake --build build