name: macOS

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true

    - name: Setup
      run: |
        brew install automake autoconf autoconf-archive libtool texinfo yasm ninja python ccache

    - name: Restore artifacts or setup vcpkg
      uses: lukka/run-vcpkg@v10
      with:
        vcpkgGitCommitId: 12c2a93b4007612b5ffa980c9d2235eb0bcac10f

    - name: Install packages
      shell: bash
      run: vcpkg install

    - name: Configure
      run: cmake --preset=build

    - name: Build
      run: cmake --build build -j 2