name: macOS

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true

    - name: Setup
      run: |
        brew install automake autoconf autoconf-archive libtool texinfo yasm ninja python ccache

    - name: Restore artifacts or setup vcpkg
      uses: lukka/run-vcpkg@v10
      with:
        vcpkgGitCommitId: 69efe9cc2df0015f0bb2d37d55acde4a75c9a25b

    - name: Configure
      run: cmake --preset=build

    - name: Build
      run: cmake --build build -j 2