name: macOS

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true

    - name: Setup
      run: |
        brew install automake autoconf autoconf-archive libtool texinfo yasm ninja python ccache

    - name: Restore artifacts or setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: 5d2a0a9814db499f6ba2e847ca7ab5912badcdbf

    - name: Configure
      run: cmake --preset=build

    - name: Build
      run: cmake --build build -j 2

    - name: Test
      working-directory: build
      continue-on-error: true
      run: ctest --rerun-failed --output-on-failure -j 2