name: macOS

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true

    - name: Setup
      run: |
        brew install automake autoconf autoconf-archive libtool texinfo yasm ninja python ccache

    - name: Restore artifacts or setup vcpkg
      uses: lukka/run-vcpkg@v10
      with:
        vcpkgGitCommitId: 65e91ebd9e1d8a5c054b98b87abef68d5d36ce6f

    - name: Configure
      run: cmake --preset=build

    - name: Build
      run: cmake --build build -j 2