name: macOS

on:
  push:
    branches:
      - main
      - develop
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true

    - name: Setup
      run: |
        rm /usr/local/bin/2to3
        rm /usr/local/bin/2to3-3.12
        rm /usr/local/bin/idle3
        rm /usr/local/bin/idle3.12
        rm /usr/local/bin/pydoc3
        rm /usr/local/bin/pydoc3.12
        rm /usr/local/bin/python3
        rm /usr/local/bin/python3.12
        rm /usr/local/bin/python3-config
        rm /usr/local/bin/python3.12-config
        brew install automake autoconf autoconf-archive libtool texinfo yasm ninja python ccache pkg-config

    - name: Restore artifacts or setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: ${{ vars.VCPKG_GIT_COMMIT_ID }}

    - name: Configure
      run: cmake --preset=build

    - name: Build
      run: cmake --build build -j 2

    - name: Test
      working-directory: build
      continue-on-error: true
      run: ctest --rerun-failed --output-on-failure -j 2