name: macOS

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true

    - name: Setup
      run: |
        rm /usr/local/bin/2to3
        rm /usr/local/bin/2to3-3.11
        rm /usr/local/bin/idle3
        rm /usr/local/bin/idle3.11
        rm /usr/local/bin/pydoc3
        brew install automake autoconf autoconf-archive libtool texinfo yasm ninja python ccache pkg-config

    - name: Restore artifacts or setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: 2a01db703fec3cdd13ca884a6a84d1505df2d235

    - name: Configure
      run: cmake --preset=build

    - name: Build
      run: cmake --build build -j 2

    - name: Test
      working-directory: build
      continue-on-error: true
      run: ctest --rerun-failed --output-on-failure -j 2