---
name: Memory Sanitizer (experimental)

"on":
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/_sanitizer.yml
    with:
      preset: msan
      job_name: MemorySanitizer (experimental)
      msan_options: halt_on_error=1:symbolize=1
