name: Valgrind

on: [workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup
        run: |
          sudo apt update
          sudo apt-get install build-essential automake autoconf autoconf-archive texinfo libtool-bin yasm ninja-build ccache valgrind

      - name: Setup GCC
        uses: pkgxdev/setup@v1
        with:
          +: gcc@13

      -  run: gcc --version

      - name: Restore artifacts or setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: 2a01db703fec3cdd13ca884a6a84d1505df2d235

      - name: Configure
        run: cmake --preset=valgrind

      - name: Build
        run: cmake --build build -j 2

      - name: Run memcheck
        working-directory: build
        continue-on-error: true
        run: |
          ctest -VV -T memcheck --verbose

      - name: Run Valgrind
        working-directory: src
        continue-on-error: true
        run: |
          pwd
          valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --verbose ./initialize --s n32000 -t11 -o
          valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --verbose ./cdt-opt
          valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --verbose ./cdt --s -n64 -t3 -a.6 -k1.1 -l.1 -p10