name: Whitespace

on: [workflow_dispatch]

jobs:
  whitespace:
    name: Find Trailing Whitespace
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: erictleung/find-file-whitespace@main