name: Whitespace

on: [push, pull_request, workflow_dispatch]

jobs:
  whitespace:
    name: Find Trailing Whitespace
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: erictleung/find-file-whitespace@main