name: Windows

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    env:
      VCPKG_DEFAULT_TRIPLET: x64-windows
      VCPKG_ROOT: C:\vcpkg

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup Clang
        uses: egor-tensin/setup-clang@v1
        with:
          platform: x64

      - name: Restore artifacts, or setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: 7e4d2ff73b643ca2c685c6cfe0783a0f62cfb15c

      - name: Install vcpkg packages and configure CMake
        run: |
          vcpkg install
          cmake -D CMAKE_BUILD_TYPE=RelWithDebInfo -D ENABLE_TESTING:BOOL=TRUE -D ENABLE_CACHE:BOOL=FALSE -S . -B build

      - name: Build
        run: cmake --build build